id: application.list
version: 7.6.7
source_object: fortios_application_list
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_application_list.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v6.0.0
      - ''
    description: List name.
  comment:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Comments.
  replacemsg_group:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Replacement message group. Source system.replacemsg-group.name.
    references:
    - system.replacemsg-group.name
  extended_log:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable extended logging.
  other_application_action:
    type: enum
    raw_type: string
    choices:
    - pass
    - block
    version_ranges:
    - - v6.0.0
      - ''
    description: Action for other applications.
  app_replacemsg:
    type: enum
    raw_type: string
    choices:
    - disable
    - enable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable replacement messages for blocked applications.
  other_application_log:
    type: enum
    raw_type: string
    choices:
    - disable
    - enable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable logging for other applications.
  enforce_default_app_port:
    type: enum
    raw_type: string
    choices:
    - disable
    - enable
    version_ranges:
    - - v6.2.0
      - ''
    description: Enable/disable default application port enforcement for allowed applications.
  force_inclusion_ssl_di_sigs:
    type: enum
    raw_type: string
    choices:
    - disable
    - enable
    version_ranges:
    - - v6.2.0
      - v6.2.0
    - - v6.2.5
      - ''
    description: Enable/disable forced inclusion of SSL deep inspection signatures.
  unknown_application_action:
    type: enum
    raw_type: string
    choices:
    - pass
    - block
    version_ranges:
    - - v6.0.0
      - ''
    description: Pass or block traffic from unknown applications.
  unknown_application_log:
    type: enum
    raw_type: string
    choices:
    - disable
    - enable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable logging for unknown applications.
  p2p_block_list:
    type: enum
    raw_type: list
    choices:
    - edonkey
    - bittorrent
    - skype
    multiple_values: true
    elements: str
    version_ranges:
    - - v7.0.0
      - ''
    description: P2P applications to be block listed.
  deep_app_inspection:
    type: enum
    raw_type: string
    choices:
    - disable
    - enable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable deep application inspection.
  options:
    type: enum
    raw_type: list
    choices:
    - allow-dns
    - allow-icmp
    - allow-http
    - allow-ssl
    multiple_values: true
    elements: str
    version_ranges:
    - - v6.0.0
      - ''
    description: Basic application protocol signatures allowed by default.
  entries:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: Application list entries.
    children:
      id:
        type: integer
        raw_type: integer
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: Entry ID. see <a href='#notes'>Notes</a>.
      risk:
        type: list
        raw_type: list
        elements: dict
        version_ranges:
        - - v6.0.0
          - ''
        description: Risk, or impact, of allowing traffic from this application to occur (1 - 5; Low, Elevated, Medium, High,
          and Critical).
        children:
          level:
            type: integer
            raw_type: integer
            required: true
            version_ranges:
            - - v6.0.0
              - ''
            description: Risk, or impact, of allowing traffic from this application to occur (1 - 5; Low, Elevated, Medium,
              High, and Critical). see <a href='#notes'>Notes</a>.
      category:
        type: list
        raw_type: list
        elements: dict
        version_ranges:
        - - v6.0.0
          - ''
        description: Category ID list.
        children:
          id:
            type: integer
            raw_type: integer
            required: true
            version_ranges:
            - - v6.0.0
              - ''
            description: Application category ID. see <a href='#notes'>Notes</a>.
      application:
        type: list
        raw_type: list
        elements: dict
        version_ranges:
        - - v6.0.0
          - ''
        description: ID of allowed applications.
        children:
          id:
            type: integer
            raw_type: integer
            required: true
            version_ranges:
            - - v6.0.0
              - ''
            description: Application IDs. see <a href='#notes'>Notes</a>.
      protocols:
        type: list
        raw_type: list
        multiple_values: true
        elements: str
        version_ranges:
        - - v6.0.0
          - ''
        description: Application protocol filter.
      vendor:
        type: list
        raw_type: list
        multiple_values: true
        elements: str
        version_ranges:
        - - v6.0.0
          - ''
        description: Application vendor filter.
      technology:
        type: list
        raw_type: list
        multiple_values: true
        elements: str
        version_ranges:
        - - v6.0.0
          - ''
        description: Application technology filter.
      behavior:
        type: list
        raw_type: list
        multiple_values: true
        elements: str
        version_ranges:
        - - v6.0.0
          - ''
        description: Application behavior filter.
      popularity:
        type: enum
        raw_type: list
        choices:
        - '1'
        - '2'
        - '3'
        - '4'
        - '5'
        multiple_values: true
        elements: str
        version_ranges:
        - - v6.0.0
          - ''
        description: Application popularity filter (1 - 5, from least to most popular).
      exclusion:
        type: list
        raw_type: list
        elements: dict
        version_ranges:
        - - v6.2.7
          - v6.2.7
        - - v6.4.4
          - ''
        description: ID of excluded applications.
        children:
          id:
            type: integer
            raw_type: integer
            required: true
            version_ranges:
            - - v6.2.7
              - v6.2.7
            - - v6.4.4
              - ''
            description: Excluded application IDs. see <a href='#notes'>Notes</a>.
      parameters:
        type: list
        raw_type: list
        elements: dict
        version_ranges:
        - - v6.0.0
          - ''
        description: Application parameters.
        children:
          id:
            type: integer
            raw_type: integer
            required: true
            version_ranges:
            - - v6.0.0
              - ''
            description: Parameter tuple ID. see <a href='#notes'>Notes</a>.
          members:
            type: list
            raw_type: list
            elements: dict
            version_ranges:
            - - v6.4.0
              - ''
            description: Parameter tuple members.
            children:
              id:
                type: integer
                raw_type: integer
                required: true
                version_ranges:
                - - v6.4.0
                  - ''
                description: Parameter. see <a href='#notes'>Notes</a>.
              name:
                type: string
                raw_type: string
                version_ranges:
                - - v6.4.0
                  - ''
                description: Parameter name.
              value:
                type: string
                raw_type: string
                version_ranges:
                - - v6.4.0
                  - ''
                description: Parameter value.
      action:
        type: enum
        raw_type: string
        choices:
        - pass
        - block
        - reset
        version_ranges:
        - - v6.0.0
          - ''
        description: Pass or block traffic, or reset connection for traffic from this application.
      log:
        type: enum
        raw_type: string
        choices:
        - disable
        - enable
        version_ranges:
        - - v6.0.0
          - ''
        description: Enable/disable logging for this application list.
      log_packet:
        type: enum
        raw_type: string
        choices:
        - disable
        - enable
        version_ranges:
        - - v6.0.0
          - ''
        description: Enable/disable packet logging.
      rate_count:
        type: integer
        raw_type: integer
        version_ranges:
        - - v6.0.0
          - ''
        description: Count of the rate.
      rate_duration:
        type: integer
        raw_type: integer
        version_ranges:
        - - v6.0.0
          - ''
        description: Duration (sec) of the rate.
      rate_mode:
        type: enum
        raw_type: string
        choices:
        - periodical
        - continuous
        version_ranges:
        - - v6.0.0
          - ''
        description: Rate limit mode.
      rate_track:
        type: enum
        raw_type: string
        choices:
        - none
        - src-ip
        - dest-ip
        - dhcp-client-mac
        - dns-domain
        version_ranges:
        - - v6.0.0
          - ''
        description: Track the packet protocol field.
      session_ttl:
        type: integer
        raw_type: integer
        version_ranges:
        - - v6.0.0
          - ''
        description: Session TTL (0 = default).
      shaper:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Traffic shaper. Source firewall.shaper.traffic-shaper.name.
        references:
        - firewall.shaper.traffic-shaper.name
      shaper_reverse:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Reverse traffic shaper. Source firewall.shaper.traffic-shaper.name.
        references:
        - firewall.shaper.traffic-shaper.name
      per_ip_shaper:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Per-IP traffic shaper. Source firewall.shaper.per-ip-shaper.name.
        references:
        - firewall.shaper.per-ip-shaper.name
      quarantine:
        type: enum
        raw_type: string
        choices:
        - none
        - attacker
        version_ranges:
        - - v6.0.0
          - ''
        description: Quarantine method.
      quarantine_expiry:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Duration of quarantine. (Format
      quarantine_log:
        type: enum
        raw_type: string
        choices:
        - disable
        - enable
        version_ranges:
        - - v6.0.0
          - ''
        description: Enable/disable quarantine logging.
  control_default_network_services:
    type: enum
    raw_type: string
    choices:
    - disable
    - enable
    version_ranges:
    - - v6.2.0
      - ''
    description: Enable/disable enforcement of protocols over selected ports.
  default_network_services:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.2.0
      - ''
    description: Default network service entries.
    children:
      id:
        type: integer
        raw_type: integer
        required: true
        version_ranges:
        - - v6.2.0
          - ''
        description: Entry ID. see <a href='#notes'>Notes</a>.
      port:
        type: integer
        raw_type: integer
        version_ranges:
        - - v6.2.0
          - ''
        description: Port number.
      services:
        type: enum
        raw_type: list
        choices:
        - http
        - ssh
        - telnet
        - ftp
        - dns
        - smtp
        - pop3
        - imap
        - snmp
        - nntp
        - https
        multiple_values: true
        elements: str
        version_ranges:
        - - v6.2.0
          - ''
        description: Network protocols.
      violation_action:
        type: enum
        raw_type: string
        choices:
        - pass
        - monitor
        - block
        version_ranges:
        - - v6.2.0
          - ''
        description: Action for protocols not in the allowlist for selected port.
