id: certificate.crl
version: 7.6.7
source_object: fortios_certificate_crl
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_certificate_crl.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v6.0.0
      - ''
    description: Name.
  crl:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Certificate Revocation List as a PEM file.
  range:
    type: enum
    raw_type: string
    choices:
    - global
    - vdom
    version_ranges:
    - - v6.0.0
      - ''
    description: Either global or VDOM IP address range for the certificate.
  source:
    type: enum
    raw_type: string
    choices:
    - factory
    - user
    - bundle
    version_ranges:
    - - v6.0.0
      - ''
    description: Certificate source type.
  update_vdom:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: VDOM for CRL update. Source system.vdom.name.
    references:
    - system.vdom.name
  ldap_server:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: LDAP server name for CRL auto-update.
  ldap_username:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: LDAP server user name.
  ldap_password:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: LDAP server user password.
  http_url:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: HTTP server URL for CRL auto-update.
  scep_url:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: SCEP server URL for CRL auto-update.
  scep_cert:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Local certificate for SCEP communication for CRL auto-update. Source certificate.local.name.
    references:
    - certificate.local.name
  update_interval:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Time in seconds before the FortiGate checks for an updated CRL. Set to 0 to update only when it expires.
  source_ip:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Source IP address for communications to a HTTP or SCEP CA server.
