id: certificate.hsm-local
version: 7.6.7
source_object: fortios_certificate_hsm_local
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_certificate_hsm_local.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v7.6.3
      - ''
    description: Name.
  comments:
    type: string
    raw_type: string
    version_ranges:
    - - v7.6.3
      - ''
    description: Comment.
  vendor:
    type: enum
    raw_type: string
    choices:
    - unknown
    - gch
    version_ranges:
    - - v7.6.3
      - ''
    description: HSM vendor.
  api_version:
    type: enum
    raw_type: string
    choices:
    - unknown
    - gch-default
    version_ranges:
    - - v7.6.3
      - ''
    description: API version for communicating with HSM.
  certificate:
    type: string
    raw_type: string
    version_ranges:
    - - v7.6.3
      - ''
    description: PEM format certificate.
  range:
    type: enum
    raw_type: string
    choices:
    - global
    - vdom
    version_ranges:
    - - v7.6.3
      - ''
    description: Either a global or VDOM IP address range for the certificate.
  source:
    type: enum
    raw_type: string
    choices:
    - factory
    - user
    - bundle
    version_ranges:
    - - v7.6.3
      - ''
    description: Certificate source type.
  gch_project:
    type: string
    raw_type: string
    version_ranges:
    - - v7.6.3
      - ''
    description: Google Cloud HSM project ID.
  gch_location:
    type: string
    raw_type: string
    version_ranges:
    - - v7.6.3
      - ''
    description: Google Cloud HSM location.
  gch_keyring:
    type: string
    raw_type: string
    version_ranges:
    - - v7.6.3
      - ''
    description: Google Cloud HSM keyring.
  gch_cryptokey:
    type: string
    raw_type: string
    version_ranges:
    - - v7.6.3
      - ''
    description: Google Cloud HSM cryptokey.
  gch_cryptokey_version:
    type: string
    raw_type: string
    version_ranges:
    - - v7.6.3
      - ''
    description: Google Cloud HSM cryptokey version.
  gch_cloud_service_name:
    type: string
    raw_type: string
    version_ranges:
    - - v7.6.3
      - ''
    description: Cloud service config name to generate access token. Source system.cloud-service.name.
    references:
    - system.cloud-service.name
  gch_cryptokey_algorithm:
    type: enum
    raw_type: string
    choices:
    - rsa-sign-pkcs1-2048-sha256
    - rsa-sign-pkcs1-3072-sha256
    - rsa-sign-pkcs1-4096-sha256
    - rsa-sign-pkcs1-4096-sha512
    - rsa-sign-pss-2048-sha256
    - rsa-sign-pss-3072-sha256
    - rsa-sign-pss-4096-sha256
    - rsa-sign-pss-4096-sha512
    - ec-sign-p256-sha256
    - ec-sign-p384-sha384
    - ec-sign-secp256k1-sha256
    version_ranges:
    - - v7.6.3
      - ''
    description: Google Cloud HSM cryptokey algorithm.
