id: dlp.sensor
version: 7.6.7
source_object: fortios_dlp_sensor
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_dlp_sensor.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v6.0.0
      - ''
    description: Name of table containing the sensor.
  match_type:
    type: enum
    raw_type: string
    choices:
    - match-all
    - match-any
    - match-eval
    version_ranges:
    - - v7.2.0
      - ''
    description: Logical relation between entries .
  eval:
    type: string
    raw_type: string
    version_ranges:
    - - v7.2.0
      - ''
    description: Expression to evaluate.
  comment:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Optional comments.
  entries:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v7.2.0
      - ''
    description: DLP sensor entries.
    children:
      id:
        type: integer
        raw_type: integer
        required: true
        version_ranges:
        - - v7.2.0
          - ''
        description: ID. see <a href='#notes'>Notes</a>.
      dictionary:
        type: string
        raw_type: string
        version_ranges:
        - - v7.2.0
          - ''
        description: Select a DLP dictionary or exact-data-match. Source dlp.dictionary.name dlp.exact-data-match.name.
        references:
        - dlp.dictionary.name
        - dlp.exact-data-match.name
      count:
        type: integer
        raw_type: integer
        version_ranges:
        - - v7.2.0
          - ''
        description: Count of dictionary matches to trigger sensor entry match (Dictionary might not be able to trigger more
          than once based on its "repeat" option, 1 - 255).
      status:
        type: enum
        raw_type: string
        choices:
        - enable
        - disable
        version_ranges:
        - - v7.2.0
          - ''
        description: Enable/disable this entry.
