id: dlp.sensitivity
version: 7.6.7
source_object: fortios_dlp_sensitivity
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_dlp_sensitivity.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v6.2.0
      - ''
    description: DLP Sensitivity Levels.
