id: dlp.dictionary
version: 7.6.7
source_object: fortios_dlp_dictionary
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_dlp_dictionary.py
root_type: list
attributes:
  uuid:
    type: string
    raw_type: string
    version_ranges:
    - - v7.2.0
      - ''
    description: Universally Unique Identifier (UUID; automatically assigned but can be manually reset).
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v7.2.0
      - ''
    description: Name of table containing the dictionary.
  match_type:
    type: enum
    raw_type: string
    choices:
    - match-all
    - match-any
    version_ranges:
    - - v7.2.0
      - ''
    description: Logical relation between entries .
  match_around:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.4.0
      - ''
    description: Enable/disable match-around support.
  comment:
    type: string
    raw_type: string
    version_ranges:
    - - v7.2.0
      - ''
    description: Optional comments.
  entries:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v7.2.0
      - ''
    description: DLP dictionary entries.
    children:
      id:
        type: integer
        raw_type: integer
        required: true
        version_ranges:
        - - v7.2.0
          - ''
        description: ID. see <a href='#notes'>Notes</a>.
      type:
        type: string
        raw_type: string
        version_ranges:
        - - v7.2.0
          - ''
        description: Pattern type to match. Source dlp.data-type.name.
        references:
        - dlp.data-type.name
      pattern:
        type: string
        raw_type: string
        version_ranges:
        - - v7.2.0
          - ''
        description: Pattern to match.
      ignore_case:
        type: enum
        raw_type: string
        choices:
        - enable
        - disable
        version_ranges:
        - - v7.2.0
          - ''
        description: Enable/disable ignore case.
      repeat:
        type: enum
        raw_type: string
        choices:
        - enable
        - disable
        version_ranges:
        - - v7.2.0
          - ''
        description: Enable/disable repeat match.
      status:
        type: enum
        raw_type: string
        choices:
        - enable
        - disable
        version_ranges:
        - - v7.2.0
          - ''
        description: Enable/disable this pattern.
      comment:
        type: string
        raw_type: string
        version_ranges:
        - - v7.2.0
          - ''
        description: Optional comments.
