id: dlp.label
version: 7.6.7
source_object: fortios_dlp_label
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_dlp_label.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v7.6.3
      - ''
    description: Name of table containing the label.
  type:
    type: enum
    raw_type: string
    choices:
    - mpip
    - fortidata
    version_ranges:
    - - v7.6.3
      - ''
    description: Label type.
  mpip_type:
    type: enum
    raw_type: string
    choices:
    - remote
    - local
    version_ranges:
    - - v7.6.3
      - ''
    description: MPIP label type.
  connector:
    type: string
    raw_type: string
    version_ranges:
    - - v7.6.3
      - ''
    description: Name of SDN connector. Source system.sdn-connector.name.
    references:
    - system.sdn-connector.name
  comment:
    type: string
    raw_type: string
    version_ranges:
    - - v7.6.3
      - ''
    description: Optional comments.
  entries:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v7.6.3
      - ''
    description: DLP label entries.
    children:
      id:
        type: integer
        raw_type: integer
        required: true
        version_ranges:
        - - v7.6.3
          - ''
        description: ID. see <a href='#notes'>Notes</a>.
      fortidata_label_name:
        type: string
        raw_type: string
        version_ranges:
        - - v7.6.4
          - ''
        description: Name of FortiData label Source dlp.fdata-label.name.
        references:
        - dlp.fdata-label.name
      mpip_label_name:
        type: string
        raw_type: string
        version_ranges:
        - - v7.6.3
          - ''
        description: Name of MPIP label. Source dlp.mpip-label.name.
        references:
        - dlp.mpip-label.name
      guid:
        type: string
        raw_type: string
        version_ranges:
        - - v7.6.3
          - ''
        description: MPIP label guid.
