id: emailfilter.iptrust
version: 7.6.7
source_object: fortios_emailfilter_iptrust
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_emailfilter_iptrust.py
root_type: list
attributes:
  id:
    type: integer
    raw_type: integer
    required: true
    version_ranges:
    - - v6.2.0
      - ''
    description: ID. see <a href='#notes'>Notes</a>.
  name:
    type: string
    raw_type: string
    version_ranges:
    - - v6.2.0
      - ''
    description: Name of table.
  comment:
    type: string
    raw_type: string
    version_ranges:
    - - v6.2.0
      - ''
    description: Optional comments.
  entries:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.2.0
      - ''
    description: Spam filter trusted IP addresses.
    children:
      status:
        type: enum
        raw_type: string
        choices:
        - enable
        - disable
        version_ranges:
        - - v6.2.0
          - ''
        description: Enable/disable status.
      id:
        type: integer
        raw_type: integer
        required: true
        version_ranges:
        - - v6.2.0
          - ''
        description: Trusted IP entry ID. see <a href='#notes'>Notes</a>.
      addr_type:
        type: enum
        raw_type: string
        choices:
        - ipv4
        - ipv6
        version_ranges:
        - - v6.2.0
          - ''
        description: Type of address.
      ip4_subnet:
        type: string
        raw_type: string
        version_ranges:
        - - v6.2.0
          - ''
        description: IPv4 network address or network address/subnet mask bits.
      ip6_subnet:
        type: string
        raw_type: string
        version_ranges:
        - - v6.2.0
          - ''
        description: IPv6 network address/subnet mask bits.
