id: extension-controller.extender
version: 7.6.7
source_object: fortios_extension_controller_extender
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_extension_controller_extender.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v7.2.1
      - ''
    description: FortiExtender entry name.
  id:
    type: string
    raw_type: string
    version_ranges:
    - - v7.2.1
      - ''
    description: FortiExtender serial number.
  authorized:
    type: enum
    raw_type: string
    choices:
    - discovered
    - disable
    - enable
    version_ranges:
    - - v7.2.1
      - ''
    description: FortiExtender Administration (enable or disable).
  ext_name:
    type: string
    raw_type: string
    version_ranges:
    - - v7.2.1
      - ''
    description: FortiExtender name.
  description:
    type: string
    raw_type: string
    version_ranges:
    - - v7.2.1
      - ''
    description: Description.
  device_id:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.2.1
      - ''
    description: Device ID.
  extension_type:
    type: enum
    raw_type: string
    choices:
    - wan-extension
    - lan-extension
    version_ranges:
    - - v7.2.1
      - ''
    description: Extension type for this FortiExtender.
  profile:
    type: string
    raw_type: string
    version_ranges:
    - - v7.2.1
      - ''
    description: FortiExtender profile configuration. Source extension-controller.extender-profile.name.
    references:
    - extension-controller.extender-profile.name
  override_allowaccess:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.2.1
      - ''
    description: Enable to override the extender profile management access configuration.
  allowaccess:
    type: enum
    raw_type: list
    choices:
    - ping
    - telnet
    - http
    - https
    - ssh
    - snmp
    multiple_values: true
    elements: str
    version_ranges:
    - - v7.2.1
      - ''
    description: Control management access to the managed extender. Separate entries with a space.
  override_login_password_change:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.2.1
      - ''
    description: Enable to override the extender profile login-password (administrator password) setting.
  login_password_change:
    type: enum
    raw_type: string
    choices:
    - 'yes'
    - default
    - 'no'
    version_ranges:
    - - v7.2.1
      - ''
    description: Change or reset the administrator password of a managed extender (yes, default, or no).
  login_password:
    type: string
    raw_type: string
    version_ranges:
    - - v7.2.1
      - ''
    description: Set the managed extender"s administrator password.
  override_enforce_bandwidth:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.2.1
      - ''
    description: Enable to override the extender profile enforce-bandwidth setting.
  enforce_bandwidth:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.2.1
      - ''
    description: Enable/disable enforcement of bandwidth on LAN extension interface.
  bandwidth_limit:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.2.1
      - ''
    description: FortiExtender LAN extension bandwidth limit (Mbps).
  wan_extension:
    type: object
    raw_type: dict
    version_ranges:
    - - v7.2.1
      - ''
    description: FortiExtender wan extension configuration.
    children:
      modem1_extension:
        type: string
        raw_type: string
        version_ranges:
        - - v7.2.1
          - ''
        description: FortiExtender interface name. Source system.interface.name.
        references:
        - system.interface.name
      modem2_extension:
        type: string
        raw_type: string
        version_ranges:
        - - v7.2.1
          - ''
        description: FortiExtender interface name. Source system.interface.name.
        references:
        - system.interface.name
      modem1_pdn1_interface:
        type: string
        raw_type: string
        version_ranges:
        - - v7.6.1
          - ''
        description: FortiExtender interface name. Source system.interface.name.
        references:
        - system.interface.name
      modem1_pdn2_interface:
        type: string
        raw_type: string
        version_ranges:
        - - v7.6.1
          - ''
        description: FortiExtender interface name. Source system.interface.name.
        references:
        - system.interface.name
      modem1_pdn3_interface:
        type: string
        raw_type: string
        version_ranges:
        - - v7.6.1
          - ''
        description: FortiExtender interface name. Source system.interface.name.
        references:
        - system.interface.name
      modem1_pdn4_interface:
        type: string
        raw_type: string
        version_ranges:
        - - v7.6.1
          - ''
        description: FortiExtender interface name. Source system.interface.name.
        references:
        - system.interface.name
      modem2_pdn1_interface:
        type: string
        raw_type: string
        version_ranges:
        - - v7.6.1
          - ''
        description: FortiExtender interface name. Source system.interface.name.
        references:
        - system.interface.name
      modem2_pdn2_interface:
        type: string
        raw_type: string
        version_ranges:
        - - v7.6.1
          - ''
        description: FortiExtender interface name. Source system.interface.name.
        references:
        - system.interface.name
      modem2_pdn3_interface:
        type: string
        raw_type: string
        version_ranges:
        - - v7.6.1
          - ''
        description: FortiExtender interface name. Source system.interface.name.
        references:
        - system.interface.name
      modem2_pdn4_interface:
        type: string
        raw_type: string
        version_ranges:
        - - v7.6.1
          - ''
        description: FortiExtender interface name. Source system.interface.name.
        references:
        - system.interface.name
  firmware_provision_latest:
    type: enum
    raw_type: string
    choices:
    - disable
    - once
    version_ranges:
    - - v7.2.1
      - ''
    description: Enable/disable one-time automatic provisioning of the latest firmware version.
