id: file-filter.profile
version: 7.6.7
source_object: fortios_file_filter_profile
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_file_filter_profile.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v6.4.0
      - ''
    description: Profile name.
  comment:
    type: string
    raw_type: string
    version_ranges:
    - - v6.4.0
      - ''
    description: Comment.
  feature_set:
    type: enum
    raw_type: string
    choices:
    - flow
    - proxy
    version_ranges:
    - - v6.4.0
      - ''
    description: Flow/proxy feature set.
  replacemsg_group:
    type: string
    raw_type: string
    version_ranges:
    - - v6.4.0
      - ''
    description: Replacement message group. Source system.replacemsg-group.name.
    references:
    - system.replacemsg-group.name
  log:
    type: enum
    raw_type: string
    choices:
    - disable
    - enable
    version_ranges:
    - - v6.4.0
      - ''
    description: Enable/disable file-filter logging.
  extended_log:
    type: enum
    raw_type: string
    choices:
    - disable
    - enable
    version_ranges:
    - - v6.4.0
      - v6.4.0
    - - v6.4.4
      - ''
    description: Enable/disable file-filter extended logging.
  scan_archive_contents:
    type: enum
    raw_type: string
    choices:
    - disable
    - enable
    version_ranges:
    - - v6.4.0
      - ''
    description: Enable/disable archive contents scan.
  rules:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.4.0
      - ''
    description: File filter rules.
    children:
      name:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v6.4.0
          - ''
        description: File-filter rule name.
      comment:
        type: string
        raw_type: string
        version_ranges:
        - - v6.4.0
          - ''
        description: Comment.
      protocol:
        type: enum
        raw_type: list
        choices:
        - http
        - ftp
        - smtp
        - imap
        - pop3
        - mapi
        - cifs
        - ssh
        - websocket
        multiple_values: true
        elements: str
        version_ranges:
        - - v6.4.0
          - ''
        description: Protocols to apply rule to.
      action:
        type: enum
        raw_type: string
        choices:
        - log-only
        - block
        version_ranges:
        - - v6.4.0
          - ''
        description: Action taken for matched file.
      direction:
        type: enum
        raw_type: string
        choices:
        - incoming
        - outgoing
        - any
        version_ranges:
        - - v6.4.0
          - ''
        description: Traffic direction (HTTP, FTP, SSH, WEBSOCKET, CIFS, and MAPI only).
      password_protected:
        type: enum
        raw_type: string
        choices:
        - 'yes'
        - any
        version_ranges:
        - - v6.4.0
          - ''
        description: Match password-protected files.
      file_type:
        type: list
        raw_type: list
        elements: dict
        version_ranges:
        - - v6.4.0
          - ''
        description: Select file type.
        children:
          name:
            type: string
            raw_type: string
            required: true
            version_ranges:
            - - v6.4.0
              - ''
            description: File type name. Source antivirus.filetype.name.
            references:
            - antivirus.filetype.name
