id: firewall.address6
version: 7.6.7
source_object: fortios_firewall_address6
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_firewall_address6.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v6.0.0
      - ''
    description: Address name.
  uuid:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Universally Unique Identifier (UUID; automatically assigned but can be manually reset).
  fabric_object:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.4.4
      - ''
    description: Security Fabric global object setting.
  type:
    type: enum
    raw_type: string
    choices:
    - ipprefix
    - iprange
    - fqdn
    - geography
    - dynamic
    - template
    - mac
    - route-tag
    - wildcard
    version_ranges:
    - - v6.0.0
      - ''
    description: Type of IPv6 address object .
  route_tag:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.4.0
      - ''
    description: route-tag address.
  macaddr:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v7.0.0
      - ''
    description: Multiple MAC address ranges.
    children:
      macaddr:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v7.0.0
          - ''
        description: MAC address ranges <start>[-<end>] separated by space.
  sdn:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: SDN. Source system.sdn-connector.name.
    references:
    - system.sdn-connector.name
  ip6:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: 'IPv6 address prefix (format: xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx/xxx).'
  wildcard:
    type: string
    raw_type: string
    version_ranges:
    - - v7.6.4
      - ''
    description: IPv6 address and wildcard netmask.
  start_ip:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: 'First IP address (inclusive) in the range for the address (format: xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx).'
  end_ip:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: 'Final IP address (inclusive) in the range for the address (format: xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx).'
  fqdn:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Fully qualified domain name.
  country:
    type: string
    raw_type: string
    version_ranges:
    - - v6.4.0
      - ''
    description: IPv6 addresses associated to a specific country.
  cache_ttl:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Minimal TTL of individual IPv6 addresses in FQDN cache.
  passive_fqdn_learning:
    type: enum
    raw_type: string
    choices:
    - disable
    - enable
    version_ranges:
    - - v7.6.5
      - ''
    description: Enable/disable passive learning of FQDNs.  When enabled, the FortiGate learns, trusts, and saves FQDNs from
      endpoint DNS queries .
  color:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Integer value to determine the color of the icon in the GUI (range 1 to 32).
  obj_id:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Object ID for NSX.
  tagging:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: Config object tagging.
    children:
      name:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: Tagging entry name.
      category:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Tag category. Source system.object-tagging.category.
        references:
        - system.object-tagging.category
      tags:
        type: list
        raw_type: list
        elements: dict
        version_ranges:
        - - v6.0.0
          - ''
        description: Tags.
        children:
          name:
            type: string
            raw_type: string
            required: true
            version_ranges:
            - - v6.0.0
              - ''
            description: Tag name. Source system.object-tagging.tags.name.
            references:
            - system.object-tagging.tags.name
  comment:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Comment.
  template:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: IPv6 address template. Source firewall.address6-template.name.
    references:
    - firewall.address6-template.name
  subnet_segment:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: IPv6 subnet segments.
    children:
      name:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: Name.
      type:
        type: enum
        raw_type: string
        choices:
        - any
        - specific
        version_ranges:
        - - v6.0.0
          - ''
        description: Subnet segment type.
      value:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Subnet segment value.
  host_type:
    type: enum
    raw_type: string
    choices:
    - any
    - specific
    version_ranges:
    - - v6.0.0
      - ''
    description: Host type.
  host:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Host Address.
  tenant:
    type: string
    raw_type: string
    version_ranges:
    - - v7.2.1
      - ''
    description: Tenant.
  epg_name:
    type: string
    raw_type: string
    version_ranges:
    - - v7.2.1
      - ''
    description: Endpoint group name.
  sdn_tag:
    type: string
    raw_type: string
    version_ranges:
    - - v7.2.1
      - ''
    description: SDN Tag.
  filter:
    type: string
    raw_type: string
    version_ranges:
    - - v7.6.1
      - ''
    description: Match criteria filter.
  list:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: IP address list.
    children:
      ip:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: IP.
  sdn_addr_type:
    type: enum
    raw_type: string
    choices:
    - private
    - public
    - all
    version_ranges:
    - - v7.6.1
      - ''
    description: Type of addresses to collect.
