id: firewall.ssh.host-key
version: 7.6.7
source_object: fortios_firewall_ssh_host_key
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_firewall_ssh_host_key.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v6.0.0
      - ''
    description: SSH public key name.
  status:
    type: enum
    raw_type: string
    choices:
    - trusted
    - revoked
    version_ranges:
    - - v6.0.0
      - ''
    description: Set the trust status of the public key.
  type:
    type: enum
    raw_type: string
    choices:
    - RSA
    - DSA
    - ECDSA
    - ED25519
    - RSA-CA
    - DSA-CA
    - ECDSA-CA
    - ED25519-CA
    version_ranges:
    - - v6.0.0
      - ''
    description: Set the type of the public key.
  nid:
    type: enum
    raw_type: string
    choices:
    - '256'
    - '384'
    - '521'
    version_ranges:
    - - v6.0.0
      - ''
    description: Set the nid of the ECDSA key.
  usage:
    type: enum
    raw_type: string
    choices:
    - transparent-proxy
    - access-proxy
    version_ranges:
    - - v7.0.1
      - ''
    description: Usage for this public key.
  ip:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: IP address of the SSH server.
  port:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Port of the SSH server.
  hostname:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Hostname of the SSH server to match SSH certificate principals.
  public_key:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: SSH public key.
