id: firewall.ip-translation
version: 7.6.7
source_object: fortios_firewall_ip_translation
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_firewall_ip_translation.py
root_type: list
attributes:
  transid:
    type: integer
    raw_type: integer
    required: true
    version_ranges:
    - - v6.0.0
      - ''
    description: IP translation ID. see <a href='#notes'>Notes</a>.
  type:
    type: enum
    raw_type: string
    choices:
    - SCTP
    version_ranges:
    - - v6.0.0
      - ''
    description: 'IP translation type (option: SCTP).'
  startip:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: First IPv4 address (inclusive) in the range of the addresses to be translated (format xxx.xxx.xxx.xxx).
  endip:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Final IPv4 address (inclusive) in the range of the addresses to be translated (format xxx.xxx.xxx.xxx).
  map_startip:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Address to be used as the starting point for translation in the range (format xxx.xxx.xxx.xxx).
