id: firewall.multicast-address6
version: 7.6.7
source_object: fortios_firewall_multicast_address6
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_firewall_multicast_address6.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v6.0.0
      - ''
    description: IPv6 multicast address name.
  ip6:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: 'IPv6 address prefix (format: xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx/xxx).'
  comment:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Comment.
  color:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Color of icon on the GUI.
  tagging:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: Config object tagging.
    children:
      name:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: Tagging entry name.
      category:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Tag category. Source system.object-tagging.category.
        references:
        - system.object-tagging.category
      tags:
        type: list
        raw_type: list
        elements: dict
        version_ranges:
        - - v6.0.0
          - ''
        description: Tags.
        children:
          name:
            type: string
            raw_type: string
            required: true
            version_ranges:
            - - v6.0.0
              - ''
            description: Tag name. Source system.object-tagging.tags.name.
            references:
            - system.object-tagging.tags.name
