id: firewall.acl6
version: 7.6.7
source_object: fortios_firewall_acl6
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_firewall_acl6.py
root_type: list
attributes:
  policyid:
    type: integer
    raw_type: integer
    required: true
    version_ranges:
    - - v6.0.0
      - ''
    description: Policy ID. see <a href='#notes'>Notes</a>.
  status:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable access control list status.
  name:
    type: string
    raw_type: string
    version_ranges:
    - - v6.4.0
      - v6.4.0
    - - v6.4.4
      - ''
    description: Policy name.
  comments:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Comment.
  interface:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Interface name. Source system.zone.name system.interface.name.
    references:
    - system.interface.name
    - system.zone.name
  srcaddr:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: Source address name.
    children:
      name:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: Address name. Source firewall.address6.name firewall.addrgrp6.name.
        references:
        - firewall.address6.name
        - firewall.addrgrp6.name
  dstaddr:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: Destination address name.
    children:
      name:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: Address name. Source firewall.address6.name firewall.addrgrp6.name.
        references:
        - firewall.address6.name
        - firewall.addrgrp6.name
  service:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: Service name.
    children:
      name:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: Service name. Source firewall.service.custom.name firewall.service.group.name.
        references:
        - firewall.service.custom.name
        - firewall.service.group.name
  fragment:
    type: enum
    raw_type: string
    choices:
    - pass
    - drop
    version_ranges:
    - - v7.4.1
      - ''
    description: Pass/drop fragments that match L3 information.
