id: firewall.vipgrp
version: 7.6.7
source_object: fortios_firewall_vipgrp
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_firewall_vipgrp.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v6.0.0
      - ''
    description: VIP group name.
  uuid:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Universally Unique Identifier (UUID; automatically assigned but can be manually reset).
  interface:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Interface. Source system.interface.name.
    references:
    - system.interface.name
  color:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Integer value to determine the color of the icon in the GUI (range 1 to 32).
  comments:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Comment.
  member:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: Member VIP objects of the group (Separate multiple objects with a space).
    children:
      name:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: VIP name. Source firewall.vip.name.
        references:
        - firewall.vip.name
