id: firewall.addrgrp
version: 7.6.7
source_object: fortios_firewall_addrgrp
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_firewall_addrgrp.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v6.0.0
      - ''
    description: Address group name.
  type:
    type: enum
    raw_type: string
    choices:
    - default
    - folder
    version_ranges:
    - - v6.4.0
      - ''
    description: Address group type.
  category:
    type: enum
    raw_type: string
    choices:
    - default
    - ztna-ems-tag
    - ztna-geo-tag
    - telemetry
    version_ranges:
    - - v7.0.0
      - ''
    description: Address group category.
  allow_routing:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable use of this group in routing configurations.
  member:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: Address objects contained within the group.
    children:
      name:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: Address name. Source firewall.address.name firewall.addrgrp.name.
        references:
        - firewall.address.name
        - firewall.addrgrp.name
  comment:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Comment.
  uuid:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Universally Unique Identifier (UUID; automatically assigned but can be manually reset).
  fabric_object:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.4.4
      - ''
    description: Security Fabric global object setting.
  exclude:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.2.0
      - ''
    description: Enable/disable address exclusion.
  exclude_member:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.2.0
      - ''
    description: Address exclusion member.
    children:
      name:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v6.2.0
          - ''
        description: Address name. Source firewall.address.name firewall.addrgrp.name.
        references:
        - firewall.address.name
        - firewall.addrgrp.name
  color:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Color of icon on the GUI.
  tagging:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: Config object tagging.
    children:
      name:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: Tagging entry name.
      category:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Tag category. Source system.object-tagging.category.
        references:
        - system.object-tagging.category
      tags:
        type: list
        raw_type: list
        elements: dict
        version_ranges:
        - - v6.0.0
          - ''
        description: Tags.
        children:
          name:
            type: string
            raw_type: string
            required: true
            version_ranges:
            - - v6.0.0
              - ''
            description: Tag name. Source system.object-tagging.tags.name.
            references:
            - system.object-tagging.tags.name
