id: firewall.dnstranslation
version: 7.6.7
source_object: fortios_firewall_dnstranslation
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_firewall_dnstranslation.py
root_type: list
attributes:
  id:
    type: integer
    raw_type: integer
    required: true
    version_ranges:
    - - v6.0.0
      - ''
    description: ID. see <a href='#notes'>Notes</a>.
  src:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: IPv4 address or subnet on the internal network to compare with the resolved address in DNS query replies.
      If the resolved address matches, the resolved address is substituted with dst.
  dst:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: IPv4 address or subnet on the external network to substitute for the resolved address in DNS query replies.
      Can be single IP address or subnet on the external network, but number of addresses must equal number of mapped IP addresses
      in src.
  netmask:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: If src and dst are subnets rather than single IP addresses, enter the netmask for both src and dst.
