id: firewall.sniffer
version: 7.6.7
source_object: fortios_firewall_sniffer
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_firewall_sniffer.py
root_type: list
attributes:
  id:
    type: integer
    raw_type: integer
    required: true
    version_ranges:
    - - v6.0.0
      - ''
    description: Sniffer ID (0 - 9999). see <a href='#notes'>Notes</a>.
  uuid:
    type: string
    raw_type: string
    version_ranges:
    - - v7.4.2
      - ''
    description: Universally Unique Identifier (UUID; automatically assigned but can be manually reset).
  status:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable the active status of the sniffer.
  logtraffic:
    type: enum
    raw_type: string
    choices:
    - all
    - utm
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Either log all sessions, only sessions that have a security profile applied, or disable all logging for this
      policy.
  ipv6:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - v7.0.12
    - - v7.2.1
      - ''
    description: Enable/disable sniffing IPv6 packets.
  non_ip:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - v7.0.12
    - - v7.2.1
      - ''
    description: Enable/disable sniffing non-IP packets.
  interface:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Interface name that traffic sniffing will take place on. Source system.interface.name.
    references:
    - system.interface.name
  host:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - v7.0.12
    - - v7.2.1
      - ''
    description: 'Hosts to filter for in sniffer traffic (Format examples: 1.1.1.1, 2.2.2.0/24, 3.3.3.3/255.255.255.0, 4.4.4.0-4.4.4.240).'
  port:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - v7.0.12
    - - v7.2.1
      - ''
    description: 'Ports to sniff (Format examples: 10, :20, 30:40, 50-, 100-200).'
  protocol:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - v7.0.12
    - - v7.2.1
      - ''
    description: Integer value for the protocol type as defined by IANA (0 - 255).
  vlan:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - v7.0.12
    - - v7.2.1
      - ''
    description: List of VLANs to sniff.
  application_list_status:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable application control profile.
  application_list:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Name of an existing application list. Source application.list.name.
    references:
    - application.list.name
  ips_sensor_status:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable IPS sensor.
  ips_sensor:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Name of an existing IPS sensor. Source ips.sensor.name.
    references:
    - ips.sensor.name
  dsri:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable DSRI.
  av_profile_status:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable antivirus profile.
  av_profile:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Name of an existing antivirus profile. Source antivirus.profile.name.
    references:
    - antivirus.profile.name
  webfilter_profile_status:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable web filter profile.
  webfilter_profile:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Name of an existing web filter profile. Source webfilter.profile.name.
    references:
    - webfilter.profile.name
  emailfilter_profile_status:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.2.0
      - ''
    description: Enable/disable emailfilter.
  emailfilter_profile:
    type: string
    raw_type: string
    version_ranges:
    - - v6.2.0
      - ''
    description: Name of an existing email filter profile. Source emailfilter.profile.name.
    references:
    - emailfilter.profile.name
  dlp_profile_status:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.2.0
      - ''
    description: Enable/disable DLP profile.
  dlp_profile:
    type: string
    raw_type: string
    version_ranges:
    - - v7.2.0
      - ''
    description: Name of an existing DLP profile. Source dlp.profile.name.
    references:
    - dlp.profile.name
  ip_threatfeed_status:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.0.0
      - ''
    description: Enable/disable IP threat feed.
  ip_threatfeed:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v7.0.0
      - ''
    description: Name of an existing IP threat feed.
    children:
      name:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v7.0.0
          - ''
        description: Threat feed name. Source system.external-resource.name.
        references:
        - system.external-resource.name
  file_filter_profile_status:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.0.0
      - ''
    description: Enable/disable file filter.
  file_filter_profile:
    type: string
    raw_type: string
    version_ranges:
    - - v7.0.0
      - ''
    description: Name of an existing file-filter profile. Source file-filter.profile.name.
    references:
    - file-filter.profile.name
  ips_dos_status:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable IPS DoS anomaly detection.
  anomaly:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: Configuration method to edit Denial of Service (DoS) anomaly settings.
    children:
      name:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: Anomaly name.
      status:
        type: enum
        raw_type: string
        choices:
        - disable
        - enable
        version_ranges:
        - - v6.0.0
          - ''
        description: Enable/disable this anomaly.
      log:
        type: enum
        raw_type: string
        choices:
        - enable
        - disable
        version_ranges:
        - - v6.0.0
          - ''
        description: Enable/disable anomaly logging.
      action:
        type: enum
        raw_type: string
        choices:
        - pass
        - block
        - proxy
        version_ranges:
        - - v6.0.0
          - ''
        description: Action taken when the threshold is reached.
      quarantine:
        type: enum
        raw_type: string
        choices:
        - none
        - attacker
        version_ranges:
        - - v6.0.0
          - ''
        description: Quarantine method.
      quarantine_expiry:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Duration of quarantine. (Format
      quarantine_log:
        type: enum
        raw_type: string
        choices:
        - disable
        - enable
        version_ranges:
        - - v6.0.0
          - ''
        description: Enable/disable quarantine logging.
      threshold:
        type: integer
        raw_type: integer
        version_ranges:
        - - v6.0.0
          - ''
        description: Anomaly threshold. Number of detected instances (packets per second or concurrent session number) that
          triggers the anomaly action.
