id: firewall.shaper.traffic-shaper
version: 7.6.7
source_object: fortios_firewall_shaper_traffic_shaper
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_firewall_shaper_traffic_shaper.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v6.0.0
      - ''
    description: Traffic shaper name.
  guaranteed_bandwidth:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Amount of bandwidth guaranteed for this shaper (0 - 100000000). Units depend on the bandwidth-unit setting.
  maximum_bandwidth:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Upper bandwidth limit enforced by this shaper (0 - 100000000). 0 means no limit. Units depend on the bandwidth-unit
      setting.
  bandwidth_unit:
    type: enum
    raw_type: string
    choices:
    - kbps
    - mbps
    - gbps
    version_ranges:
    - - v6.0.0
      - ''
    description: Unit of measurement for guaranteed and maximum bandwidth for this shaper (Kbps, Mbps or Gbps).
  priority:
    type: enum
    raw_type: string
    choices:
    - low
    - medium
    - high
    version_ranges:
    - - v6.0.0
      - ''
    description: Higher priority traffic is more likely to be forwarded without delays and without compromising the guaranteed
      bandwidth.
  per_policy:
    type: enum
    raw_type: string
    choices:
    - disable
    - enable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable applying a separate shaper for each policy. For example, if enabled the guaranteed bandwidth
      is applied separately for each policy.
  diffserv:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable changing the DiffServ setting applied to traffic accepted by this shaper.
  diffservcode:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: DiffServ setting to be applied to traffic accepted by this shaper.
  dscp_marking_method:
    type: enum
    raw_type: string
    choices:
    - multi-stage
    - static
    version_ranges:
    - - v6.2.0
      - ''
    description: Select DSCP marking method.
  exceed_bandwidth:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.2.0
      - ''
    description: Exceed bandwidth used for DSCP/VLAN CoS multi-stage marking. Units depend on the bandwidth-unit setting.
  exceed_dscp:
    type: string
    raw_type: string
    version_ranges:
    - - v6.2.0
      - ''
    description: DSCP mark for traffic in guaranteed-bandwidth and exceed-bandwidth.
  maximum_dscp:
    type: string
    raw_type: string
    version_ranges:
    - - v6.2.0
      - ''
    description: DSCP mark for traffic in exceed-bandwidth and maximum-bandwidth.
  cos_marking:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.4.0
      - ''
    description: Enable/disable VLAN CoS marking.
  cos_marking_method:
    type: enum
    raw_type: string
    choices:
    - multi-stage
    - static
    version_ranges:
    - - v7.4.0
      - ''
    description: Select VLAN CoS marking method.
  cos:
    type: string
    raw_type: string
    version_ranges:
    - - v7.4.0
      - ''
    description: VLAN CoS mark.
  exceed_cos:
    type: string
    raw_type: string
    version_ranges:
    - - v7.4.0
      - ''
    description: VLAN CoS mark for traffic in [guaranteed-bandwidth, exceed-bandwidth].
  maximum_cos:
    type: string
    raw_type: string
    version_ranges:
    - - v7.4.0
      - ''
    description: VLAN CoS mark for traffic in [exceed-bandwidth, maximum-bandwidth].
  overhead:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.2.0
      - ''
    description: Per-packet size overhead used in rate computations.
  exceed_class_id:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.2.0
      - ''
    description: Class ID for traffic in guaranteed-bandwidth and maximum-bandwidth. Source firewall.traffic-class.class-id.
    references:
    - firewall.traffic-class.class-id
