id: firewall.auth-portal
version: 7.6.7
source_object: fortios_firewall_auth_portal
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_firewall_auth_portal.py
root_type: object
attributes:
  groups:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: Firewall user groups permitted to authenticate through this portal. Separate group names with spaces.
    children:
      name:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: Group name. Source user.group.name.
        references:
        - user.group.name
  portal_addr:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Address (or FQDN) of the authentication portal.
  portal_addr6:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: IPv6 address (or FQDN) of authentication portal.
  identity_based_route:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Name of the identity-based route that applies to this portal. Source firewall.identity-based-route.name.
    references:
    - firewall.identity-based-route.name
  proxy_auth:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.2.4
      - ''
    description: Enable/disable authentication by proxy daemon .
