id: firewall.on-demand-sniffer
version: 7.6.7
source_object: fortios_firewall_on_demand_sniffer
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_firewall_on_demand_sniffer.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v7.4.4
      - ''
    description: On-demand packet sniffer name.
  interface:
    type: string
    raw_type: string
    version_ranges:
    - - v7.4.4
      - ''
    description: Interface name that on-demand packet sniffer will take place. Source system.interface.name.
    references:
    - system.interface.name
  max_packet_count:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.4.4
      - ''
    description: Maximum number of packets to capture per on-demand packet sniffer.
  hosts:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v7.4.4
      - ''
    description: IPv4 or IPv6 hosts to filter in this traffic sniffer.
    children:
      host:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v7.4.4
          - ''
        description: IPv4 or IPv6 host.
  ports:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v7.4.4
      - ''
    description: Ports to filter for in this traffic sniffer.
    children:
      port:
        type: integer
        raw_type: integer
        required: true
        version_ranges:
        - - v7.4.4
          - ''
        description: Port to filter in this traffic sniffer. see <a href='#notes'>Notes</a>.
  protocols:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v7.4.4
      - ''
    description: Protocols to filter in this traffic sniffer.
    children:
      protocol:
        type: integer
        raw_type: integer
        required: true
        version_ranges:
        - - v7.4.4
          - ''
        description: Integer value for the protocol type as defined by IANA (0 - 255). see <a href='#notes'>Notes</a>.
  non_ip_packet:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.4.4
      - ''
    description: Include non-IP packets.
  advanced_filter:
    type: string
    raw_type: string
    version_ranges:
    - - v7.4.4
      - ''
    description: Advanced freeform filter that will be used over existing filter settings if set. Can only be used by super
      admin.
