id: firewall.access-proxy-ssh-client-cert
version: 7.6.7
source_object: fortios_firewall_access_proxy_ssh_client_cert
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_firewall_access_proxy_ssh_client_cert.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v7.0.1
      - ''
    description: SSH client certificate name.
  source_address:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.0.1
      - ''
    description: Enable/disable appending source-address certificate critical option. This option ensure certificate only
      accepted from FortiGate source address.
  permit_x11_forwarding:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.0.1
      - ''
    description: Enable/disable appending permit-x11-forwarding certificate extension.
  permit_agent_forwarding:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.0.1
      - ''
    description: Enable/disable appending permit-agent-forwarding certificate extension.
  permit_port_forwarding:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.0.1
      - ''
    description: Enable/disable appending permit-port-forwarding certificate extension.
  permit_pty:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.0.1
      - ''
    description: Enable/disable appending permit-pty certificate extension.
  permit_user_rc:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.0.1
      - ''
    description: Enable/disable appending permit-user-rc certificate extension.
  cert_extension:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v7.0.1
      - ''
    description: Configure certificate extension for user certificate.
    children:
      name:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v7.0.1
          - ''
        description: Name of certificate extension.
      critical:
        type: enum
        raw_type: string
        choices:
        - 'no'
        - 'yes'
        version_ranges:
        - - v7.0.1
          - ''
        description: Critical option.
      type:
        type: enum
        raw_type: string
        choices:
        - fixed
        - user
        version_ranges:
        - - v7.0.1
          - ''
        description: Type of certificate extension.
      data:
        type: string
        raw_type: string
        version_ranges:
        - - v7.0.1
          - ''
        description: Data of certificate extension.
  auth_ca:
    type: string
    raw_type: string
    version_ranges:
    - - v7.0.1
      - ''
    description: Name of the SSH server public key authentication CA. Source firewall.ssh.local-ca.name.
    references:
    - firewall.ssh.local-ca.name
