id: firewall.proxy-address
version: 7.6.7
source_object: fortios_firewall_proxy_address
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_firewall_proxy_address.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v6.0.0
      - ''
    description: Address name.
  uuid:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Universally Unique Identifier (UUID; automatically assigned but can be manually reset).
  type:
    type: enum
    raw_type: string
    choices:
    - host-regex
    - url
    - category
    - method
    - ua
    - header
    - src-advanced
    - dst-advanced
    - saas
    version_ranges:
    - - v6.0.0
      - ''
    description: Proxy address type.
  host:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Address object for the host. Source firewall.address.name firewall.addrgrp.name firewall.proxy-address.name
      firewall.vipgrp.name firewall.vip.name.
    references:
    - firewall.address.name
    - firewall.addrgrp.name
    - firewall.proxy-address.name
    - firewall.vip.name
    - firewall.vipgrp.name
  host_regex:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Host name as a regular expression.
  path:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: URL path as a regular expression.
  query:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Match the query part of the URL as a regular expression.
  referrer:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable use of referrer field in the HTTP header to match the address.
  category:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: FortiGuard category ID.
    children:
      id:
        type: integer
        raw_type: integer
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: FortiGuard category ID. see <a href='#notes'>Notes</a>.
  method:
    type: enum
    raw_type: list
    choices:
    - get
    - post
    - put
    - head
    - connect
    - trace
    - options
    - delete
    - update
    - patch
    - other
    multiple_values: true
    elements: str
    version_ranges:
    - - v6.0.0
      - ''
    description: HTTP request methods to be used.
  ua:
    type: enum
    raw_type: list
    choices:
    - chrome
    - ms
    - firefox
    - safari
    - ie
    - edge
    - other
    multiple_values: true
    elements: str
    version_ranges:
    - - v6.0.0
      - ''
    description: Names of browsers to be used as user agent.
  ua_min_ver:
    type: string
    raw_type: string
    version_ranges:
    - - v7.2.4
      - ''
    description: Minimum version of the user agent specified in dotted notation. For example, use 90.0.1 with the ua field
      set to "chrome" to require Google Chrome"s minimum version must be 90.0.1.
  ua_max_ver:
    type: string
    raw_type: string
    version_ranges:
    - - v7.2.4
      - ''
    description: Maximum version of the user agent specified in dotted notation. For example, use 120 with the ua field set
      to "chrome" to require Google Chrome"s maximum version must be 120.
  header_name:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Name of HTTP header.
  header:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: HTTP header value as a regular expression.
  case_sensitivity:
    type: enum
    raw_type: string
    choices:
    - disable
    - enable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable to make the pattern case sensitive.
  header_group:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: HTTP header group.
    children:
      id:
        type: integer
        raw_type: integer
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: ID. see <a href='#notes'>Notes</a>.
      header_name:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: HTTP header.
      header:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: HTTP header regular expression.
      case_sensitivity:
        type: enum
        raw_type: string
        choices:
        - disable
        - enable
        version_ranges:
        - - v6.0.0
          - ''
        description: Case sensitivity in pattern.
  color:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Integer value to determine the color of the icon in the GUI (1 - 32).
  tagging:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: Config object tagging.
    children:
      name:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: Tagging entry name.
      category:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Tag category. Source system.object-tagging.category.
        references:
        - system.object-tagging.category
      tags:
        type: list
        raw_type: list
        elements: dict
        version_ranges:
        - - v6.0.0
          - ''
        description: Tags.
        children:
          name:
            type: string
            raw_type: string
            required: true
            version_ranges:
            - - v6.0.0
              - ''
            description: Tag name. Source system.object-tagging.tags.name.
            references:
            - system.object-tagging.tags.name
  comment:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Optional comments.
  application:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v7.2.1
      - ''
    description: SaaS application.
    children:
      name:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v7.2.1
          - ''
        description: SaaS application name.
