id: firewall.schedule.group
version: 7.6.7
source_object: fortios_firewall_schedule_group
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_firewall_schedule_group.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v6.0.0
      - ''
    description: Schedule group name.
  member:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: Schedules added to the schedule group.
    children:
      name:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: Schedule name. Source firewall.schedule.onetime.name firewall.schedule.recurring.name.
        references:
        - firewall.schedule.onetime.name
        - firewall.schedule.recurring.name
  uuid:
    type: string
    raw_type: string
    version_ranges:
    - - v7.6.0
      - ''
    description: Universally Unique Identifier (UUID; automatically assigned but can be manually reset).
  fabric_object:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.4.4
      - ''
    description: Security Fabric global object setting.
  color:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Color of icon on the GUI.
