id: gtp.rat-timeout-profile
version: 7.6.7
source_object: fortios_gtp_rat_timeout_profile
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_gtp_rat_timeout_profile.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v7.0.1
      - v7.0.8
    - - v7.2.0
      - v7.2.4
    - - v7.4.3
      - v7.6.7
    description: RAT timeout profile name.
  utran_timeout:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.0.1
      - v7.0.8
    - - v7.2.0
      - v7.2.4
    - - v7.4.3
      - v7.6.7
    description: Established utran timeout in seconds .
  geran_timeout:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.0.1
      - v7.0.8
    - - v7.2.0
      - v7.2.4
    - - v7.4.3
      - v7.6.7
    description: Established geran timeout in seconds .
  wlan_timeout:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.0.1
      - v7.0.8
    - - v7.2.0
      - v7.2.4
    - - v7.4.3
      - v7.6.7
    description: Established wlan timeout in seconds .
  gan_timeout:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.0.1
      - v7.0.8
    - - v7.2.0
      - v7.2.4
    - - v7.4.3
      - v7.6.7
    description: Established gan timeout in seconds .
  hspa_timeout:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.0.1
      - v7.0.8
    - - v7.2.0
      - v7.2.4
    - - v7.4.3
      - v7.6.7
    description: Established hspa timeout in seconds .
  eutran_timeout:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.0.1
      - v7.0.8
    - - v7.2.0
      - v7.2.4
    - - v7.4.3
      - v7.6.7
    description: Established eutran timeout in seconds .
  virtual_timeout:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.0.1
      - v7.0.8
    - - v7.2.0
      - v7.2.4
    - - v7.4.3
      - v7.6.7
    description: Established virtual timeout in seconds .
  nbiot_timeout:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.0.1
      - v7.0.8
    - - v7.2.0
      - v7.2.4
    - - v7.4.3
      - v7.6.7
    description: Established nbiot timeout in seconds .
  ltem_timeout:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.0.1
      - v7.0.8
    - - v7.2.0
      - v7.2.4
    - - v7.4.3
      - v7.6.7
    description: Established ltem timeout in seconds .
  nr_timeout:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.0.1
      - v7.0.8
    - - v7.2.0
      - v7.2.4
    - - v7.4.3
      - v7.6.7
    description: Established nr timeout in seconds .
