id: gtp.ie-allow-list
version: 7.6.7
source_object: fortios_gtp_ie_allow_list
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_gtp_ie_allow_list.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v7.0.0
      - v7.0.8
    - - v7.2.0
      - v7.2.4
    - - v7.4.3
      - v7.6.7
    description: IE allow list name.
  entries:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v7.0.0
      - v7.0.8
    - - v7.2.0
      - v7.2.4
    - - v7.4.3
      - v7.6.7
    description: Entries of allow list for unknown or out-of-state IEs.
    children:
      id:
        type: integer
        raw_type: integer
        required: true
        version_ranges:
        - - v7.0.0
          - v7.0.8
        - - v7.2.0
          - v7.2.4
        - - v7.4.3
          - v7.6.7
        description: Entry ID. see <a href='#notes'>Notes</a>.
      ie:
        type: integer
        raw_type: integer
        version_ranges:
        - - v7.0.0
          - v7.0.8
        - - v7.2.0
          - v7.2.4
        - - v7.4.3
          - v7.6.7
        description: IE ID (1 - 255).
      fos_message:
        type: integer
        raw_type: integer
        version_ranges:
        - - v7.0.0
          - v7.0.8
        - - v7.2.0
          - v7.2.4
        - - v7.4.3
          - v7.6.7
        description: Message ID (1 - 255).
