id: icap.profile
version: 7.6.7
source_object: fortios_icap_profile
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_icap_profile.py
root_type: list
attributes:
  replacemsg_group:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Replacement message group. Source system.replacemsg-group.name.
    references:
    - system.replacemsg-group.name
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v6.0.0
      - ''
    description: ICAP profile name.
  comment:
    type: string
    raw_type: string
    version_ranges:
    - - v7.2.4
      - ''
    description: Comment.
  request:
    type: enum
    raw_type: string
    choices:
    - disable
    - enable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable whether an HTTP request is passed to an ICAP server.
  response:
    type: enum
    raw_type: string
    choices:
    - disable
    - enable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable whether an HTTP response is passed to an ICAP server.
  file_transfer:
    type: enum
    raw_type: list
    choices:
    - ssh
    - ftp
    multiple_values: true
    elements: str
    version_ranges:
    - - v7.2.0
      - ''
    description: Configure the file transfer protocols to pass transferred files to an ICAP server as REQMOD.
  streaming_content_bypass:
    type: enum
    raw_type: string
    choices:
    - disable
    - enable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable bypassing of ICAP server for streaming content.
  ocr_only:
    type: enum
    raw_type: string
    choices:
    - disable
    - enable
    version_ranges:
    - - v7.6.1
      - ''
    description: Enable/disable this FortiGate unit to submit only OCR interested content to the ICAP server.
  preview:
    type: enum
    raw_type: string
    choices:
    - disable
    - enable
    version_ranges:
    - - v6.2.0
      - ''
    description: Enable/disable preview of data to ICAP server.
  preview_data_length:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.2.0
      - ''
    description: Preview data length to be sent to ICAP server.
  request_server:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: ICAP server to use for an HTTP request. Source icap.server.name icap.server-group.name.
    references:
    - icap.server-group.name
    - icap.server.name
  response_server:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: ICAP server to use for an HTTP response. Source icap.server.name icap.server-group.name.
    references:
    - icap.server-group.name
    - icap.server.name
  file_transfer_server:
    type: string
    raw_type: string
    version_ranges:
    - - v7.2.0
      - ''
    description: ICAP server to use for a file transfer. Source icap.server.name icap.server-group.name.
    references:
    - icap.server-group.name
    - icap.server.name
  request_failure:
    type: enum
    raw_type: string
    choices:
    - error
    - bypass
    version_ranges:
    - - v6.0.0
      - ''
    description: Action to take if the ICAP server cannot be contacted when processing an HTTP request.
  response_failure:
    type: enum
    raw_type: string
    choices:
    - error
    - bypass
    version_ranges:
    - - v6.0.0
      - ''
    description: Action to take if the ICAP server cannot be contacted when processing an HTTP response.
  file_transfer_failure:
    type: enum
    raw_type: string
    choices:
    - error
    - bypass
    version_ranges:
    - - v7.2.0
      - ''
    description: Action to take if the ICAP server cannot be contacted when processing a file transfer.
  request_path:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Path component of the ICAP URI that identifies the HTTP request processing service.
  response_path:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Path component of the ICAP URI that identifies the HTTP response processing service.
  file_transfer_path:
    type: string
    raw_type: string
    version_ranges:
    - - v7.2.0
      - ''
    description: Path component of the ICAP URI that identifies the file transfer processing service.
  methods:
    type: enum
    raw_type: list
    choices:
    - delete
    - get
    - head
    - options
    - post
    - put
    - trace
    - connect
    - other
    multiple_values: true
    elements: str
    version_ranges:
    - - v6.0.0
      - ''
    description: The allowed HTTP methods that will be sent to ICAP server for further processing.
  response_req_hdr:
    type: enum
    raw_type: string
    choices:
    - disable
    - enable
    version_ranges:
    - - v6.2.0
      - ''
    description: Enable/disable addition of req-hdr for ICAP response modification (respmod) processing.
  respmod_default_action:
    type: enum
    raw_type: string
    choices:
    - forward
    - bypass
    version_ranges:
    - - v6.4.0
      - ''
    description: Default action to ICAP response modification (respmod) processing.
  icap_block_log:
    type: enum
    raw_type: string
    choices:
    - disable
    - enable
    version_ranges:
    - - v7.0.1
      - ''
    description: Enable/disable UTM log when infection found .
  chunk_encap:
    type: enum
    raw_type: string
    choices:
    - disable
    - enable
    version_ranges:
    - - v7.0.2
      - ''
    description: Enable/disable chunked encapsulation .
  extension_feature:
    type: enum
    raw_type: list
    choices:
    - scan-progress
    multiple_values: true
    elements: str
    version_ranges:
    - - v7.0.2
      - ''
    description: Enable/disable ICAP extension features.
  scan_progress_interval:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.0.2
      - ''
    description: Scan progress interval value.
  timeout:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.2.0
      - ''
    description: Time (in seconds) that ICAP client waits for the response from ICAP server.
  icap_headers:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.2.0
      - ''
    description: Configure ICAP forwarded request headers.
    children:
      id:
        type: integer
        raw_type: integer
        required: true
        version_ranges:
        - - v6.2.0
          - ''
        description: HTTP forwarded header ID. see <a href='#notes'>Notes</a>.
      name:
        type: string
        raw_type: string
        version_ranges:
        - - v6.2.0
          - ''
        description: HTTP forwarded header name.
      content:
        type: string
        raw_type: string
        version_ranges:
        - - v6.2.0
          - ''
        description: HTTP header content.
      base64_encoding:
        type: enum
        raw_type: string
        choices:
        - disable
        - enable
        version_ranges:
        - - v6.2.0
          - ''
        description: Enable/disable use of base64 encoding of HTTP content.
  respmod_forward_rules:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.4.0
      - ''
    description: ICAP response mode forward rules.
    children:
      name:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v6.4.0
          - ''
        description: Address name.
      host:
        type: string
        raw_type: string
        version_ranges:
        - - v6.4.0
          - ''
        description: Address object for the host. Source firewall.address.name firewall.addrgrp.name firewall.proxy-address.name.
        references:
        - firewall.address.name
        - firewall.addrgrp.name
        - firewall.proxy-address.name
      header_group:
        type: list
        raw_type: list
        elements: dict
        version_ranges:
        - - v6.4.0
          - ''
        description: HTTP header group.
        children:
          id:
            type: integer
            raw_type: integer
            required: true
            version_ranges:
            - - v6.4.0
              - ''
            description: ID. see <a href='#notes'>Notes</a>.
          header_name:
            type: string
            raw_type: string
            version_ranges:
            - - v6.4.0
              - ''
            description: HTTP header.
          header:
            type: string
            raw_type: string
            version_ranges:
            - - v6.4.0
              - ''
            description: HTTP header regular expression.
          case_sensitivity:
            type: enum
            raw_type: string
            choices:
            - disable
            - enable
            version_ranges:
            - - v6.4.0
              - ''
            description: Enable/disable case sensitivity when matching header.
      action:
        type: enum
        raw_type: string
        choices:
        - forward
        - bypass
        version_ranges:
        - - v6.4.0
          - ''
        description: Action to be taken for ICAP server.
      http_resp_status_code:
        type: list
        raw_type: list
        elements: dict
        version_ranges:
        - - v6.4.0
          - ''
        description: HTTP response status code.
        children:
          code:
            type: integer
            raw_type: integer
            required: true
            version_ranges:
            - - v6.4.0
              - ''
            description: HTTP response status code. see <a href='#notes'>Notes</a>.
  size_limit_204:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.2.0
      - ''
    description: 204 response size limit to be saved by ICAP client in megabytes (1 - 10).
  response_204:
    type: enum
    raw_type: string
    choices:
    - disable
    - enable
    version_ranges:
    - - v7.2.0
      - ''
    description: Enable/disable allowance of 204 response from ICAP server.
