id: log.custom-field
version: 7.6.7
source_object: fortios_log_custom_field
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_log_custom_field.py
root_type: list
attributes:
  id:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v6.0.0
      - ''
    description: Field ID string.
  name:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: 'Field name (max: 15 characters).'
  value:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: 'Field value (max: 15 characters).'
