id: log.fortianalyzer.override-filter
version: 7.6.7
source_object: fortios_log_fortianalyzer_override_filter
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_log_fortianalyzer_override_filter.py
root_type: object
attributes:
  severity:
    type: enum
    raw_type: string
    choices:
    - emergency
    - alert
    - critical
    - error
    - warning
    - notification
    - information
    - debug
    version_ranges:
    - - v6.0.0
      - ''
    description: Lowest severity level to log.
  forward_traffic:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable forward traffic logging.
  local_traffic:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable local in or out traffic logging.
  multicast_traffic:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable multicast traffic logging.
  sniffer_traffic:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable sniffer traffic logging.
  ztna_traffic:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.0.4
      - ''
    description: Enable/disable ztna traffic logging.
  http_transaction:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.6.0
      - ''
    description: Enable/disable log HTTP transaction messages.
  anomaly:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable anomaly logging.
  voip:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable VoIP logging.
  dlp_archive:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable DLP archive logging.
  forti_switch:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.4.2
      - ''
    description: Enable/disable Forti-Switch logging.
  free_style:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v7.0.0
      - ''
    description: Free style filters.
    children:
      id:
        type: integer
        raw_type: integer
        required: true
        version_ranges:
        - - v7.0.0
          - ''
        description: Entry ID. see <a href='#notes'>Notes</a>.
      category:
        type: enum
        raw_type: string
        choices:
        - traffic
        - event
        - virus
        - webfilter
        - attack
        - spam
        - anomaly
        - voip
        - dlp
        - app-ctrl
        - waf
        - dns
        - ssh
        - ssl
        - file-filter
        - icap
        - virtual-patch
        - debug
        - gtp
        version_ranges:
        - - v7.0.0
          - ''
        description: Log category.
      filter:
        type: string
        raw_type: string
        version_ranges:
        - - v7.0.0
          - ''
        description: Free style filter string.
      filter_type:
        type: enum
        raw_type: string
        choices:
        - include
        - exclude
        version_ranges:
        - - v7.0.0
          - ''
        description: Include/exclude logs that match the filter.
  gtp:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - v7.6.7
    description: Enable/disable GTP messages logging.
