id: log.memory.global-setting
version: 7.6.7
source_object: fortios_log_memory_global_setting
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_log_memory_global_setting.py
root_type: object
attributes:
  max_size:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Maximum amount of memory that can be used for memory logging in bytes.
  full_first_warning_threshold:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Log full first warning threshold as a percent (1 - 98).
  full_second_warning_threshold:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Log full second warning threshold as a percent (2 - 99).
  full_final_warning_threshold:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Log full final warning threshold as a percent (3 - 100).
