id: report.setting
version: 7.6.7
source_object: fortios_report_setting
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_report_setting.py
root_type: object
attributes:
  pdf_report:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable PDF report.
  fortiview:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable historical FortiView.
  report_source:
    type: enum
    raw_type: list
    choices:
    - forward-traffic
    - sniffer-traffic
    - local-deny-traffic
    multiple_values: true
    elements: str
    version_ranges:
    - - v6.0.0
      - ''
    description: Report log source.
  web_browsing_threshold:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Web browsing time calculation threshold (3 - 15 min).
  top_n:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Number of items to populate (1000 - 20000).
