id: router.extcommunity-list
version: 7.6.7
source_object: fortios_router_extcommunity_list
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_router_extcommunity_list.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v7.2.4
      - ''
    description: Extended community list name.
  type:
    type: enum
    raw_type: string
    choices:
    - standard
    - expanded
    version_ranges:
    - - v7.2.4
      - ''
    description: Extended community list type (standard or expanded).
  rule:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v7.2.4
      - ''
    description: Extended community list rule.
    children:
      id:
        type: integer
        raw_type: integer
        required: true
        version_ranges:
        - - v7.2.4
          - ''
        description: ID. see <a href='#notes'>Notes</a>.
      action:
        type: enum
        raw_type: string
        choices:
        - deny
        - permit
        version_ranges:
        - - v7.2.4
          - ''
        description: Permit or deny route-based operations, based on the route"s EXTENDED COMMUNITY attribute.
      regexp:
        type: string
        raw_type: string
        version_ranges:
        - - v7.2.4
          - ''
        description: Ordered list of EXTENDED COMMUNITY attributes as a regular expression.
      type:
        type: enum
        raw_type: string
        choices:
        - rt
        - soo
        version_ranges:
        - - v7.2.4
          - ''
        description: Type of extended community.
      match:
        type: string
        raw_type: string
        version_ranges:
        - - v7.2.4
          - ''
        description: Extended community specifications for matching a reserved extended community.
