id: router.isis
version: 7.6.7
source_object: fortios_router_isis
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_router_isis.py
root_type: object
attributes:
  is_type:
    type: enum
    raw_type: string
    choices:
    - level-1-2
    - level-1
    - level-2-only
    version_ranges:
    - - v6.0.0
      - ''
    description: IS type.
  adv_passive_only:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable IS-IS advertisement of passive interfaces only.
  adv_passive_only6:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable IPv6 IS-IS advertisement of passive interfaces only.
  auth_mode_l1:
    type: enum
    raw_type: string
    choices:
    - password
    - md5
    version_ranges:
    - - v6.0.0
      - ''
    description: Level 1 authentication mode.
  auth_mode_l2:
    type: enum
    raw_type: string
    choices:
    - password
    - md5
    version_ranges:
    - - v6.0.0
      - ''
    description: Level 2 authentication mode.
  auth_password_l1:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Authentication password for level 1 PDUs.
  auth_password_l2:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Authentication password for level 2 PDUs.
  auth_keychain_l1:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Authentication key-chain for level 1 PDUs. Source router.key-chain.name.
    references:
    - router.key-chain.name
  auth_keychain_l2:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Authentication key-chain for level 2 PDUs. Source router.key-chain.name.
    references:
    - router.key-chain.name
  auth_sendonly_l1:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable level 1 authentication send-only.
  auth_sendonly_l2:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable level 2 authentication send-only.
  ignore_lsp_errors:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable ignoring of LSP errors with bad checksums.
  lsp_gen_interval_l1:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Minimum interval for level 1 LSP regenerating.
  lsp_gen_interval_l2:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Minimum interval for level 2 LSP regenerating.
  lsp_refresh_interval:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: LSP refresh time in seconds.
  max_lsp_lifetime:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Maximum LSP lifetime in seconds.
  spf_interval_exp_l1:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Level 1 SPF calculation delay.
  spf_interval_exp_l2:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Level 2 SPF calculation delay.
  dynamic_hostname:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable dynamic hostname.
  adjacency_check:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable adjacency check.
  adjacency_check6:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable IPv6 adjacency check.
  overload_bit:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable signal other routers not to use us in SPF.
  overload_bit_suppress:
    type: enum
    raw_type: list
    choices:
    - external
    - interlevel
    multiple_values: true
    elements: str
    version_ranges:
    - - v6.0.0
      - ''
    description: Suppress overload-bit for the specific prefixes.
  overload_bit_on_startup:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Overload-bit only temporarily after reboot.
  default_originate:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable distribution of default route information.
  default_originate6:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable distribution of default IPv6 route information.
  metric_style:
    type: enum
    raw_type: string
    choices:
    - narrow
    - wide
    - transition
    - narrow-transition
    - narrow-transition-l1
    - narrow-transition-l2
    - wide-l1
    - wide-l2
    - wide-transition
    - wide-transition-l1
    - wide-transition-l2
    - transition-l1
    - transition-l2
    version_ranges:
    - - v6.0.0
      - ''
    description: Use old-style (ISO 10589) or new-style packet formats.
  redistribute_l1:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable redistribution of level 1 routes into level 2.
  redistribute_l1_list:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Access-list for route redistribution from l1 to l2. Source router.access-list.name.
    references:
    - router.access-list.name
  redistribute_l2:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable redistribution of level 2 routes into level 1.
  redistribute_l2_list:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Access-list for route redistribution from l2 to l1. Source router.access-list.name.
    references:
    - router.access-list.name
  redistribute6_l1:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable redistribution of level 1 IPv6 routes into level 2.
  redistribute6_l1_list:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Access-list for IPv6 route redistribution from l1 to l2. Source router.access-list6.name.
    references:
    - router.access-list6.name
  redistribute6_l2:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable redistribution of level 2 IPv6 routes into level 1.
  redistribute6_l2_list:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Access-list for IPv6 route redistribution from l2 to l1. Source router.access-list6.name.
    references:
    - router.access-list6.name
  isis_net:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: IS-IS net configuration.
    children:
      id:
        type: integer
        raw_type: integer
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: ISIS network ID. see <a href='#notes'>Notes</a>.
      net:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: IS-IS networks (format = xx.xxxx.  .xxxx.xx.).
  isis_interface:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: IS-IS interface configuration.
    children:
      name:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: IS-IS interface name. Source system.interface.name.
        references:
        - system.interface.name
      status:
        type: enum
        raw_type: string
        choices:
        - enable
        - disable
        version_ranges:
        - - v6.0.0
          - ''
        description: Enable/disable interface for IS-IS.
      status6:
        type: enum
        raw_type: string
        choices:
        - enable
        - disable
        version_ranges:
        - - v6.0.0
          - ''
        description: Enable/disable IPv6 interface for IS-IS.
      network_type:
        type: enum
        raw_type: string
        choices:
        - broadcast
        - point-to-point
        - loopback
        version_ranges:
        - - v6.0.0
          - ''
        description: IS-IS interface"s network type.
      circuit_type:
        type: enum
        raw_type: string
        choices:
        - level-1-2
        - level-1
        - level-2
        version_ranges:
        - - v6.0.0
          - ''
        description: IS-IS interface"s circuit type.
      csnp_interval_l1:
        type: integer
        raw_type: integer
        version_ranges:
        - - v6.0.0
          - ''
        description: Level 1 CSNP interval.
      csnp_interval_l2:
        type: integer
        raw_type: integer
        version_ranges:
        - - v6.0.0
          - ''
        description: Level 2 CSNP interval.
      hello_interval_l1:
        type: integer
        raw_type: integer
        version_ranges:
        - - v6.0.0
          - ''
        description: Level 1 hello interval.
      hello_interval_l2:
        type: integer
        raw_type: integer
        version_ranges:
        - - v6.0.0
          - ''
        description: Level 2 hello interval.
      hello_multiplier_l1:
        type: integer
        raw_type: integer
        version_ranges:
        - - v6.0.0
          - ''
        description: Level 1 multiplier for Hello holding time.
      hello_multiplier_l2:
        type: integer
        raw_type: integer
        version_ranges:
        - - v6.0.0
          - ''
        description: Level 2 multiplier for Hello holding time.
      hello_padding:
        type: enum
        raw_type: string
        choices:
        - enable
        - disable
        version_ranges:
        - - v6.0.0
          - ''
        description: Enable/disable padding to IS-IS hello packets.
      lsp_interval:
        type: integer
        raw_type: integer
        version_ranges:
        - - v6.0.0
          - ''
        description: LSP transmission interval (milliseconds).
      lsp_retransmit_interval:
        type: integer
        raw_type: integer
        version_ranges:
        - - v6.0.0
          - ''
        description: LSP retransmission interval (sec).
      metric_l1:
        type: integer
        raw_type: integer
        version_ranges:
        - - v6.0.0
          - ''
        description: Level 1 metric for interface.
      metric_l2:
        type: integer
        raw_type: integer
        version_ranges:
        - - v6.0.0
          - ''
        description: Level 2 metric for interface.
      wide_metric_l1:
        type: integer
        raw_type: integer
        version_ranges:
        - - v6.0.0
          - ''
        description: Level 1 wide metric for interface.
      wide_metric_l2:
        type: integer
        raw_type: integer
        version_ranges:
        - - v6.0.0
          - ''
        description: Level 2 wide metric for interface.
      auth_password_l1:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Authentication password for level 1 PDUs.
      auth_password_l2:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Authentication password for level 2 PDUs.
      auth_keychain_l1:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Authentication key-chain for level 1 PDUs. Source router.key-chain.name.
        references:
        - router.key-chain.name
      auth_keychain_l2:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Authentication key-chain for level 2 PDUs. Source router.key-chain.name.
        references:
        - router.key-chain.name
      auth_send_only_l1:
        type: enum
        raw_type: string
        choices:
        - enable
        - disable
        version_ranges:
        - - v6.0.0
          - ''
        description: Enable/disable authentication send-only for level 1 PDUs.
      auth_send_only_l2:
        type: enum
        raw_type: string
        choices:
        - enable
        - disable
        version_ranges:
        - - v6.0.0
          - ''
        description: Enable/disable authentication send-only for level 2 PDUs.
      auth_mode_l1:
        type: enum
        raw_type: string
        choices:
        - md5
        - password
        version_ranges:
        - - v6.0.0
          - ''
        description: Level 1 authentication mode.
      auth_mode_l2:
        type: enum
        raw_type: string
        choices:
        - md5
        - password
        version_ranges:
        - - v6.0.0
          - ''
        description: Level 2 authentication mode.
      priority_l1:
        type: integer
        raw_type: integer
        version_ranges:
        - - v6.0.0
          - ''
        description: Level 1 priority.
      priority_l2:
        type: integer
        raw_type: integer
        version_ranges:
        - - v6.0.0
          - ''
        description: Level 2 priority.
      mesh_group:
        type: enum
        raw_type: string
        choices:
        - enable
        - disable
        version_ranges:
        - - v6.0.0
          - ''
        description: Enable/disable IS-IS mesh group.
      mesh_group_id:
        type: integer
        raw_type: integer
        version_ranges:
        - - v6.0.0
          - ''
        description: 'Mesh group ID <0-4294967295>, 0: mesh-group blocked.'
  summary_address:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: IS-IS summary addresses.
    children:
      id:
        type: integer
        raw_type: integer
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: Summary address entry ID. see <a href='#notes'>Notes</a>.
      prefix:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Prefix.
      level:
        type: enum
        raw_type: string
        choices:
        - level-1-2
        - level-1
        - level-2
        version_ranges:
        - - v6.0.0
          - ''
        description: Level.
  summary_address6:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: IS-IS IPv6 summary addresses.
    children:
      id:
        type: integer
        raw_type: integer
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: Prefix entry ID. see <a href='#notes'>Notes</a>.
      prefix6:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: IPv6 prefix.
      level:
        type: enum
        raw_type: string
        choices:
        - level-1-2
        - level-1
        - level-2
        version_ranges:
        - - v6.0.0
          - ''
        description: Level.
