id: router.multicast-flow
version: 7.6.7
source_object: fortios_router_multicast_flow
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_router_multicast_flow.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v6.0.0
      - ''
    description: Name.
  comments:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Comment.
  flows:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: Multicast-flow entries.
    children:
      id:
        type: integer
        raw_type: integer
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: Flow ID. see <a href='#notes'>Notes</a>.
      group_addr:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Multicast group IP address.
      source_addr:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Multicast source IP address.
