id: router.access-list6
version: 7.6.7
source_object: fortios_router_access_list6
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_router_access_list6.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v6.0.0
      - ''
    description: Name.
  comments:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Comment.
  rule:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: Rule.
    children:
      id:
        type: integer
        raw_type: integer
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: Rule ID. see <a href='#notes'>Notes</a>.
      action:
        type: enum
        raw_type: string
        choices:
        - permit
        - deny
        version_ranges:
        - - v6.0.0
          - ''
        description: Permit or deny this IP address and netmask prefix.
      prefix6:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: IPv6 prefix to define regular filter criteria, such as "any" or subnets.
      exact_match:
        type: enum
        raw_type: string
        choices:
        - enable
        - disable
        version_ranges:
        - - v6.0.0
          - ''
        description: Enable/disable exact prefix match.
