id: router.aspath-list
version: 7.6.7
source_object: fortios_router_aspath_list
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_router_aspath_list.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v6.0.0
      - ''
    description: AS path list name.
  rule:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: AS path list rule.
    children:
      id:
        type: integer
        raw_type: integer
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: ID. see <a href='#notes'>Notes</a>.
      action:
        type: enum
        raw_type: string
        choices:
        - deny
        - permit
        version_ranges:
        - - v6.0.0
          - ''
        description: Permit or deny route-based operations, based on the route"s AS_PATH attribute.
      regexp:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Regular-expression to match the Border Gateway Protocol (BGP) AS paths.
