id: router.route-map
version: 7.6.7
source_object: fortios_router_route_map
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_router_route_map.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v6.0.0
      - ''
    description: Name.
  comments:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Optional comments.
  rule:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: Rule.
    children:
      id:
        type: integer
        raw_type: integer
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: Rule ID. see <a href='#notes'>Notes</a>.
      action:
        type: enum
        raw_type: string
        choices:
        - permit
        - deny
        version_ranges:
        - - v6.0.0
          - ''
        description: Action.
      match_as_path:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Match BGP AS path list. Source router.aspath-list.name.
        references:
        - router.aspath-list.name
      match_community:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Match BGP community list. Source router.community-list.name.
        references:
        - router.community-list.name
      match_extcommunity:
        type: string
        raw_type: string
        version_ranges:
        - - v7.2.4
          - ''
        description: Match BGP extended community list. Source router.extcommunity-list.name.
        references:
        - router.extcommunity-list.name
      match_community_exact:
        type: enum
        raw_type: string
        choices:
        - enable
        - disable
        version_ranges:
        - - v6.0.0
          - ''
        description: Enable/disable exact matching of communities.
      match_extcommunity_exact:
        type: enum
        raw_type: string
        choices:
        - enable
        - disable
        version_ranges:
        - - v7.2.4
          - ''
        description: Enable/disable exact matching of extended communities.
      match_origin:
        type: enum
        raw_type: string
        choices:
        - none
        - egp
        - igp
        - incomplete
        version_ranges:
        - - v6.0.0
          - ''
        description: Match BGP origin code.
      match_interface:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Match interface configuration. Source system.interface.name.
        references:
        - system.interface.name
      match_ip_address:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Match IP address permitted by access-list or prefix-list. Source router.access-list.name router.prefix-list.name.
        references:
        - router.access-list.name
        - router.prefix-list.name
      match_ip6_address:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Match IPv6 address permitted by access-list6 or prefix-list6. Source router.access-list6.name router.prefix-list6.name.
        references:
        - router.access-list6.name
        - router.prefix-list6.name
      match_ip_nexthop:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Match next hop IP address passed by access-list or prefix-list. Source router.access-list.name router.prefix-list.name.
        references:
        - router.access-list.name
        - router.prefix-list.name
      match_ip6_nexthop:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Match next hop IPv6 address passed by access-list6 or prefix-list6. Source router.access-list6.name router.prefix-list6.name.
        references:
        - router.access-list6.name
        - router.prefix-list6.name
      match_metric:
        type: integer
        raw_type: integer
        version_ranges:
        - - v6.0.0
          - ''
        description: Match metric for redistribute routes.
      match_route_type:
        type: enum
        raw_type: string
        choices:
        - external-type1
        - external-type2
        - none
        version_ranges:
        - - v6.0.0
          - ''
        description: Match route type.
      match_tag:
        type: integer
        raw_type: integer
        version_ranges:
        - - v6.0.0
          - ''
        description: Match tag.
      match_vrf:
        type: integer
        raw_type: integer
        version_ranges:
        - - v6.4.0
          - ''
        description: Match VRF ID.
      match_suppress:
        type: enum
        raw_type: string
        choices:
        - enable
        - disable
        version_ranges:
        - - v7.6.5
          - ''
        description: Enable/disable matching of suppressed original neighbor.
      set_aggregator_as:
        type: integer
        raw_type: integer
        version_ranges:
        - - v6.0.0
          - ''
        description: BGP aggregator AS.
      set_aggregator_ip:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: BGP aggregator IP.
      set_aspath_action:
        type: enum
        raw_type: string
        choices:
        - prepend
        - replace
        version_ranges:
        - - v6.0.0
          - ''
        description: Specify preferred action of set-aspath.
      set_aspath:
        type: list
        raw_type: list
        elements: dict
        version_ranges:
        - - v6.0.0
          - ''
        description: Prepend BGP AS path attribute.
        children:
          as:
            type: string
            raw_type: string
            required: true
            version_ranges:
            - - v6.0.0
              - ''
            description: AS number (0 - 4294967295).
      set_atomic_aggregate:
        type: enum
        raw_type: string
        choices:
        - enable
        - disable
        version_ranges:
        - - v6.0.0
          - ''
        description: Enable/disable BGP atomic aggregate attribute.
      set_community_delete:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Delete communities matching community list. Source router.community-list.name.
        references:
        - router.community-list.name
      set_community:
        type: list
        raw_type: list
        elements: dict
        version_ranges:
        - - v6.0.0
          - ''
        description: BGP community attribute.
        children:
          community:
            type: string
            raw_type: string
            required: true
            version_ranges:
            - - v6.0.0
              - ''
            description: 'Attribute: AA|AA:NN|internet|local-AS|no-advertise|no-export|gshut.(exact match required for well
              known communities).'
      set_community_additive:
        type: enum
        raw_type: string
        choices:
        - enable
        - disable
        version_ranges:
        - - v6.0.0
          - ''
        description: Enable/disable adding set-community to existing community.
      set_dampening_reachability_half_life:
        type: integer
        raw_type: integer
        version_ranges:
        - - v6.0.0
          - ''
        description: Reachability half-life time for the penalty (1 - 45 min, 0 = unset).
      set_dampening_reuse:
        type: integer
        raw_type: integer
        version_ranges:
        - - v6.0.0
          - ''
        description: Value to start reusing a route (1 - 20000, 0 = unset).
      set_dampening_suppress:
        type: integer
        raw_type: integer
        version_ranges:
        - - v6.0.0
          - ''
        description: Value to start suppressing a route (1 - 20000, 0 = unset).
      set_dampening_max_suppress:
        type: integer
        raw_type: integer
        version_ranges:
        - - v6.0.0
          - ''
        description: Maximum duration to suppress a route (1 - 255 min, 0 = unset).
      set_dampening_unreachability_half_life:
        type: integer
        raw_type: integer
        version_ranges:
        - - v6.0.0
          - ''
        description: Unreachability Half-life time for the penalty (1 - 45 min, 0 = unset).
      set_extcommunity_rt:
        type: list
        raw_type: list
        elements: dict
        version_ranges:
        - - v6.0.0
          - ''
        description: Route Target extended community.
        children:
          community:
            type: string
            raw_type: string
            required: true
            version_ranges:
            - - v6.0.0
              - ''
            description: AA:NN.
      set_extcommunity_soo:
        type: list
        raw_type: list
        elements: dict
        version_ranges:
        - - v6.0.0
          - ''
        description: Site-of-Origin extended community.
        children:
          community:
            type: string
            raw_type: string
            required: true
            version_ranges:
            - - v6.0.0
              - ''
            description: Community (format = AA:NN).
      set_ip_nexthop:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: IP address of next hop.
      set_ip_prefsrc:
        type: string
        raw_type: string
        version_ranges:
        - - v7.4.0
          - ''
        description: IP address of preferred source.
      set_vpnv4_nexthop:
        type: string
        raw_type: string
        version_ranges:
        - - v7.4.1
          - ''
        description: IP address of VPNv4 next hop.
      set_ip6_nexthop:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: IPv6 global address of next hop.
      set_ip6_nexthop_local:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: IPv6 local address of next hop.
      set_vpnv6_nexthop:
        type: string
        raw_type: string
        version_ranges:
        - - v7.4.2
          - ''
        description: IPv6 global address of VPNv6 next hop.
      set_vpnv6_nexthop_local:
        type: string
        raw_type: string
        version_ranges:
        - - v7.4.2
          - ''
        description: IPv6 link-local address of VPNv6 next hop.
      set_local_preference:
        type: integer
        raw_type: integer
        version_ranges:
        - - v6.0.0
          - ''
        description: BGP local preference path attribute.
      set_metric:
        type: integer
        raw_type: integer
        version_ranges:
        - - v6.0.0
          - ''
        description: Metric value.
      set_metric_type:
        type: enum
        raw_type: string
        choices:
        - external-type1
        - external-type2
        - none
        version_ranges:
        - - v6.0.0
          - ''
        description: Metric type.
      set_originator_id:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: BGP originator ID attribute.
      set_origin:
        type: enum
        raw_type: string
        choices:
        - none
        - egp
        - igp
        - incomplete
        version_ranges:
        - - v6.0.0
          - ''
        description: BGP origin code.
      set_tag:
        type: integer
        raw_type: integer
        version_ranges:
        - - v6.0.0
          - ''
        description: Tag value.
      set_weight:
        type: integer
        raw_type: integer
        version_ranges:
        - - v6.0.0
          - ''
        description: BGP weight for routing table.
      set_route_tag:
        type: integer
        raw_type: integer
        version_ranges:
        - - v6.0.0
          - ''
        description: Route tag for routing table.
      set_priority:
        type: integer
        raw_type: integer
        version_ranges:
        - - v7.2.0
          - ''
        description: Priority for routing table.
