id: router.ripng
version: 7.6.7
source_object: fortios_router_ripng
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_router_ripng.py
root_type: object
attributes:
  default_information_originate:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable generation of default route.
  default_metric:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Default metric.
  max_out_metric:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Maximum metric allowed to output(0 means "not set").
  distance:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: Distance.
    children:
      id:
        type: integer
        raw_type: integer
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: Distance ID. see <a href='#notes'>Notes</a>.
      distance:
        type: integer
        raw_type: integer
        version_ranges:
        - - v6.0.0
          - ''
        description: Distance (1 - 255).
      prefix6:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Distance prefix6.
      access_list6:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Access list for route destination. Source router.access-list6.name.
        references:
        - router.access-list6.name
  distribute_list:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: Distribute list.
    children:
      id:
        type: integer
        raw_type: integer
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: Distribute list ID. see <a href='#notes'>Notes</a>.
      status:
        type: enum
        raw_type: string
        choices:
        - enable
        - disable
        version_ranges:
        - - v6.0.0
          - ''
        description: Status.
      direction:
        type: enum
        raw_type: string
        choices:
        - in
        - out
        version_ranges:
        - - v6.0.0
          - ''
        description: Distribute list direction.
      listname:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Distribute access/prefix list name. Source router.access-list6.name router.prefix-list6.name.
        references:
        - router.access-list6.name
        - router.prefix-list6.name
      interface:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Distribute list interface name. Source system.interface.name.
        references:
        - system.interface.name
  neighbor:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: Neighbor.
    children:
      id:
        type: integer
        raw_type: integer
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: Neighbor entry ID. see <a href='#notes'>Notes</a>.
      ip6:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: IPv6 link-local address.
      interface:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Interface name. Source system.interface.name.
        references:
        - system.interface.name
  network:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: Network.
    children:
      id:
        type: integer
        raw_type: integer
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: Network entry ID. see <a href='#notes'>Notes</a>.
      prefix:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Network IPv6 link-local prefix.
  aggregate_address:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: Aggregate address.
    children:
      id:
        type: integer
        raw_type: integer
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: Aggregate address entry ID. see <a href='#notes'>Notes</a>.
      prefix6:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Aggregate address prefix.
  offset_list:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: Offset list.
    children:
      id:
        type: integer
        raw_type: integer
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: Offset-list ID. see <a href='#notes'>Notes</a>.
      status:
        type: enum
        raw_type: string
        choices:
        - enable
        - disable
        version_ranges:
        - - v6.0.0
          - ''
        description: Status.
      direction:
        type: enum
        raw_type: string
        choices:
        - in
        - out
        version_ranges:
        - - v6.0.0
          - ''
        description: Offset list direction.
      access_list6:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: IPv6 access list name. Source router.access-list6.name.
        references:
        - router.access-list6.name
      offset:
        type: integer
        raw_type: integer
        version_ranges:
        - - v6.0.0
          - ''
        description: Offset.
      interface:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Interface name. Source system.interface.name.
        references:
        - system.interface.name
  passive_interface:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: Passive interface configuration.
    children:
      name:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: Passive interface name. Source system.interface.name.
        references:
        - system.interface.name
  update_timer:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Update timer in seconds.
  timeout_timer:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Timeout timer in seconds.
  garbage_timer:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Garbage timer in seconds.
  interface:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: RIPng interface configuration.
    children:
      name:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: Interface name. Source system.interface.name.
        references:
        - system.interface.name
      split_horizon_status:
        type: enum
        raw_type: string
        choices:
        - enable
        - disable
        version_ranges:
        - - v6.0.0
          - ''
        description: Enable/disable split horizon.
      split_horizon:
        type: enum
        raw_type: string
        choices:
        - poisoned
        - regular
        version_ranges:
        - - v6.0.0
          - ''
        description: Enable/disable split horizon.
