id: router.rip
version: 7.6.7
source_object: fortios_router_rip
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_router_rip.py
root_type: object
attributes:
  default_information_originate:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable generation of default route.
  default_metric:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Default metric.
  max_out_metric:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Maximum metric allowed to output(0 means "not set").
  distance:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: Distance.
    children:
      id:
        type: integer
        raw_type: integer
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: Distance ID. see <a href='#notes'>Notes</a>.
      prefix:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Distance prefix.
      distance:
        type: integer
        raw_type: integer
        version_ranges:
        - - v6.0.0
          - ''
        description: Distance (1 - 255).
      access_list:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Access list for route destination. Source router.access-list.name.
        references:
        - router.access-list.name
  distribute_list:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: Distribute list.
    children:
      id:
        type: integer
        raw_type: integer
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: Distribute list ID. see <a href='#notes'>Notes</a>.
      status:
        type: enum
        raw_type: string
        choices:
        - enable
        - disable
        version_ranges:
        - - v6.0.0
          - ''
        description: Status.
      direction:
        type: enum
        raw_type: string
        choices:
        - in
        - out
        version_ranges:
        - - v6.0.0
          - ''
        description: Distribute list direction.
      listname:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Distribute access/prefix list name. Source router.access-list.name router.prefix-list.name.
        references:
        - router.access-list.name
        - router.prefix-list.name
      interface:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Distribute list interface name. Source system.interface.name.
        references:
        - system.interface.name
  neighbor:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: Neighbor.
    children:
      id:
        type: integer
        raw_type: integer
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: Neighbor entry ID. see <a href='#notes'>Notes</a>.
      ip:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: IP address.
  network:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: Network.
    children:
      id:
        type: integer
        raw_type: integer
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: Network entry ID. see <a href='#notes'>Notes</a>.
      prefix:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Network prefix.
  offset_list:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: Offset list.
    children:
      id:
        type: integer
        raw_type: integer
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: Offset-list ID. see <a href='#notes'>Notes</a>.
      status:
        type: enum
        raw_type: string
        choices:
        - enable
        - disable
        version_ranges:
        - - v6.0.0
          - ''
        description: Status.
      direction:
        type: enum
        raw_type: string
        choices:
        - in
        - out
        version_ranges:
        - - v6.0.0
          - ''
        description: Offset list direction.
      access_list:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Access list name. Source router.access-list.name.
        references:
        - router.access-list.name
      offset:
        type: integer
        raw_type: integer
        version_ranges:
        - - v6.0.0
          - ''
        description: Offset.
      interface:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Interface name. Source system.interface.name.
        references:
        - system.interface.name
  passive_interface:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: Passive interface configuration.
    children:
      name:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: Passive interface name. Source system.interface.name.
        references:
        - system.interface.name
  update_timer:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Update timer in seconds.
  timeout_timer:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Timeout timer in seconds.
  garbage_timer:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Garbage timer in seconds.
  version:
    type: enum
    raw_type: string
    choices:
    - '1'
    - '2'
    version_ranges:
    - - v6.0.0
      - ''
    description: RIP version.
  interface:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: RIP interface configuration.
    children:
      name:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: Interface name. Source system.interface.name.
        references:
        - system.interface.name
      auth_keychain:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Authentication key-chain name. Source router.key-chain.name.
        references:
        - router.key-chain.name
      auth_mode:
        type: enum
        raw_type: string
        choices:
        - none
        - text
        - md5
        version_ranges:
        - - v6.0.0
          - ''
        description: Authentication mode.
      auth_string:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Authentication string/password.
      receive_version:
        type: enum
        raw_type: list
        choices:
        - '1'
        - '2'
        multiple_values: true
        elements: str
        version_ranges:
        - - v6.0.0
          - ''
        description: Receive version.
      send_version:
        type: enum
        raw_type: list
        choices:
        - '1'
        - '2'
        multiple_values: true
        elements: str
        version_ranges:
        - - v6.0.0
          - ''
        description: Send version.
      send_version2_broadcast:
        type: enum
        raw_type: string
        choices:
        - disable
        - enable
        version_ranges:
        - - v6.0.0
          - ''
        description: Enable/disable broadcast version 1 compatible packets.
      split_horizon_status:
        type: enum
        raw_type: string
        choices:
        - enable
        - disable
        version_ranges:
        - - v6.0.0
          - ''
        description: Enable/disable split horizon.
      split_horizon:
        type: enum
        raw_type: string
        choices:
        - poisoned
        - regular
        version_ranges:
        - - v6.0.0
          - ''
        description: Enable/disable split horizon.
