id: router.community-list
version: 7.6.7
source_object: fortios_router_community_list
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_router_community_list.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v6.0.0
      - ''
    description: Community list name.
  type:
    type: enum
    raw_type: string
    choices:
    - standard
    - expanded
    version_ranges:
    - - v6.0.0
      - ''
    description: Community list type (standard or expanded).
  rule:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: Community list rule.
    children:
      id:
        type: integer
        raw_type: integer
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: ID. see <a href='#notes'>Notes</a>.
      action:
        type: enum
        raw_type: string
        choices:
        - deny
        - permit
        version_ranges:
        - - v6.0.0
          - ''
        description: Permit or deny route-based operations, based on the route"s COMMUNITY attribute.
      regexp:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Ordered list of COMMUNITY attributes as a regular expression.
      match:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Community specifications for matching a reserved community.
