id: switch-controller.auto-config.default
version: 7.6.7
source_object: fortios_switch_controller_auto_config_default
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_switch_controller_auto_config_default.py
root_type: object
attributes:
  fgt_policy:
    type: string
    raw_type: string
    version_ranges:
    - - v6.2.0
      - ''
    description: Default FortiLink auto-config policy. Source switch-controller.auto-config.policy.name.
    references:
    - switch-controller.auto-config.policy.name
  isl_policy:
    type: string
    raw_type: string
    version_ranges:
    - - v6.2.0
      - ''
    description: Default ISL auto-config policy. Source switch-controller.auto-config.policy.name.
    references:
    - switch-controller.auto-config.policy.name
  icl_policy:
    type: string
    raw_type: string
    version_ranges:
    - - v6.2.0
      - ''
    description: Default ICL auto-config policy. Source switch-controller.auto-config.policy.name.
    references:
    - switch-controller.auto-config.policy.name
