id: switch-controller.ip-source-guard-log
version: 7.6.7
source_object: fortios_switch_controller_ip_source_guard_log
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_switch_controller_ip_source_guard_log.py
root_type: object
attributes:
  log_violations:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.6.4
      - ''
    description: Enable/Disable log violations for IP source guard logging.
  violation_timer:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.6.4
      - ''
    description: IP source gurad log violation timer in seconds (0 - 1500).
