id: switch-controller.dynamic-port-policy
version: 7.6.7
source_object: fortios_switch_controller_dynamic_port_policy
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_switch_controller_dynamic_port_policy.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v7.0.0
      - ''
    description: Dynamic port policy name.
  description:
    type: string
    raw_type: string
    version_ranges:
    - - v7.0.0
      - ''
    description: Description for the Dynamic port policy.
  fortilink:
    type: string
    raw_type: string
    version_ranges:
    - - v7.0.0
      - ''
    description: FortiLink interface for which this Dynamic port policy belongs to. Source system.interface.name.
    references:
    - system.interface.name
  policy:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v7.0.0
      - ''
    description: Port policies with matching criteria and actions.
    children:
      name:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v7.0.0
          - ''
        description: Policy name.
      description:
        type: string
        raw_type: string
        version_ranges:
        - - v7.0.0
          - ''
        description: Description for the policy.
      status:
        type: enum
        raw_type: string
        choices:
        - enable
        - disable
        version_ranges:
        - - v7.0.0
          - ''
        description: Enable/disable policy.
      category:
        type: enum
        raw_type: string
        choices:
        - device
        - interface-tag
        version_ranges:
        - - v7.0.0
          - ''
        description: Category of Dynamic port policy.
      match_type:
        type: enum
        raw_type: string
        choices:
        - dynamic
        - override
        version_ranges:
        - - v7.4.4
          - ''
        description: Match and retain the devices based on the type.
      match_period:
        type: integer
        raw_type: integer
        version_ranges:
        - - v7.4.4
          - ''
        description: Duration in hours to retain the matched devices (0 - 3072, 0 = always retain).
      match_remove:
        type: enum
        raw_type: string
        choices:
        - default
        - link-down
        version_ranges:
        - - v7.6.3
          - ''
        description: Options to remove the matched override devices.
      interface_tags:
        type: list
        raw_type: list
        elements: dict
        version_ranges:
        - - v7.0.0
          - ''
        description: Match policy based on the FortiSwitch interface object tags.
        children:
          tag_name:
            type: string
            raw_type: string
            required: true
            version_ranges:
            - - v7.0.0
              - ''
            description: FortiSwitch port tag name. Source switch-controller.switch-interface-tag.name.
            references:
            - switch-controller.switch-interface-tag.name
      mac:
        type: string
        raw_type: string
        version_ranges:
        - - v7.0.0
          - ''
        description: Match policy based on MAC address.
      hw_vendor:
        type: string
        raw_type: string
        version_ranges:
        - - v7.0.4
          - ''
        description: Match policy based on hardware vendor.
      type:
        type: string
        raw_type: string
        version_ranges:
        - - v7.0.0
          - ''
        description: Match policy based on type.
      family:
        type: string
        raw_type: string
        version_ranges:
        - - v7.0.0
          - ''
        description: Match policy based on family.
      host:
        type: string
        raw_type: string
        version_ranges:
        - - v7.0.0
          - ''
        description: Match policy based on host.
      lldp_profile:
        type: string
        raw_type: string
        version_ranges:
        - - v7.0.0
          - ''
        description: LLDP profile to be applied when using this policy. Source switch-controller.lldp-profile.name.
        references:
        - switch-controller.lldp-profile.name
      qos_policy:
        type: string
        raw_type: string
        version_ranges:
        - - v7.0.0
          - ''
        description: QoS policy to be applied when using this policy. Source switch-controller.qos.qos-policy.name.
        references:
        - switch-controller.qos.qos-policy.name
      vlan_policy:
        type: string
        raw_type: string
        version_ranges:
        - - v7.0.0
          - ''
        description: VLAN policy to be applied when using this policy. Source switch-controller.vlan-policy.name.
        references:
        - switch-controller.vlan-policy.name
      bounce_port_link:
        type: enum
        raw_type: string
        choices:
        - disable
        - enable
        version_ranges:
        - - v7.0.0
          - ''
        description: Enable/disable bouncing (administratively bring the link down, up) of a switch port where this policy
          is applied. Helps to clear and reassign VLAN from lldp-profile.
      bounce_port_duration:
        type: integer
        raw_type: integer
        version_ranges:
        - - v7.6.1
          - ''
        description: Bounce duration in seconds of a switch port where this policy is applied.
      poe_reset:
        type: enum
        raw_type: string
        choices:
        - disable
        - enable
        version_ranges:
        - - v7.6.1
          - ''
        description: Enable/disable POE reset of a switch port where this policy is applied.
      set_802_1x:
        type: string
        raw_type: string
        version_ranges:
        - - v7.0.0
          - ''
        description: 802.1x security policy to be applied when using this policy. Source switch-controller.security-policy.802-1X.name
          switch-controller.security-policy.captive-portal.name.
        references:
        - switch-controller.security-policy.802-1X.name
        - switch-controller.security-policy.captive-portal.name
