id: switch-controller.network-monitor-settings
version: 7.6.7
source_object: fortios_switch_controller_network_monitor_settings
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_switch_controller_network_monitor_settings.py
root_type: object
attributes:
  network_monitoring:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable passive gathering of information by FortiSwitch units concerning other network devices.
