id: switch-controller.ptp.interface-policy
version: 7.6.7
source_object: fortios_switch_controller_ptp_interface_policy
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_switch_controller_ptp_interface_policy.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v7.4.1
      - ''
    description: Policy name.
  description:
    type: string
    raw_type: string
    version_ranges:
    - - v7.4.1
      - ''
    description: Description.
  vlan:
    type: string
    raw_type: string
    version_ranges:
    - - v7.4.1
      - ''
    description: PTP VLAN. Source system.interface.name.
    references:
    - system.interface.name
  vlan_pri:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.4.1
      - ''
    description: Configure PTP VLAN priority (0 - 7).
