id: switch-controller.quarantine
version: 7.6.7
source_object: fortios_switch_controller_quarantine
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_switch_controller_quarantine.py
root_type: object
attributes:
  quarantine:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable quarantine.
  targets:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: Quarantine MACs.
    children:
      mac:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: Quarantine MAC.
      description:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Description for the quarantine MAC.
      tag:
        type: list
        raw_type: list
        elements: dict
        version_ranges:
        - - v6.0.0
          - ''
        description: Tags for the quarantine MAC.
        children:
          tags:
            type: string
            raw_type: string
            required: true
            version_ranges:
            - - v6.0.0
              - ''
            description: Tag string. For example, string1 string2 string3.
