id: switch-controller.flow-tracking
version: 7.6.7
source_object: fortios_switch_controller_flow_tracking
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_switch_controller_flow_tracking.py
root_type: object
attributes:
  sample_mode:
    type: enum
    raw_type: string
    choices:
    - local
    - perimeter
    - device-ingress
    version_ranges:
    - - v6.2.0
      - ''
    description: Configure sample mode for the flow tracking.
  sample_rate:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.2.0
      - ''
    description: Configure sample rate for the perimeter and device-ingress sampling(0 - 99999).
  format:
    type: enum
    raw_type: string
    choices:
    - netflow1
    - netflow5
    - netflow9
    - ipfix
    version_ranges:
    - - v6.2.0
      - ''
    description: Configure flow tracking protocol.
  collectors:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v7.2.0
      - ''
    description: Configure collectors for the flow.
    children:
      name:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v7.2.0
          - ''
        description: Collector name.
      ip:
        type: string
        raw_type: string
        version_ranges:
        - - v7.2.0
          - ''
        description: Collector IP address.
      port:
        type: integer
        raw_type: integer
        version_ranges:
        - - v7.2.0
          - ''
        description: Collector port number(0-65535).
      transport:
        type: enum
        raw_type: string
        choices:
        - udp
        - tcp
        - sctp
        version_ranges:
        - - v7.2.0
          - ''
        description: Collector L4 transport protocol for exporting packets.
  level:
    type: enum
    raw_type: string
    choices:
    - vlan
    - ip
    - port
    - proto
    - mac
    version_ranges:
    - - v6.2.0
      - ''
    description: Configure flow tracking level.
  max_export_pkt_size:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.2.0
      - ''
    description: Configure flow max export packet size (512-9216).
  template_export_period:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.2.0
      - ''
    description: Configure template export period (1-60).
  timeout_general:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.2.0
      - ''
    description: Configure flow session general timeout (60-604800).
  timeout_icmp:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.2.0
      - ''
    description: Configure flow session ICMP timeout (60-604800).
  timeout_max:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.2.0
      - ''
    description: Configure flow session max timeout (60-604800).
  timeout_tcp:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.2.0
      - ''
    description: Configure flow session TCP timeout (60-604800).
  timeout_tcp_fin:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.2.0
      - ''
    description: Configure flow session TCP FIN timeout (60-604800).
  timeout_tcp_rst:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.2.0
      - ''
    description: Configure flow session TCP RST timeout (60-604800).
  timeout_udp:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.2.0
      - ''
    description: Configure flow session UDP timeout (60-604800).
  aggregates:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.2.0
      - ''
    description: Configure aggregates in which all traffic sessions matching the IP Address will be grouped into the same
      flow.
    children:
      id:
        type: integer
        raw_type: integer
        required: true
        version_ranges:
        - - v6.2.0
          - ''
        description: Aggregate id. see <a href='#notes'>Notes</a>.
      ip:
        type: string
        raw_type: string
        version_ranges:
        - - v6.2.0
          - ''
        description: IP address to group all matching traffic sessions to a flow.
