id: switch-controller.storm-control-policy
version: 7.6.7
source_object: fortios_switch_controller_storm_control_policy
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_switch_controller_storm_control_policy.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v6.2.0
      - ''
    description: Storm control policy name.
  description:
    type: string
    raw_type: string
    version_ranges:
    - - v6.2.0
      - ''
    description: Description of the storm control policy.
  storm_control_mode:
    type: enum
    raw_type: string
    choices:
    - global
    - override
    - disabled
    version_ranges:
    - - v6.2.0
      - ''
    description: Set Storm control mode.
  rate:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.2.0
      - ''
    description: Threshold rate in packets per second at which storm traffic is controlled in override mode .
  burst_size_level:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.6.4
      - ''
    description: Increase level to handle bursty traffic (0 - 4).
  unknown_unicast:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.2.0
      - ''
    description: Enable/disable storm control to drop/allow unknown unicast traffic in override mode.
  unknown_multicast:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.2.0
      - ''
    description: Enable/disable storm control to drop/allow unknown multicast traffic in override mode.
  broadcast:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.2.0
      - ''
    description: Enable/disable storm control to drop/allow broadcast traffic in override mode.
