id: switch-controller.snmp-sysinfo
version: 7.6.7
source_object: fortios_switch_controller_snmp_sysinfo
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_switch_controller_snmp_sysinfo.py
root_type: object
attributes:
  status:
    type: enum
    raw_type: string
    choices:
    - disable
    - enable
    version_ranges:
    - - v6.2.0
      - ''
    description: Enable/disable SNMP.
  engine_id:
    type: string
    raw_type: string
    version_ranges:
    - - v6.2.0
      - ''
    description: Local SNMP engine ID string (max 24 char).
  description:
    type: string
    raw_type: string
    version_ranges:
    - - v6.2.0
      - ''
    description: System description.
  contact_info:
    type: string
    raw_type: string
    version_ranges:
    - - v6.2.0
      - ''
    description: Contact information.
  location:
    type: string
    raw_type: string
    version_ranges:
    - - v6.2.0
      - ''
    description: System location.
