id: switch-controller.switch-log
version: 7.6.7
source_object: fortios_switch_controller_switch_log
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_switch_controller_switch_log.py
root_type: object
attributes:
  status:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable adding FortiSwitch logs to FortiGate event log.
  severity:
    type: enum
    raw_type: string
    choices:
    - emergency
    - alert
    - critical
    - error
    - warning
    - notification
    - information
    - debug
    version_ranges:
    - - v6.0.0
      - ''
    description: Severity of FortiSwitch logs that are added to the FortiGate event log.
