id: switch-controller.snmp-user
version: 7.6.7
source_object: fortios_switch_controller_snmp_user
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_switch_controller_snmp_user.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v6.2.0
      - ''
    description: SNMP user name.
  queries:
    type: enum
    raw_type: string
    choices:
    - disable
    - enable
    version_ranges:
    - - v6.2.0
      - ''
    description: Enable/disable SNMP queries for this user.
  query_port:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.2.0
      - ''
    description: SNMPv3 query port .
  security_level:
    type: enum
    raw_type: string
    choices:
    - no-auth-no-priv
    - auth-no-priv
    - auth-priv
    version_ranges:
    - - v6.2.0
      - ''
    description: Security level for message authentication and encryption.
  auth_proto:
    type: enum
    raw_type: string
    choices:
    - md5
    - sha1
    - sha224
    - sha256
    - sha384
    - sha512
    version_ranges:
    - - v6.2.0
      - ''
    description: Authentication protocol.
  auth_pwd:
    type: string
    raw_type: string
    version_ranges:
    - - v6.2.0
      - ''
    description: Password for authentication protocol.
  priv_proto:
    type: enum
    raw_type: string
    choices:
    - aes128
    - aes192
    - aes192c
    - aes256
    - aes256c
    - des
    version_ranges:
    - - v6.2.0
      - ''
    description: Privacy (encryption) protocol.
  priv_pwd:
    type: string
    raw_type: string
    version_ranges:
    - - v6.2.0
      - ''
    description: Password for privacy (encryption) protocol.
