id: switch-controller.remote-log
version: 7.6.7
source_object: fortios_switch_controller_remote_log
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_switch_controller_remote_log.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v6.2.0
      - ''
    description: Remote log name.
  status:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.2.0
      - ''
    description: Enable/disable logging by FortiSwitch device to a remote syslog server.
  server:
    type: string
    raw_type: string
    version_ranges:
    - - v6.2.0
      - ''
    description: IPv4 address of the remote syslog server.
  port:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.2.0
      - ''
    description: Remote syslog server listening port.
  severity:
    type: enum
    raw_type: string
    choices:
    - emergency
    - alert
    - critical
    - error
    - warning
    - notification
    - information
    - debug
    version_ranges:
    - - v6.2.0
      - ''
    description: Severity of logs to be transferred to remote log server.
  csv:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.2.0
      - ''
    description: Enable/disable comma-separated value (CSV) strings.
  facility:
    type: enum
    raw_type: string
    choices:
    - kernel
    - user
    - mail
    - daemon
    - auth
    - syslog
    - lpr
    - news
    - uucp
    - cron
    - authpriv
    - ftp
    - ntp
    - audit
    - alert
    - clock
    - local0
    - local1
    - local2
    - local3
    - local4
    - local5
    - local6
    - local7
    version_ranges:
    - - v6.2.0
      - ''
    description: Facility to log to remote syslog server.
