id: switch-controller.security-policy.local-access
version: 7.6.7
source_object: fortios_switch_controller_security_policy_local_access
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_switch_controller_security_policy_local_access.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v6.2.0
      - ''
    description: Policy name.
  mgmt_allowaccess:
    type: enum
    raw_type: list
    choices:
    - https
    - ping
    - ssh
    - snmp
    - http
    - telnet
    - radius-acct
    multiple_values: true
    elements: str
    version_ranges:
    - - v6.2.0
      - ''
    description: Allowed access on the switch management interface.
  internal_allowaccess:
    type: enum
    raw_type: list
    choices:
    - https
    - ping
    - ssh
    - snmp
    - http
    - telnet
    - radius-acct
    multiple_values: true
    elements: str
    version_ranges:
    - - v6.2.0
      - ''
    description: Allowed access on the switch internal interface.
