id: switch-controller.snmp-trap-threshold
version: 7.6.7
source_object: fortios_switch_controller_snmp_trap_threshold
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_switch_controller_snmp_trap_threshold.py
root_type: object
attributes:
  trap_high_cpu_threshold:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.2.0
      - ''
    description: CPU usage when trap is sent.
  trap_low_memory_threshold:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.2.0
      - ''
    description: Memory usage when trap is sent.
  trap_log_full_threshold:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.2.0
      - ''
    description: Log disk usage when trap is sent.
