id: system.snmp.user
version: 7.6.7
source_object: fortios_system_snmp_user
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_system_snmp_user.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v6.0.0
      - ''
    description: SNMP user name.
  status:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable this SNMP user.
  trap_status:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable traps for this SNMP user.
  trap_lport:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: SNMPv3 local trap port .
  trap_rport:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: SNMPv3 trap remote port .
  queries:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable SNMP queries for this user.
  query_port:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: SNMPv3 query port .
  notify_hosts:
    type: list
    raw_type: list
    multiple_values: true
    elements: str
    version_ranges:
    - - v6.0.0
      - ''
    description: SNMP managers to send notifications (traps) to.
  notify_hosts6:
    type: list
    raw_type: list
    multiple_values: true
    elements: str
    version_ranges:
    - - v6.0.0
      - ''
    description: IPv6 SNMP managers to send notifications (traps) to.
  source_ip:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Source IP for SNMP trap.
  source_ipv6:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Source IPv6 for SNMP trap.
  ha_direct:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable direct management of HA cluster members.
  events:
    type: enum
    raw_type: list
    choices:
    - cpu-high
    - mem-low
    - log-full
    - intf-ip
    - vpn-tun-up
    - vpn-tun-down
    - ha-switch
    - ha-hb-failure
    - ips-signature
    - ips-anomaly
    - av-virus
    - av-oversize
    - av-pattern
    - av-fragmented
    - fm-if-change
    - fm-conf-change
    - bgp-established
    - bgp-backward-transition
    - ha-member-up
    - ha-member-down
    - ent-conf-change
    - av-conserve
    - av-bypass
    - av-oversize-passed
    - av-oversize-blocked
    - ips-pkg-update
    - ips-fail-open
    - temperature-high
    - voltage-alert
    - power-supply
    - faz-disconnect
    - faz
    - fan-failure
    - wc-ap-up
    - wc-ap-down
    - fswctl-session-up
    - fswctl-session-down
    - load-balance-real-server-down
    - device-new
    - per-cpu-high
    - dhcp
    - pool-usage
    - ippool
    - interface
    - ospf-nbr-state-change
    - ospf-virtnbr-state-change
    - bfd
    multiple_values: true
    elements: str
    version_ranges:
    - - v6.0.0
      - ''
    description: SNMP notifications (traps) to send.
  mib_view:
    type: string
    raw_type: string
    version_ranges:
    - - v7.2.0
      - ''
    description: SNMP access control MIB view. Source system.snmp.mib-view.name.
    references:
    - system.snmp.mib-view.name
  vdoms:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v7.2.0
      - ''
    description: SNMP access control VDOMs.
    children:
      name:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v7.2.0
          - ''
        description: VDOM name. Source system.vdom.name.
        references:
        - system.vdom.name
  security_level:
    type: enum
    raw_type: string
    choices:
    - no-auth-no-priv
    - auth-no-priv
    - auth-priv
    version_ranges:
    - - v6.0.0
      - ''
    description: Security level for message authentication and encryption.
  auth_proto:
    type: enum
    raw_type: string
    choices:
    - md5
    - sha
    - sha224
    - sha256
    - sha384
    - sha512
    version_ranges:
    - - v6.0.0
      - ''
    description: Authentication protocol.
  auth_pwd:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Password for authentication protocol.
  priv_proto:
    type: enum
    raw_type: string
    choices:
    - aes
    - des
    - aes256
    - aes256cisco
    version_ranges:
    - - v6.0.0
      - ''
    description: Privacy (encryption) protocol.
  priv_pwd:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Password for privacy (encryption) protocol.
  interface_select_method:
    type: enum
    raw_type: string
    choices:
    - auto
    - sdwan
    - specify
    version_ranges:
    - - v7.6.0
      - ''
    description: Specify how to select outgoing interface to reach server.
  interface:
    type: string
    raw_type: string
    version_ranges:
    - - v7.6.0
      - ''
    description: Specify outgoing interface to reach server. Source system.interface.name.
    references:
    - system.interface.name
  vrf_select:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.6.1
      - ''
    description: VRF ID used for connection to server.
