id: system.virtual-wire-pair
version: 7.6.7
source_object: fortios_system_virtual_wire_pair
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_system_virtual_wire_pair.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v6.0.0
      - ''
    description: Virtual-wire-pair name. Must be a unique interface name.
  member:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: Interfaces belong to the virtual-wire-pair.
    children:
      interface_name:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: Interface name. Source system.interface.name.
        references:
        - system.interface.name
  wildcard_vlan:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable wildcard VLAN.
  vlan_filter:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: VLAN ranges to allow
