id: system.dedicated-mgmt
version: 7.6.7
source_object: fortios_system_dedicated_mgmt
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_system_dedicated_mgmt.py
root_type: object
attributes:
  status:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable dedicated management.
  interface:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Dedicated management interface. Source system.interface.name.
    references:
    - system.interface.name
  default_gateway:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Default gateway for dedicated management interface.
  dhcp_server:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable DHCP server on management interface.
  dhcp_netmask:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: DHCP netmask.
  dhcp_start_ip:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: DHCP start IP for dedicated management.
  dhcp_end_ip:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: DHCP end IP for dedicated management.
