id: system.replacemsg-group
version: 7.6.7
source_object: fortios_system_replacemsg_group
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_system_replacemsg_group.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v6.0.0
      - ''
    description: Group name.
  comment:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Comment.
  group_type:
    type: enum
    raw_type: string
    choices:
    - default
    - utm
    - auth
    version_ranges:
    - - v6.0.0
      - ''
    description: Group type.
  mail:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: Replacement message table entries.
    children:
      msg_type:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: Message type.
      buffer:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Message string.
      header:
        type: enum
        raw_type: string
        choices:
        - none
        - http
        - 8bit
        version_ranges:
        - - v6.0.0
          - ''
        description: Header flag.
      format:
        type: enum
        raw_type: string
        choices:
        - none
        - text
        - html
        version_ranges:
        - - v6.0.0
          - ''
        description: Format flag.
  http:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: Replacement message table entries.
    children:
      msg_type:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: Message type.
      buffer:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Message string.
      header:
        type: enum
        raw_type: string
        choices:
        - none
        - http
        - 8bit
        version_ranges:
        - - v6.0.0
          - ''
        description: Header flag.
      format:
        type: enum
        raw_type: string
        choices:
        - none
        - text
        - html
        version_ranges:
        - - v6.0.0
          - ''
        description: Format flag.
  webproxy:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: Replacement message table entries.
    children:
      msg_type:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: Message type.
      buffer:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Message string.
      header:
        type: enum
        raw_type: string
        choices:
        - none
        - http
        - 8bit
        version_ranges:
        - - v6.0.0
          - ''
        description: Header flag.
      format:
        type: enum
        raw_type: string
        choices:
        - none
        - text
        - html
        version_ranges:
        - - v6.0.0
          - ''
        description: Format flag.
  ftp:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: Replacement message table entries.
    children:
      msg_type:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: Message type.
      buffer:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Message string.
      header:
        type: enum
        raw_type: string
        choices:
        - none
        - http
        - 8bit
        version_ranges:
        - - v6.0.0
          - ''
        description: Header flag.
      format:
        type: enum
        raw_type: string
        choices:
        - none
        - text
        - html
        version_ranges:
        - - v6.0.0
          - ''
        description: Format flag.
  fortiguard_wf:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: Replacement message table entries.
    children:
      msg_type:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: Message type.
      buffer:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Message string.
      header:
        type: enum
        raw_type: string
        choices:
        - none
        - http
        - 8bit
        version_ranges:
        - - v6.0.0
          - ''
        description: Header flag.
      format:
        type: enum
        raw_type: string
        choices:
        - none
        - text
        - html
        version_ranges:
        - - v6.0.0
          - ''
        description: Format flag.
  spam:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: Replacement message table entries.
    children:
      msg_type:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: Message type.
      buffer:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Message string.
      header:
        type: enum
        raw_type: string
        choices:
        - none
        - http
        - 8bit
        version_ranges:
        - - v6.0.0
          - ''
        description: Header flag.
      format:
        type: enum
        raw_type: string
        choices:
        - none
        - text
        - html
        version_ranges:
        - - v6.0.0
          - ''
        description: Format flag.
  alertmail:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: Replacement message table entries.
    children:
      msg_type:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: Message type.
      buffer:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Message string.
      header:
        type: enum
        raw_type: string
        choices:
        - none
        - http
        - 8bit
        version_ranges:
        - - v6.0.0
          - ''
        description: Header flag.
      format:
        type: enum
        raw_type: string
        choices:
        - none
        - text
        - html
        version_ranges:
        - - v6.0.0
          - ''
        description: Format flag.
  admin:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: Replacement message table entries.
    children:
      msg_type:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: Message type.
      buffer:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Message string.
      header:
        type: enum
        raw_type: string
        choices:
        - none
        - http
        - 8bit
        version_ranges:
        - - v6.0.0
          - ''
        description: Header flag.
      format:
        type: enum
        raw_type: string
        choices:
        - none
        - text
        - html
        version_ranges:
        - - v6.0.0
          - ''
        description: Format flag.
  auth:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: Replacement message table entries.
    children:
      msg_type:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: Message type.
      buffer:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Message string.
      header:
        type: enum
        raw_type: string
        choices:
        - none
        - http
        - 8bit
        version_ranges:
        - - v6.0.0
          - ''
        description: Header flag.
      format:
        type: enum
        raw_type: string
        choices:
        - none
        - text
        - html
        version_ranges:
        - - v6.0.0
          - ''
        description: Format flag.
  sslvpn:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: Replacement message table entries.
    children:
      msg_type:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: Message type.
      buffer:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Message string.
      header:
        type: enum
        raw_type: string
        choices:
        - none
        - http
        - 8bit
        version_ranges:
        - - v6.0.0
          - ''
        description: Header flag.
      format:
        type: enum
        raw_type: string
        choices:
        - none
        - text
        - html
        version_ranges:
        - - v6.0.0
          - ''
        description: Format flag.
  nac_quar:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: Replacement message table entries.
    children:
      msg_type:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: Message type.
      buffer:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Message string.
      header:
        type: enum
        raw_type: string
        choices:
        - none
        - http
        - 8bit
        version_ranges:
        - - v6.0.0
          - ''
        description: Header flag.
      format:
        type: enum
        raw_type: string
        choices:
        - none
        - text
        - html
        version_ranges:
        - - v6.0.0
          - ''
        description: Format flag.
  traffic_quota:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: Replacement message table entries.
    children:
      msg_type:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: Message type.
      buffer:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Message string.
      header:
        type: enum
        raw_type: string
        choices:
        - none
        - http
        - 8bit
        version_ranges:
        - - v6.0.0
          - ''
        description: Header flag.
      format:
        type: enum
        raw_type: string
        choices:
        - none
        - text
        - html
        version_ranges:
        - - v6.0.0
          - ''
        description: Format flag.
  utm:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: Replacement message table entries.
    children:
      msg_type:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: Message type.
      buffer:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Message string.
      header:
        type: enum
        raw_type: string
        choices:
        - none
        - http
        - 8bit
        version_ranges:
        - - v6.0.0
          - ''
        description: Header flag.
      format:
        type: enum
        raw_type: string
        choices:
        - none
        - text
        - html
        version_ranges:
        - - v6.0.0
          - ''
        description: Format flag.
  custom_message:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: Replacement message table entries.
    children:
      msg_type:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: Message type.
      buffer:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Message string.
      header:
        type: enum
        raw_type: string
        choices:
        - none
        - http
        - 8bit
        version_ranges:
        - - v6.0.0
          - ''
        description: Header flag.
      format:
        type: enum
        raw_type: string
        choices:
        - none
        - text
        - html
        version_ranges:
        - - v6.0.0
          - ''
        description: Format flag.
  icap:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: Replacement message table entries.
    children:
      msg_type:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: Message type.
      buffer:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Message string.
      header:
        type: enum
        raw_type: string
        choices:
        - none
        - http
        - 8bit
        version_ranges:
        - - v6.0.0
          - ''
        description: Header flag.
      format:
        type: enum
        raw_type: string
        choices:
        - none
        - text
        - html
        version_ranges:
        - - v6.0.0
          - ''
        description: Format flag.
  automation:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v7.0.0
      - ''
    description: Replacement message table entries.
    children:
      msg_type:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v7.0.0
          - ''
        description: Message type.
      buffer:
        type: string
        raw_type: string
        version_ranges:
        - - v7.0.0
          - ''
        description: Message string.
      header:
        type: enum
        raw_type: string
        choices:
        - none
        - http
        - 8bit
        version_ranges:
        - - v7.0.0
          - ''
        description: Header flag.
      format:
        type: enum
        raw_type: string
        choices:
        - none
        - text
        - html
        version_ranges:
        - - v7.0.0
          - ''
        description: Format flag.
