id: system.admin
version: 7.6.7
source_object: fortios_system_admin
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_system_admin.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v6.0.0
      - ''
    description: User name.
  vdom:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: Virtual domain(s) that the administrator can access.
    children:
      name:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: Virtual domain name. Source system.vdom.name.
        references:
        - system.vdom.name
  remote_auth:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable authentication using a remote RADIUS, LDAP, or TACACS+ server.
  remote_group:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: User group name used for remote auth.
  wildcard:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable wildcard RADIUS authentication.
  password:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Admin user password.
  peer_auth:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Set to enable peer certificate authentication (for HTTPS admin access).
  peer_group:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Name of peer group defined under config user group which has PKI members. Used for peer certificate authentication
      (for HTTPS admin access).
  trusthost1:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Any IPv4 address or subnet address and netmask from which the administrator can connect to the FortiGate
      unit. Default allows access from any IPv4 address.
  trusthost2:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Any IPv4 address or subnet address and netmask from which the administrator can connect to the FortiGate
      unit. Default allows access from any IPv4 address.
  trusthost3:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Any IPv4 address or subnet address and netmask from which the administrator can connect to the FortiGate
      unit. Default allows access from any IPv4 address.
  trusthost4:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Any IPv4 address or subnet address and netmask from which the administrator can connect to the FortiGate
      unit. Default allows access from any IPv4 address.
  trusthost5:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Any IPv4 address or subnet address and netmask from which the administrator can connect to the FortiGate
      unit. Default allows access from any IPv4 address.
  trusthost6:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Any IPv4 address or subnet address and netmask from which the administrator can connect to the FortiGate
      unit. Default allows access from any IPv4 address.
  trusthost7:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Any IPv4 address or subnet address and netmask from which the administrator can connect to the FortiGate
      unit. Default allows access from any IPv4 address.
  trusthost8:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Any IPv4 address or subnet address and netmask from which the administrator can connect to the FortiGate
      unit. Default allows access from any IPv4 address.
  trusthost9:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Any IPv4 address or subnet address and netmask from which the administrator can connect to the FortiGate
      unit. Default allows access from any IPv4 address.
  trusthost10:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Any IPv4 address or subnet address and netmask from which the administrator can connect to the FortiGate
      unit. Default allows access from any IPv4 address.
  ip6_trusthost1:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Any IPv6 address from which the administrator can connect to the FortiGate unit. Default allows access from
      any IPv6 address.
  ip6_trusthost2:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Any IPv6 address from which the administrator can connect to the FortiGate unit. Default allows access from
      any IPv6 address.
  ip6_trusthost3:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Any IPv6 address from which the administrator can connect to the FortiGate unit. Default allows access from
      any IPv6 address.
  ip6_trusthost4:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Any IPv6 address from which the administrator can connect to the FortiGate unit. Default allows access from
      any IPv6 address.
  ip6_trusthost5:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Any IPv6 address from which the administrator can connect to the FortiGate unit. Default allows access from
      any IPv6 address.
  ip6_trusthost6:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Any IPv6 address from which the administrator can connect to the FortiGate unit. Default allows access from
      any IPv6 address.
  ip6_trusthost7:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Any IPv6 address from which the administrator can connect to the FortiGate unit. Default allows access from
      any IPv6 address.
  ip6_trusthost8:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Any IPv6 address from which the administrator can connect to the FortiGate unit. Default allows access from
      any IPv6 address.
  ip6_trusthost9:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Any IPv6 address from which the administrator can connect to the FortiGate unit. Default allows access from
      any IPv6 address.
  ip6_trusthost10:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Any IPv6 address from which the administrator can connect to the FortiGate unit. Default allows access from
      any IPv6 address.
  accprofile:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Access profile for this administrator. Access profiles control administrator access to FortiGate features.
      Source system.accprofile.name.
    references:
    - system.accprofile.name
  allow_remove_admin_session:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable allow admin session to be removed by privileged admin users.
  comments:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Comment.
  ssh_public_key1:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Public key of an SSH client. The client is authenticated without being asked for credentials. Create the
      public-private key pair in the SSH client application.
  ssh_public_key2:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Public key of an SSH client. The client is authenticated without being asked for credentials. Create the
      public-private key pair in the SSH client application.
  ssh_public_key3:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Public key of an SSH client. The client is authenticated without being asked for credentials. Create the
      public-private key pair in the SSH client application.
  ssh_certificate:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Select the certificate to be used by the FortiGate for authentication with an SSH client. Source certificate.remote.name.
    references:
    - certificate.remote.name
  schedule:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Firewall schedule used to restrict when the administrator can log in. No schedule means no restrictions.
  accprofile_override:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable to use the name of an access profile provided by the remote authentication server to control the FortiGate
      features that this administrator can access.
  vdom_override:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.2.1
      - ''
    description: Enable to use the names of VDOMs provided by the remote authentication server to control the VDOMs that this
      administrator can access.
  password_expire:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Password expire time.
  force_password_change:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable force password change on next login.
  two_factor:
    type: enum
    raw_type: string
    choices:
    - disable
    - fortitoken
    - fortitoken-cloud
    - email
    - sms
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable two-factor authentication.
  two_factor_authentication:
    type: enum
    raw_type: string
    choices:
    - fortitoken
    - email
    - sms
    version_ranges:
    - - v6.2.0
      - v6.2.0
    - - v6.2.5
      - ''
    description: Authentication method by FortiToken Cloud.
  two_factor_notification:
    type: enum
    raw_type: string
    choices:
    - email
    - sms
    version_ranges:
    - - v6.2.0
      - v6.2.0
    - - v6.2.5
      - ''
    description: Notification method for user activation by FortiToken Cloud.
  fortitoken:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: This administrator"s FortiToken serial number.
  email_to:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: This administrator"s email address.
  sms_server:
    type: enum
    raw_type: string
    choices:
    - fortiguard
    - custom
    version_ranges:
    - - v6.0.0
      - ''
    description: Send SMS messages using the FortiGuard SMS server or a custom server.
  sms_custom_server:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Custom SMS server to send SMS messages to. Source system.sms-server.name.
    references:
    - system.sms-server.name
  sms_phone:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Phone number on which the administrator receives SMS messages.
  guest_auth:
    type: enum
    raw_type: string
    choices:
    - disable
    - enable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable guest authentication.
  guest_usergroups:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: Select guest user groups.
    children:
      name:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: Select guest user groups.
  guest_lang:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Guest management portal language. Source system.custom-language.name.
    references:
    - system.custom-language.name
