id: system.automation-action
version: 7.6.7
source_object: fortios_system_automation_action
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_system_automation_action.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v6.0.0
      - ''
    description: Name.
  description:
    type: string
    raw_type: string
    version_ranges:
    - - v7.0.0
      - ''
    description: Description.
  action_type:
    type: enum
    raw_type: string
    choices:
    - email
    - fortiexplorer-notification
    - alert
    - disable-ssid
    - system-actions
    - quarantine
    - quarantine-forticlient
    - quarantine-nsx
    - quarantine-fortinac
    - ban-ip
    - aws-lambda
    - azure-function
    - google-cloud-function
    - alicloud-function
    - webhook
    - cli-script
    - diagnose-script
    - regular-expression
    - slack-notification
    - microsoft-teams-notification
    version_ranges:
    - - v6.0.0
      - ''
    description: Action type.
  system_action:
    type: enum
    raw_type: string
    choices:
    - reboot
    - shutdown
    - backup-config
    version_ranges:
    - - v7.2.1
      - ''
    description: System action type.
  tls_certificate:
    type: string
    raw_type: string
    version_ranges:
    - - v6.2.0
      - ''
    description: Custom TLS certificate for API request. Source certificate.local.name.
    references:
    - certificate.local.name
  forticare_email:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.4.0
      - ''
    description: Enable/disable use of your FortiCare email address as the email-to address.
  email_to:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: Email addresses.
    children:
      name:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: Email address.
  email_from:
    type: string
    raw_type: string
    version_ranges:
    - - v6.2.0
      - ''
    description: Email sender name.
  email_subject:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Email subject.
  minimum_interval:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Limit execution to no more than once in this interval (in seconds).
  aws_api_key:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: AWS API Gateway API key.
  azure_function_authorization:
    type: enum
    raw_type: string
    choices:
    - anonymous
    - function
    - admin
    version_ranges:
    - - v6.2.0
      - ''
    description: Azure function authorization level.
  azure_api_key:
    type: string
    raw_type: string
    version_ranges:
    - - v6.2.0
      - ''
    description: Azure function API key.
  alicloud_function_authorization:
    type: enum
    raw_type: string
    choices:
    - anonymous
    - function
    version_ranges:
    - - v6.2.0
      - ''
    description: AliCloud function authorization type.
  alicloud_access_key_id:
    type: string
    raw_type: string
    version_ranges:
    - - v6.2.0
      - ''
    description: AliCloud AccessKey ID.
  alicloud_access_key_secret:
    type: string
    raw_type: string
    version_ranges:
    - - v6.2.0
      - ''
    description: AliCloud AccessKey secret.
  message_type:
    type: enum
    raw_type: string
    choices:
    - text
    - json
    - form-data
    version_ranges:
    - - v7.0.0
      - ''
    description: Message type.
  replacement_message:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.0.0
      - ''
    description: Enable/disable replacement message.
  replacemsg_group:
    type: string
    raw_type: string
    version_ranges:
    - - v7.0.0
      - ''
    description: Replacement message group. Source system.replacemsg-group.name.
    references:
    - system.replacemsg-group.name
  protocol:
    type: enum
    raw_type: string
    choices:
    - http
    - https
    version_ranges:
    - - v6.0.0
      - ''
    description: Request protocol.
  method:
    type: enum
    raw_type: string
    choices:
    - post
    - put
    - get
    - patch
    - delete
    version_ranges:
    - - v6.0.0
      - ''
    description: Request method (POST, PUT, GET, PATCH or DELETE).
  uri:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Request API URI.
  http_body:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Request body (if necessary). Should be serialized json string.
  port:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Protocol port.
  http_headers:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v7.0.6
      - v7.0.12
    - - v7.2.1
      - ''
    description: Request headers.
    children:
      id:
        type: integer
        raw_type: integer
        required: true
        version_ranges:
        - - v7.0.6
          - v7.0.12
        - - v7.2.1
          - ''
        description: Entry ID. see <a href='#notes'>Notes</a>.
      key:
        type: string
        raw_type: string
        version_ranges:
        - - v7.0.6
          - v7.0.12
        - - v7.2.1
          - ''
        description: Request header key.
      value:
        type: string
        raw_type: string
        version_ranges:
        - - v7.0.6
          - v7.0.12
        - - v7.2.1
          - ''
        description: Request header value.
  form_data:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v7.6.4
      - ''
    description: Form data parts for content type multipart/form-data.
    children:
      id:
        type: integer
        raw_type: integer
        required: true
        version_ranges:
        - - v7.6.4
          - ''
        description: Entry ID. see <a href='#notes'>Notes</a>.
      key:
        type: string
        raw_type: string
        version_ranges:
        - - v7.6.4
          - ''
        description: Key of the part of Multipart/form-data.
      value:
        type: string
        raw_type: string
        version_ranges:
        - - v7.6.4
          - ''
        description: Value of the part of Multipart/form-data.
  verify_host_cert:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.0.0
      - ''
    description: Enable/disable verification of the remote host certificate.
  script:
    type: string
    raw_type: string
    version_ranges:
    - - v6.2.0
      - ''
    description: CLI script.
  output_size:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.2.0
      - ''
    description: Number of megabytes to limit script output to (1 - 1024).
  timeout:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.2.0
      - ''
    description: Maximum running time for this script in seconds (0 = no timeout).
  duration:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.6.1
      - ''
    description: Maximum running time for this script in seconds.
  output_interval:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.6.4
      - ''
    description: Collect the outputs for each output-interval in seconds (0 = no intermediate output).
  file_only:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.6.4
      - ''
    description: Enable/disable the output in files only.
  execute_security_fabric:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.0.2
      - ''
    description: Enable/disable execution of CLI script on all or only one FortiGate unit in the Security Fabric.
  accprofile:
    type: string
    raw_type: string
    version_ranges:
    - - v7.0.0
      - ''
    description: Access profile for CLI script action to access FortiGate features. Source system.accprofile.name.
    references:
    - system.accprofile.name
  regular_expression:
    type: string
    raw_type: string
    version_ranges:
    - - v7.6.1
      - ''
    description: Regular expression string.
  log_debug_print:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.6.3
      - ''
    description: Enable/disable logging debug print output from diagnose action.
  security_tag:
    type: string
    raw_type: string
    version_ranges:
    - - v6.2.0
      - ''
    description: NSX security tag.
  sdn_connector:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.2.0
      - ''
    description: NSX SDN connector names.
    children:
      name:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v6.2.0
          - ''
        description: SDN connector name. Source system.sdn-connector.name.
        references:
        - system.sdn-connector.name
  fos_message:
    type: string
    raw_type: string
    version_ranges:
    - - v6.4.0
      - ''
    description: Message content.
