id: system.mobile-tunnel
version: 7.6.7
source_object: fortios_system_mobile_tunnel
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_system_mobile_tunnel.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v6.0.0
      - ''
    description: Tunnel name.
  status:
    type: enum
    raw_type: string
    choices:
    - disable
    - enable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable this mobile tunnel.
  roaming_interface:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Select the associated interface name from available options. Source system.interface.name.
    references:
    - system.interface.name
  home_agent:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: 'IPv4 address of the NEMO HA (Format: xxx.xxx.xxx.xxx).'
  home_address:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: 'Home IP address (Format: xxx.xxx.xxx.xxx).'
  renew_interval:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Time before lifetime expiration to send NMMO HA re-registration (5 - 60).
  lifetime:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: NMMO HA registration request lifetime (180 - 65535 sec).
  reg_interval:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: NMMO HA registration interval (5 - 300).
  reg_retry:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Maximum number of NMMO HA registration retries (1 to 30).
  n_mhae_spi:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: NEMO authentication SPI .
  n_mhae_key_type:
    type: enum
    raw_type: string
    choices:
    - ascii
    - base64
    version_ranges:
    - - v6.0.0
      - ''
    description: NEMO authentication key type (ASCII or base64).
  n_mhae_key:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: NEMO authentication key.
  hash_algorithm:
    type: enum
    raw_type: string
    choices:
    - hmac-md5
    version_ranges:
    - - v6.0.0
      - ''
    description: Hash Algorithm (Keyed MD5).
  tunnel_mode:
    type: enum
    raw_type: string
    choices:
    - gre
    version_ranges:
    - - v6.0.0
      - ''
    description: NEMO tunnel mode (GRE tunnel).
  network:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: NEMO network configuration.
    children:
      id:
        type: integer
        raw_type: integer
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: Network entry ID. see <a href='#notes'>Notes</a>.
      interface:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Select the associated interface name from available options. Source system.interface.name.
        references:
        - system.interface.name
      prefix:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Class IP and Netmask with correction (Format:xxx.xxx.xxx.xxx xxx.xxx.xxx.xxx or xxx.xxx.xxx.xxx/x).
