id: system.email-server
version: 7.6.7
source_object: fortios_system_email_server
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_system_email_server.py
root_type: object
attributes:
  type:
    type: enum
    raw_type: string
    choices:
    - custom
    version_ranges:
    - - v6.0.0
      - ''
    description: Use FortiGuard Message service or custom email server.
  server:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: SMTP server IP address or hostname.
  port:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: SMTP server port.
  source_ip:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: SMTP server IPv4 source IP.
  source_ip6:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: SMTP server IPv6 source IP.
  authenticate:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable authentication.
  validate_server:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable validation of server certificate.
  username:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: SMTP server user name for authentication.
  password:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: SMTP server user password for authentication.
  security:
    type: enum
    raw_type: string
    choices:
    - none
    - starttls
    - smtps
    version_ranges:
    - - v6.0.0
      - ''
    description: Connection security used by the email server.
  ssl_min_proto_version:
    type: enum
    raw_type: string
    choices:
    - default
    - SSLv3
    - TLSv1
    - TLSv1-1
    - TLSv1-2
    - TLSv1-3
    version_ranges:
    - - v6.0.0
      - ''
    description: Minimum supported protocol version for SSL/TLS connections .
  interface_select_method:
    type: enum
    raw_type: string
    choices:
    - auto
    - sdwan
    - specify
    version_ranges:
    - - v7.0.0
      - ''
    description: Specify how to select outgoing interface to reach server.
  interface:
    type: string
    raw_type: string
    version_ranges:
    - - v7.0.0
      - ''
    description: Specify outgoing interface to reach server. Source system.interface.name.
    references:
    - system.interface.name
  vrf_select:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.6.1
      - ''
    description: VRF ID used for connection to server.
