id: system.speed-test-setting
version: 7.6.7
source_object: fortios_system_speed_test_setting
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_system_speed_test_setting.py
root_type: object
attributes:
  latency_threshold:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.4.1
      - ''
    description: Speed test latency threshold in milliseconds (0 - 2000) for the Auto mode. If the latency exceeds this threshold,
      the speed test will use the UDP protocol; otherwise, it will use the TCP protocol.
  multiple_tcp_stream:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.4.1
      - ''
    description: Number of parallel client streams (1 - 64) for the TCP protocol to run during the speed test.
