id: system.ips-urlfilter-dns
version: 7.6.7
source_object: fortios_system_ips_urlfilter_dns
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_system_ips_urlfilter_dns.py
root_type: list
attributes:
  address:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v6.0.0
      - ''
    description: DNS server IP address.
  status:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable using this DNS server for IPS URL filter DNS queries.
  ipv6_capability:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable this server for IPv6 queries.
