id: system.ips-urlfilter-dns6
version: 7.6.7
source_object: fortios_system_ips_urlfilter_dns6
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_system_ips_urlfilter_dns6.py
root_type: list
attributes:
  address6:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v6.0.0
      - ''
    description: IPv6 address of DNS server.
  status:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable this server for IPv6 DNS queries.
