id: system.autoupdate.schedule
version: 7.6.7
source_object: fortios_system_autoupdate_schedule
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_system_autoupdate_schedule.py
root_type: object
attributes:
  status:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable scheduled updates.
  frequency:
    type: enum
    raw_type: string
    choices:
    - every
    - daily
    - weekly
    - automatic
    version_ranges:
    - - v6.0.0
      - ''
    description: Update frequency.
  time:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Update time.
  day:
    type: enum
    raw_type: string
    choices:
    - Sunday
    - Monday
    - Tuesday
    - Wednesday
    - Thursday
    - Friday
    - Saturday
    version_ranges:
    - - v6.0.0
      - ''
    description: Update day.
