id: system.mac-address-table
version: 7.6.7
source_object: fortios_system_mac_address_table
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_system_mac_address_table.py
root_type: list
attributes:
  mac:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v6.0.0
      - ''
    description: MAC address.
  interface:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Interface name. Source system.interface.name.
    references:
    - system.interface.name
  reply_substitute:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: New MAC for reply traffic.
