id: system.lte-modem
version: 7.6.7
source_object: fortios_system_lte_modem
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_system_lte_modem.py
root_type: object
attributes:
  status:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable USB LTE/WIMAX device.
  extra_init:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Extra initialization string for USB LTE/WIMAX devices.
  pdptype:
    type: enum
    raw_type: string
    choices:
    - IPv4
    version_ranges:
    - - v7.4.1
      - ''
    description: Packet Data Protocol (PDP) context type.
  authtype:
    type: enum
    raw_type: string
    choices:
    - none
    - pap
    - chap
    version_ranges:
    - - v6.0.0
      - ''
    description: Authentication type for PDP-IP packet data calls.
  username:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Authentication username for PDP-IP packet data calls.
  passwd:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Authentication password for PDP-IP packet data calls.
  apn:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Login APN string for PDP-IP packet data calls.
  modem_port:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Modem port index (0 - 20).
