id: system.vdom-netflow
version: 7.6.7
source_object: fortios_system_vdom_netflow
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_system_vdom_netflow.py
root_type: object
attributes:
  vdom_netflow:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable NetFlow per VDOM.
  collectors:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v7.4.2
      - ''
    description: Netflow collectors.
    children:
      id:
        type: integer
        raw_type: integer
        required: true
        version_ranges:
        - - v7.4.2
          - ''
        description: ID. see <a href='#notes'>Notes</a>.
      collector_ip:
        type: string
        raw_type: string
        version_ranges:
        - - v7.4.2
          - ''
        description: Collector IP.
      collector_port:
        type: integer
        raw_type: integer
        version_ranges:
        - - v7.4.2
          - ''
        description: NetFlow collector port number.
      source_ip:
        type: string
        raw_type: string
        version_ranges:
        - - v7.4.2
          - ''
        description: Source IP address for communication with the NetFlow agent.
      source_ip_interface:
        type: string
        raw_type: string
        version_ranges:
        - - v7.6.0
          - ''
        description: Name of the interface used to determine the source IP for exporting packets. Source system.interface.name.
        references:
        - system.interface.name
      interface_select_method:
        type: enum
        raw_type: string
        choices:
        - auto
        - sdwan
        - specify
        version_ranges:
        - - v7.4.2
          - ''
        description: Specify how to select outgoing interface to reach server.
      interface:
        type: string
        raw_type: string
        version_ranges:
        - - v7.4.2
          - ''
        description: Specify outgoing interface to reach server. Source system.interface.name.
        references:
        - system.interface.name
      vrf_select:
        type: integer
        raw_type: integer
        version_ranges:
        - - v7.6.1
          - ''
        description: VRF ID used for connection to server.
