id: system.affinity-packet-redistribution
version: 7.6.7
source_object: fortios_system_affinity_packet_redistribution
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_system_affinity_packet_redistribution.py
root_type: list
attributes:
  id:
    type: integer
    raw_type: integer
    required: true
    version_ranges:
    - - v7.0.0
      - v7.0.12
    - - v7.2.1
      - v7.2.2
    - - v7.4.0
      - v7.6.1
    - - v7.6.5
      - ''
    description: ID of the packet redistribution setting. see <a href='#notes'>Notes</a>.
  interface:
    type: string
    raw_type: string
    version_ranges:
    - - v7.0.0
      - v7.0.12
    - - v7.2.1
      - v7.2.2
    - - v7.4.0
      - v7.6.1
    - - v7.6.5
      - ''
    description: Physical interface name on which to perform packet redistribution. Source system.interface.name.
    references:
    - system.interface.name
  rxqid:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.0.0
      - v7.0.12
    - - v7.2.1
      - v7.2.2
    - - v7.4.0
      - v7.6.1
    - - v7.6.5
      - ''
    description: ID of the receive queue (when the interface has multiple queues) on which to perform packet redistribution
      (255 = all queues).
  round_robin:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.4.0
      - v7.6.1
    - - v7.6.5
      - ''
    description: Enable/disable round-robin redistribution to multiple CPUs.
  affinity_cpumask:
    type: string
    raw_type: string
    version_ranges:
    - - v7.0.0
      - v7.0.12
    - - v7.2.1
      - v7.2.2
    - - v7.4.0
      - v7.6.1
    - - v7.6.5
      - ''
    description: Hexadecimal cpumask, empty value means all CPUs.
