id: system.sdn-vpn
version: 7.6.7
source_object: fortios_system_sdn_vpn
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_system_sdn_vpn.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v7.6.1
      - ''
    description: Public cloud VPN name.
  sdn:
    type: string
    raw_type: string
    version_ranges:
    - - v7.6.1
      - ''
    description: SDN connector name. Source system.sdn-connector.name.
    references:
    - system.sdn-connector.name
  remote_type:
    type: enum
    raw_type: string
    choices:
    - vgw
    - tgw
    version_ranges:
    - - v7.6.1
      - ''
    description: Type of remote device.
  routing_type:
    type: enum
    raw_type: string
    choices:
    - static
    - dynamic
    version_ranges:
    - - v7.6.1
      - ''
    description: Type of routing.
  vgw_id:
    type: string
    raw_type: string
    version_ranges:
    - - v7.6.1
      - ''
    description: Virtual private gateway id.
  tgw_id:
    type: string
    raw_type: string
    version_ranges:
    - - v7.6.1
      - ''
    description: Transit gateway id.
  subnet_id:
    type: string
    raw_type: string
    version_ranges:
    - - v7.6.1
      - ''
    description: AWS subnet id for TGW route propagation.
  bgp_as:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.6.1
      - ''
    description: BGP Router AS number.
  cgw_gateway:
    type: string
    raw_type: string
    version_ranges:
    - - v7.6.1
      - ''
    description: Public IP address of the customer gateway.
  nat_traversal:
    type: enum
    raw_type: string
    choices:
    - disable
    - enable
    version_ranges:
    - - v7.6.1
      - ''
    description: Enable/disable use for NAT traversal. Please enable if your FortiGate device is behind a NAT/PAT device.
  tunnel_interface:
    type: string
    raw_type: string
    version_ranges:
    - - v7.6.1
      - ''
    description: Tunnel interface with public IP. Source system.interface.name.
    references:
    - system.interface.name
  internal_interface:
    type: string
    raw_type: string
    version_ranges:
    - - v7.6.1
      - ''
    description: Internal interface with local subnet. Source system.interface.name.
    references:
    - system.interface.name
  local_cidr:
    type: string
    raw_type: string
    version_ranges:
    - - v7.6.1
      - ''
    description: Local subnet address and subnet mask.
  remote_cidr:
    type: string
    raw_type: string
    version_ranges:
    - - v7.6.1
      - ''
    description: Remote subnet address and subnet mask.
  cgw_name:
    type: string
    raw_type: string
    version_ranges:
    - - v7.6.1
      - ''
    description: AWS customer gateway name to be created.
  psksecret:
    type: string
    raw_type: string
    version_ranges:
    - - v7.6.1
      - ''
    description: Pre-shared secret for PSK authentication. Auto-generated if not specified
