id: system.cloud-service
version: 7.6.7
source_object: fortios_system_cloud_service
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_system_cloud_service.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v7.6.3
      - ''
    description: Name.
  vendor:
    type: enum
    raw_type: string
    choices:
    - unknown
    - google-cloud-kms
    version_ranges:
    - - v7.6.3
      - ''
    description: Cloud service vendor.
  traffic_vdom:
    type: string
    raw_type: string
    version_ranges:
    - - v7.6.3
      - ''
    description: Vdom used to communicate with cloud service. Source system.vdom.name.
    references:
    - system.vdom.name
  gck_service_account:
    type: string
    raw_type: string
    version_ranges:
    - - v7.6.3
      - ''
    description: Service account (e.g. "account-id@sampledomain.com").
  gck_private_key:
    type: string
    raw_type: string
    version_ranges:
    - - v7.6.3
      - ''
    description: Service account private key in PEM format (e.g. "-----BEGIN PRIVATE KEY-----\...").
  gck_keyid:
    type: string
    raw_type: string
    version_ranges:
    - - v7.6.3
      - ''
    description: Key id, also referred as "kid".
  gck_access_token_lifetime:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.6.3
      - ''
    description: Lifetime of automatically generated access tokens in minutes .
