id: system.session-ttl
version: 7.6.7
source_object: fortios_system_session_ttl
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_system_session_ttl.py
root_type: object
attributes:
  default:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Default timeout.
  port:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: Session TTL port.
    children:
      id:
        type: integer
        raw_type: integer
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: Table entry ID. see <a href='#notes'>Notes</a>.
      protocol:
        type: integer
        raw_type: integer
        version_ranges:
        - - v6.0.0
          - ''
        description: Protocol (0 - 255).
      start_port:
        type: integer
        raw_type: integer
        version_ranges:
        - - v6.0.0
          - ''
        description: Start port number.
      end_port:
        type: integer
        raw_type: integer
        version_ranges:
        - - v6.0.0
          - ''
        description: End port number.
      timeout:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Session timeout (TTL).
      refresh_direction:
        type: enum
        raw_type: string
        choices:
        - both
        - outgoing
        - incoming
        version_ranges:
        - - v7.4.1
          - ''
        description: Configure refresh direction.
