id: system.fortidata
version: 7.6.7
source_object: fortios_system_fortidata
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_system_fortidata.py
root_type: object
attributes:
  status:
    type: enum
    raw_type: string
    choices:
    - disable
    - enable
    version_ranges:
    - - v7.6.4
      - ''
    description: Enable/disable FortiData.
  source_ip:
    type: string
    raw_type: string
    version_ranges:
    - - v7.6.4
      - ''
    description: Source IPv4 address used to communicate with FortiData.
  interface_select_method:
    type: enum
    raw_type: string
    choices:
    - auto
    - sdwan
    - specify
    version_ranges:
    - - v7.6.4
      - ''
    description: Specify how to select outgoing interface to reach server.
  interface:
    type: string
    raw_type: string
    version_ranges:
    - - v7.6.4
      - ''
    description: Specify outgoing interface to reach server. Source system.interface.name.
    references:
    - system.interface.name
  vrf_select:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.6.4
      - ''
    description: VRF ID used for connection to server.
