id: system.management-tunnel
version: 7.6.7
source_object: fortios_system_management_tunnel
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_system_management_tunnel.py
root_type: object
attributes:
  status:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable FGFM tunnel.
  allow_config_restore:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable allow config restore.
  allow_push_configuration:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable push configuration.
  allow_push_firmware:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable push firmware.
  allow_collect_statistics:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable collection of run time statistics.
  authorized_manager_only:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable restriction of authorized manager only.
  serial_number:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Serial number.
