id: system.tos-based-priority
version: 7.6.7
source_object: fortios_system_tos_based_priority
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_system_tos_based_priority.py
root_type: list
attributes:
  id:
    type: integer
    raw_type: integer
    required: true
    version_ranges:
    - - v6.0.0
      - ''
    description: Item ID. see <a href='#notes'>Notes</a>.
  tos:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: 'Value of the ToS byte in the IP datagram header (0-15, 8: minimize delay, 4: maximize throughput, 2: maximize
      reliability, 1: minimize monetary cost, and 0: ).'
  priority:
    type: enum
    raw_type: string
    choices:
    - low
    - medium
    - high
    version_ranges:
    - - v6.0.0
      - ''
    description: ToS based priority level to low, medium or high (these priorities match firewall traffic shaping priorities)
      .
