id: system.fortiguard
version: 7.6.7
source_object: fortios_system_fortiguard
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_system_fortiguard.py
root_type: object
attributes:
  fortiguard_anycast:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.2.0
      - ''
    description: Enable/disable use of FortiGuard"s Anycast network.
  fortiguard_anycast_source:
    type: enum
    raw_type: string
    choices:
    - fortinet
    - aws
    - debug
    version_ranges:
    - - v6.2.0
      - ''
    description: Configure which of Fortinet"s servers to provide FortiGuard services in FortiGuard"s anycast network. Default
      is Fortinet.
  protocol:
    type: enum
    raw_type: string
    choices:
    - udp
    - http
    - https
    version_ranges:
    - - v6.0.0
      - v6.0.0
    - - v6.0.11
      - ''
    description: Protocol used to communicate with the FortiGuard servers.
  port:
    type: enum
    raw_type: string
    choices:
    - '8888'
    - '53'
    - '80'
    - '443'
    version_ranges:
    - - v6.0.0
      - ''
    description: Port used to communicate with the FortiGuard servers.
  service_account_id:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - v6.0.11
    - - v6.2.3
      - v6.2.3
    - - v7.0.12
      - v7.0.12
    - - v7.2.1
      - ''
    description: Service account ID.
  load_balance_servers:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Number of servers to alternate between as first FortiGuard option.
  update_server_location:
    type: enum
    raw_type: string
    choices:
    - automatic
    - usa
    - eu
    version_ranges:
    - - v6.0.0
      - ''
    description: Location from which to receive FortiGuard updates.
  sandbox_region:
    type: string
    raw_type: string
    version_ranges:
    - - v6.2.0
      - ''
    description: FortiCloud Sandbox region.
  sandbox_inline_scan:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.2.1
      - ''
    description: Enable/disable FortiCloud Sandbox inline-scan.
  update_ffdb:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.0.0
      - ''
    description: Enable/disable Internet Service Database update.
  update_uwdb:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.0.0
      - ''
    description: Enable/disable allowlist update.
  update_dldb:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.4.0
      - ''
    description: Enable/disable DLP signature update.
  update_extdb:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.0.0
      - ''
    description: Enable/disable external resource update.
  update_build_proxy:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.0.0
      - ''
    description: Enable/disable proxy dictionary rebuild.
  persistent_connection:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.0.0
      - ''
    description: Enable/disable use of persistent connection to receive update notification from FortiGuard.
  vdom:
    type: string
    raw_type: string
    version_ranges:
    - - v7.2.0
      - ''
    description: FortiGuard Service virtual domain name. Source system.vdom.name.
    references:
    - system.vdom.name
  auto_firmware_upgrade:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.2.1
      - ''
    description: Enable/disable automatic patch-level firmware upgrade from FortiGuard. The FortiGate unit searches for new
      patches only in the same major and minor version.
  auto_firmware_upgrade_day:
    type: enum
    raw_type: list
    choices:
    - sunday
    - monday
    - tuesday
    - wednesday
    - thursday
    - friday
    - saturday
    multiple_values: true
    elements: str
    version_ranges:
    - - v7.2.1
      - ''
    description: Allowed day(s) of the week to install an automatic patch-level firmware upgrade from FortiGuard . Disallow
      any day of the week to use auto-firmware-upgrade-delay instead, which waits for designated days before installing an
      automatic patch-level firmware upgrade.
  auto_firmware_upgrade_delay:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.4.0
      - ''
    description: Delay of day(s) before installing an automatic patch-level firmware upgrade from FortiGuard  of the week
      for installing an automatic patch-level firmware upgrade.
  auto_firmware_upgrade_start_hour:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.2.1
      - ''
    description: Start time in the designated time window for automatic patch-level firmware upgrade from FortiGuard in 24
      hour time (0 ~ 23). The actual upgrade time is selected randomly within the time window.
  auto_firmware_upgrade_end_hour:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.2.1
      - ''
    description: End time in the designated time window for automatic patch-level firmware upgrade from FortiGuard in 24 hour
      time (0 ~ 23). When the end time is smaller than the start time, the end time is interpreted as the next day. The actual
      upgrade time is selected randomly within the time window.
  FDS_license_expiring_days:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.4.0
      - ''
    description: Threshold for number of days before FortiGuard license expiration to generate license expiring event log
      (1 - 100 days).
  subscribe_update_notification:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.6.3
      - ''
    description: Enable/disable subscription to receive update notification from FortiGuard.
  antispam_force_off:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable turning off the FortiGuard antispam service.
  antispam_cache:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable FortiGuard antispam request caching. Uses a small amount of memory but improves performance.
  antispam_cache_ttl:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Time-to-live for antispam cache entries in seconds (300 - 86400). Lower times reduce the cache size. Higher
      times may improve performance since the cache will have more entries.
  antispam_cache_mpermille:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.4.0
      - ''
    description: Maximum permille of FortiGate memory the antispam cache is allowed to use (1 - 150).
  antispam_timeout:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Antispam query time out (1 - 30 sec).
  outbreak_prevention_force_off:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Turn off FortiGuard Virus Outbreak Prevention service.
  outbreak_prevention_cache:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable FortiGuard Virus Outbreak Prevention cache.
  outbreak_prevention_cache_ttl:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Time-to-live for FortiGuard Virus Outbreak Prevention cache entries (300 - 86400 sec).
  outbreak_prevention_cache_mpermille:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.4.0
      - ''
    description: Maximum permille of memory FortiGuard Virus Outbreak Prevention cache can use (1 - 150 permille).
  outbreak_prevention_timeout:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: FortiGuard Virus Outbreak Prevention time out (1 - 30 sec).
  webfilter_force_off:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable turning off the FortiGuard web filtering service.
  webfilter_cache:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable FortiGuard web filter caching.
  webfilter_cache_ttl:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Time-to-live for web filter cache entries in seconds (300 - 86400).
  webfilter_timeout:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Web filter query time out (1 - 30 sec).
  sdns_server_ip:
    type: list
    raw_type: list
    multiple_values: true
    elements: str
    version_ranges:
    - - v6.0.0
      - ''
    description: IP address of the FortiGuard DNS rating server.
  sdns_server_port:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Port to connect to on the FortiGuard DNS rating server.
  anycast_sdns_server_ip:
    type: string
    raw_type: string
    version_ranges:
    - - v6.4.0
      - ''
    description: IP address of the FortiGuard anycast DNS rating server.
  anycast_sdns_server_port:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.4.0
      - ''
    description: Port to connect to on the FortiGuard anycast DNS rating server.
  sdns_options:
    type: enum
    raw_type: list
    choices:
    - include-question-section
    multiple_values: true
    elements: str
    version_ranges:
    - - v6.4.0
      - ''
    description: Customization options for the FortiGuard DNS service.
  source_ip:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Source IPv4 address used to communicate with FortiGuard.
  source_ip6:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Source IPv6 address used to communicate with FortiGuard.
  proxy_server_ip:
    type: string
    raw_type: string
    version_ranges:
    - - v6.2.0
      - ''
    description: Hostname or IPv4 address of the proxy server.
  proxy_server_port:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.2.0
      - ''
    description: Port used to communicate with the proxy server.
  proxy_username:
    type: string
    raw_type: string
    version_ranges:
    - - v6.2.0
      - ''
    description: Proxy user name.
  proxy_password:
    type: string
    raw_type: string
    version_ranges:
    - - v6.2.0
      - ''
    description: Proxy user password.
  ddns_server_ip:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: IP address of the FortiDDNS server.
  ddns_server_ip6:
    type: string
    raw_type: string
    version_ranges:
    - - v7.0.1
      - ''
    description: IPv6 address of the FortiDDNS server.
  ddns_server_port:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Port used to communicate with FortiDDNS servers.
  interface_select_method:
    type: enum
    raw_type: string
    choices:
    - auto
    - sdwan
    - specify
    version_ranges:
    - - v6.2.0
      - v6.2.0
    - - v6.2.5
      - ''
    description: Specify how to select outgoing interface to reach server.
  interface:
    type: string
    raw_type: string
    version_ranges:
    - - v6.2.0
      - v6.2.0
    - - v6.2.5
      - ''
    description: Specify outgoing interface to reach server. Source system.interface.name.
    references:
    - system.interface.name
  vrf_select:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.6.1
      - ''
    description: VRF ID used for connection to server.
  auto_join_forticloud:
    type: string
    raw_type: string
    description: Automatically connect to and login to FortiCloud.
