id: system.pppoe-interface
version: 7.6.7
source_object: fortios_system_pppoe_interface
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_system_pppoe_interface.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v6.0.0
      - ''
    description: Name of the PPPoE interface.
  dial_on_demand:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable dial on demand to dial the PPPoE interface when packets are routed to the PPPoE interface.
  ipv6:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable IPv6 Control Protocol (IPv6CP).
  device:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Name for the physical interface. Source system.interface.name.
    references:
    - system.interface.name
  username:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: User name.
  password:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Enter the password.
  pppoe_egress_cos:
    type: enum
    raw_type: string
    choices:
    - cos0
    - cos1
    - cos2
    - cos3
    - cos4
    - cos5
    - cos6
    - cos7
    version_ranges:
    - - v7.6.0
      - ''
    description: CoS in VLAN tag for outgoing PPPoE/PPP packets.
  auth_type:
    type: enum
    raw_type: string
    choices:
    - auto
    - pap
    - chap
    - mschapv1
    - mschapv2
    version_ranges:
    - - v6.0.0
      - ''
    description: PPP authentication type to use.
  ipunnumbered:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: PPPoE unnumbered IP.
  pppoe_unnumbered_negotiate:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable PPPoE unnumbered negotiation.
  idle_timeout:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: PPPoE auto disconnect after idle timeout (0-4294967295 sec).
  multilink:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.6.5
      - ''
    description: Enable/disable PPP multilink support.
  mrru:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.6.5
      - ''
    description: PPP MRRU (296 - 65535).
  disc_retry_timeout:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: PPPoE discovery init timeout value in (0-4294967295 sec).
  padt_retry_timeout:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: PPPoE terminate timeout value in (0-4294967295 sec).
  service_name:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: PPPoE service name.
  ac_name:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: PPPoE AC name.
  lcp_echo_interval:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Time in seconds between PPPoE Link Control Protocol (LCP) echo requests.
  lcp_max_echo_fails:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Maximum missed LCP echo messages before disconnect.
