id: system.sso-fortigate-cloud-admin
version: 7.6.7
source_object: fortios_system_sso_fortigate_cloud_admin
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_system_sso_fortigate_cloud_admin.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v7.2.4
      - ''
    description: FortiCloud SSO admin name.
  accprofile:
    type: string
    raw_type: string
    version_ranges:
    - - v7.2.4
      - ''
    description: FortiCloud SSO admin user access profile. Permission is set to read-only without a FortiGate Cloud Central
      Management license. Source system.accprofile.name.
    references:
    - system.accprofile.name
  vdom:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v7.2.4
      - ''
    description: Virtual domain(s) that the administrator can access.
    children:
      name:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v7.2.4
          - ''
        description: Virtual domain name. Source system.vdom.name.
        references:
        - system.vdom.name
