id: system.accprofile
version: 7.6.7
source_object: fortios_system_accprofile
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_system_accprofile.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v6.0.0
      - ''
    description: Profile name.
  scope:
    type: enum
    raw_type: string
    choices:
    - vdom
    - global
    version_ranges:
    - - v6.0.0
      - ''
    description: 'Scope of admin access: global or specific VDOM(s).'
  comments:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Comment.
  secfabgrp:
    type: enum
    raw_type: string
    choices:
    - none
    - read
    - read-write
    - custom
    version_ranges:
    - - v6.0.0
      - ''
    description: Security Fabric.
  ftviewgrp:
    type: enum
    raw_type: string
    choices:
    - none
    - read
    - read-write
    version_ranges:
    - - v6.0.0
      - ''
    description: FortiView.
  authgrp:
    type: enum
    raw_type: string
    choices:
    - none
    - read
    - read-write
    version_ranges:
    - - v6.0.0
      - ''
    description: Administrator access to Users and Devices.
  sysgrp:
    type: enum
    raw_type: string
    choices:
    - none
    - read
    - read-write
    - custom
    version_ranges:
    - - v6.0.0
      - ''
    description: System Configuration.
  netgrp:
    type: enum
    raw_type: string
    choices:
    - none
    - read
    - read-write
    - custom
    version_ranges:
    - - v6.0.0
      - ''
    description: Network Configuration.
  loggrp:
    type: enum
    raw_type: string
    choices:
    - none
    - read
    - read-write
    - custom
    version_ranges:
    - - v6.0.0
      - ''
    description: Administrator access to Logging and Reporting including viewing log messages.
  fwgrp:
    type: enum
    raw_type: string
    choices:
    - none
    - read
    - read-write
    - custom
    version_ranges:
    - - v6.0.0
      - ''
    description: Administrator access to the Firewall configuration.
  vpngrp:
    type: enum
    raw_type: string
    choices:
    - none
    - read
    - read-write
    version_ranges:
    - - v6.0.0
      - ''
    description: Administrator access to IPsec, SSL, PPTP, and L2TP VPN.
  utmgrp:
    type: enum
    raw_type: string
    choices:
    - none
    - read
    - read-write
    - custom
    version_ranges:
    - - v6.0.0
      - ''
    description: Administrator access to Security Profiles.
  wanoptgrp:
    type: enum
    raw_type: string
    choices:
    - none
    - read
    - read-write
    version_ranges:
    - - v6.0.0
      - v7.4.1
    - - v7.4.3
      - ''
    description: Administrator access to WAN Opt & Cache.
  wifi:
    type: enum
    raw_type: string
    choices:
    - none
    - read
    - read-write
    version_ranges:
    - - v6.0.0
      - ''
    description: Administrator access to the WiFi controller and Switch controller.
  netgrp_permission:
    type: object
    raw_type: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: Custom network permission.
    children:
      cfg:
        type: enum
        raw_type: string
        choices:
        - none
        - read
        - read-write
        version_ranges:
        - - v6.0.0
          - ''
        description: Network Configuration.
      packet_capture:
        type: enum
        raw_type: string
        choices:
        - none
        - read
        - read-write
        version_ranges:
        - - v6.0.0
          - ''
        description: Packet Capture Configuration.
      route_cfg:
        type: enum
        raw_type: string
        choices:
        - none
        - read
        - read-write
        version_ranges:
        - - v6.0.0
          - ''
        description: Router Configuration.
  sysgrp_permission:
    type: object
    raw_type: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: Custom system permission.
    children:
      admin:
        type: enum
        raw_type: string
        choices:
        - none
        - read
        - read-write
        version_ranges:
        - - v6.0.0
          - ''
        description: Administrator Users.
      upd:
        type: enum
        raw_type: string
        choices:
        - none
        - read
        - read-write
        version_ranges:
        - - v6.0.0
          - ''
        description: FortiGuard Updates.
      cfg:
        type: enum
        raw_type: string
        choices:
        - none
        - read
        - read-write
        version_ranges:
        - - v6.0.0
          - ''
        description: System Configuration.
      mnt:
        type: enum
        raw_type: string
        choices:
        - none
        - read
        - read-write
        version_ranges:
        - - v6.0.0
          - ''
        description: Maintenance.
  fwgrp_permission:
    type: object
    raw_type: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: Custom firewall permission.
    children:
      policy:
        type: enum
        raw_type: string
        choices:
        - none
        - read
        - read-write
        version_ranges:
        - - v6.0.0
          - ''
        description: Policy Configuration.
      address:
        type: enum
        raw_type: string
        choices:
        - none
        - read
        - read-write
        version_ranges:
        - - v6.0.0
          - ''
        description: Address Configuration.
      service:
        type: enum
        raw_type: string
        choices:
        - none
        - read
        - read-write
        version_ranges:
        - - v6.0.0
          - ''
        description: Service Configuration.
      schedule:
        type: enum
        raw_type: string
        choices:
        - none
        - read
        - read-write
        version_ranges:
        - - v6.0.0
          - ''
        description: Schedule Configuration.
      others:
        type: enum
        raw_type: string
        choices:
        - none
        - read
        - read-write
        version_ranges:
        - - v7.0.1
          - ''
        description: Other Firewall Configuration.
  loggrp_permission:
    type: object
    raw_type: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: Custom Log & Report permission.
    children:
      config:
        type: enum
        raw_type: string
        choices:
        - none
        - read
        - read-write
        version_ranges:
        - - v6.0.0
          - ''
        description: Log & Report configuration.
      data_access:
        type: enum
        raw_type: string
        choices:
        - none
        - read
        - read-write
        version_ranges:
        - - v6.0.0
          - ''
        description: Log & Report Data Access.
      report_access:
        type: enum
        raw_type: string
        choices:
        - none
        - read
        - read-write
        version_ranges:
        - - v6.0.0
          - ''
        description: Log & Report Report Access.
      threat_weight:
        type: enum
        raw_type: string
        choices:
        - none
        - read
        - read-write
        version_ranges:
        - - v6.0.0
          - ''
        description: Log & Report Threat Weight.
  utmgrp_permission:
    type: object
    raw_type: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: Custom Security Profile permissions.
    children:
      antivirus:
        type: enum
        raw_type: string
        choices:
        - none
        - read
        - read-write
        version_ranges:
        - - v6.0.0
          - ''
        description: Antivirus profiles and settings.
      ips:
        type: enum
        raw_type: string
        choices:
        - none
        - read
        - read-write
        version_ranges:
        - - v6.0.0
          - ''
        description: IPS profiles and settings.
      webfilter:
        type: enum
        raw_type: string
        choices:
        - none
        - read
        - read-write
        version_ranges:
        - - v6.0.0
          - ''
        description: Web Filter profiles and settings.
      emailfilter:
        type: enum
        raw_type: string
        choices:
        - none
        - read
        - read-write
        version_ranges:
        - - v6.2.0
          - ''
        description: Email Filter and settings.
      dlp:
        type: enum
        raw_type: string
        choices:
        - none
        - read
        - read-write
        version_ranges:
        - - v7.4.4
          - ''
        description: DLP profiles and settings.
      file_filter:
        type: enum
        raw_type: string
        choices:
        - none
        - read
        - read-write
        version_ranges:
        - - v6.4.0
          - ''
        description: File-filter profiles and settings.
      application_control:
        type: enum
        raw_type: string
        choices:
        - none
        - read
        - read-write
        version_ranges:
        - - v6.0.0
          - ''
        description: Application Control profiles and settings.
      icap:
        type: enum
        raw_type: string
        choices:
        - none
        - read
        - read-write
        version_ranges:
        - - v6.0.0
          - ''
        description: ICAP profiles and settings.
      voip:
        type: enum
        raw_type: string
        choices:
        - none
        - read
        - read-write
        version_ranges:
        - - v6.0.0
          - ''
        description: VoIP profiles and settings.
      waf:
        type: enum
        raw_type: string
        choices:
        - none
        - read
        - read-write
        version_ranges:
        - - v6.0.0
          - ''
        description: Web Application Firewall profiles and settings.
      dnsfilter:
        type: enum
        raw_type: string
        choices:
        - none
        - read
        - read-write
        version_ranges:
        - - v6.0.0
          - ''
        description: DNS Filter profiles and settings.
      endpoint_control:
        type: enum
        raw_type: string
        choices:
        - none
        - read
        - read-write
        version_ranges:
        - - v6.0.0
          - ''
        description: FortiClient Profiles.
      videofilter:
        type: enum
        raw_type: string
        choices:
        - none
        - read
        - read-write
        version_ranges:
        - - v7.2.0
          - ''
        description: Video filter profiles and settings.
      virtual_patch:
        type: enum
        raw_type: string
        choices:
        - none
        - read
        - read-write
        version_ranges:
        - - v7.4.1
          - ''
        description: Virtual patch profiles and settings.
      casb:
        type: enum
        raw_type: string
        choices:
        - none
        - read
        - read-write
        version_ranges:
        - - v7.4.1
          - ''
        description: Inline CASB filter profile and settings
      telemetry:
        type: enum
        raw_type: string
        choices:
        - none
        - read
        - read-write
        version_ranges:
        - - v7.6.4
          - ''
        description: Telemetry profile and settings.
  secfabgrp_permission:
    type: object
    raw_type: dict
    version_ranges:
    - - v7.6.5
      - ''
    description: Custom Security Fabric permissions.
    children:
      csfsys:
        type: enum
        raw_type: string
        choices:
        - none
        - read
        - read-write
        version_ranges:
        - - v7.6.5
          - ''
        description: Security Fabric system profiles and settings.
      csffoo:
        type: enum
        raw_type: string
        choices:
        - none
        - read
        - read-write
        version_ranges:
        - - v7.6.5
          - ''
        description: Fabric Overlay Orchestrator profiles and settings.
      mmsgtp:
        type: enum
        raw_type: string
        choices:
        - none
        - read
        - read-write
        version_ranges:
        - - v7.6.5
          - v7.6.7
        description: UTM permission.
  admintimeout_override:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable overriding the global administrator idle timeout.
  admintimeout:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Administrator timeout for this access profile (0 - 480 min).
  cli_diagnose:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.4.2
      - ''
    description: Enable/disable permission to run diagnostic commands.
  cli_get:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.4.2
      - ''
    description: Enable/disable permission to run get commands.
  cli_show:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.4.2
      - ''
    description: Enable/disable permission to run show commands.
  cli_exec:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.4.2
      - ''
    description: Enable/disable permission to run execute commands.
  cli_config:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.4.2
      - ''
    description: Enable/disable permission to run config commands.
  system_execute_ssh:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.2.1
      - ''
    description: Enable/disable permission to execute SSH commands.
  system_execute_telnet:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.2.1
      - ''
    description: Enable/disable permission to execute TELNET commands.
