id: system.vxlan
version: 7.6.7
source_object: fortios_system_vxlan
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_system_vxlan.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v6.0.0
      - ''
    description: VXLAN device or interface name. Must be a unique interface name.
  interface:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Outgoing interface for VXLAN encapsulated traffic. Source system.interface.name.
    references:
    - system.interface.name
  vni:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: VXLAN network ID.
  ip_version:
    type: enum
    raw_type: string
    choices:
    - ipv4-unicast
    - ipv6-unicast
    - ipv4-multicast
    - ipv6-multicast
    version_ranges:
    - - v6.0.0
      - ''
    description: IP version to use for the VXLAN interface and so for communication over the VXLAN. IPv4 or IPv6 unicast or
      multicast.
  remote_ip:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: IPv4 address of the VXLAN interface on the device at the remote end of the VXLAN.
    children:
      ip:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: IPv4 address.
  local_ip:
    type: string
    raw_type: string
    version_ranges:
    - - v7.6.4
      - ''
    description: IPv4 address to use as the source address for egress VXLAN packets.
  remote_ip6:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: IPv6 IP address of the VXLAN interface on the device at the remote end of the VXLAN.
    children:
      ip6:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: IPv6 address.
  local_ip6:
    type: string
    raw_type: string
    version_ranges:
    - - v7.6.4
      - ''
    description: IPv6 address to use as the source address for egress VXLAN packets.
  dstport:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: VXLAN destination port (1 - 65535).
  multicast_ttl:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: VXLAN multicast TTL (1-255).
  evpn_id:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.4.0
      - ''
    description: EVPN instance. Source system.evpn.id.
    references:
    - system.evpn.id
  learn_from_traffic:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.4.0
      - ''
    description: Enable/disable VXLAN MAC learning from traffic.
