id: system.vdom-dns
version: 7.6.7
source_object: fortios_system_vdom_dns
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_system_vdom_dns.py
root_type: object
attributes:
  vdom_dns:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable configuring DNS servers for the current VDOM.
  primary:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Primary DNS server IP address for the VDOM.
  secondary:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Secondary DNS server IP address for the VDOM.
  protocol:
    type: enum
    raw_type: list
    choices:
    - cleartext
    - dot
    - doh
    multiple_values: true
    elements: str
    version_ranges:
    - - v7.0.0
      - ''
    description: DNS transport protocols.
  ssl_certificate:
    type: string
    raw_type: string
    version_ranges:
    - - v6.2.0
      - ''
    description: Name of local certificate for SSL connections. Source certificate.local.name.
    references:
    - certificate.local.name
  server_hostname:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.2.0
      - ''
    description: DNS server host name list.
    children:
      hostname:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v6.2.0
          - ''
        description: DNS server host name list separated by space (maximum 4 domains).
  ip6_primary:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Primary IPv6 DNS server IP address for the VDOM.
  ip6_secondary:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Secondary IPv6 DNS server IP address for the VDOM.
  source_ip:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Source IP for communications with the DNS server.
  source_ip_interface:
    type: string
    raw_type: string
    version_ranges:
    - - v7.6.1
      - ''
    description: IP address of the specified interface as the source IP address. Source system.interface.name.
    references:
    - system.interface.name
  interface_select_method:
    type: enum
    raw_type: string
    choices:
    - auto
    - sdwan
    - specify
    version_ranges:
    - - v6.2.0
      - v6.2.0
    - - v6.2.5
      - ''
    description: Specify how to select outgoing interface to reach server.
  interface:
    type: string
    raw_type: string
    version_ranges:
    - - v6.2.0
      - v6.2.0
    - - v6.2.5
      - ''
    description: Specify outgoing interface to reach server. Source system.interface.name.
    references:
    - system.interface.name
  vrf_select:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.6.1
      - ''
    description: VRF ID used for connection to server.
  server_select_method:
    type: enum
    raw_type: string
    choices:
    - least-rtt
    - failover
    version_ranges:
    - - v7.0.1
      - ''
    description: Specify how configured servers are prioritized.
  alt_primary:
    type: string
    raw_type: string
    version_ranges:
    - - v7.0.1
      - ''
    description: Alternate primary DNS server. This is not used as a failover DNS server.
  alt_secondary:
    type: string
    raw_type: string
    version_ranges:
    - - v7.0.1
      - ''
    description: Alternate secondary DNS server. This is not used as a failover DNS server.
