id: system.ike
version: 7.6.7
source_object: fortios_system_ike
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_system_ike.py
root_type: object
attributes:
  embryonic_limit:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.0.0
      - ''
    description: Maximum number of IPsec tunnels to negotiate simultaneously.
  dh_multiprocess:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.0.0
      - ''
    description: Enable/disable multiprocess Diffie-Hellman daemon for IKE.
  dh_worker_count:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.0.0
      - ''
    description: Number of Diffie-Hellman workers to start.
  dh_mode:
    type: enum
    raw_type: string
    choices:
    - software
    - hardware
    version_ranges:
    - - v7.0.0
      - ''
    description: Use software (CPU) or hardware (CPX) to perform Diffie-Hellman calculations.
  dh_keypair_cache:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.0.0
      - ''
    description: Enable/disable Diffie-Hellman key pair cache.
  dh_keypair_count:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.0.0
      - ''
    description: Number of key pairs to pre-generate for each Diffie-Hellman group (per-worker).
  dh_keypair_throttle:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.0.0
      - ''
    description: Enable/disable Diffie-Hellman key pair cache CPU throttling.
  dh_group_1:
    type: object
    raw_type: dict
    version_ranges:
    - - v7.0.0
      - ''
    description: Diffie-Hellman group 1 (MODP-768).
    children:
      mode:
        type: enum
        raw_type: string
        choices:
        - software
        - hardware
        - global
        version_ranges:
        - - v7.0.0
          - ''
        description: Use software (CPU) or hardware (CPX) to perform calculations for this Diffie-Hellman group.
      keypair_cache:
        type: enum
        raw_type: string
        choices:
        - global
        - custom
        version_ranges:
        - - v7.0.0
          - ''
        description: Configure custom key pair cache size for this Diffie-Hellman group.
      keypair_count:
        type: integer
        raw_type: integer
        version_ranges:
        - - v7.0.0
          - ''
        description: Number of key pairs to pre-generate for this Diffie-Hellman group (per-worker).
  dh_group_2:
    type: object
    raw_type: dict
    version_ranges:
    - - v7.0.0
      - ''
    description: Diffie-Hellman group 2 (MODP-1024).
    children:
      mode:
        type: enum
        raw_type: string
        choices:
        - software
        - hardware
        - global
        version_ranges:
        - - v7.0.0
          - ''
        description: Use software (CPU) or hardware (CPX) to perform calculations for this Diffie-Hellman group.
      keypair_cache:
        type: enum
        raw_type: string
        choices:
        - global
        - custom
        version_ranges:
        - - v7.0.0
          - ''
        description: Configure custom key pair cache size for this Diffie-Hellman group.
      keypair_count:
        type: integer
        raw_type: integer
        version_ranges:
        - - v7.0.0
          - ''
        description: Number of key pairs to pre-generate for this Diffie-Hellman group (per-worker).
  dh_group_5:
    type: object
    raw_type: dict
    version_ranges:
    - - v7.0.0
      - ''
    description: Diffie-Hellman group 5 (MODP-1536).
    children:
      mode:
        type: enum
        raw_type: string
        choices:
        - software
        - hardware
        - global
        version_ranges:
        - - v7.0.0
          - ''
        description: Use software (CPU) or hardware (CPX) to perform calculations for this Diffie-Hellman group.
      keypair_cache:
        type: enum
        raw_type: string
        choices:
        - global
        - custom
        version_ranges:
        - - v7.0.0
          - ''
        description: Configure custom key pair cache size for this Diffie-Hellman group.
      keypair_count:
        type: integer
        raw_type: integer
        version_ranges:
        - - v7.0.0
          - ''
        description: Number of key pairs to pre-generate for this Diffie-Hellman group (per-worker).
  dh_group_14:
    type: object
    raw_type: dict
    version_ranges:
    - - v7.0.0
      - ''
    description: Diffie-Hellman group 14 (MODP-2048).
    children:
      mode:
        type: enum
        raw_type: string
        choices:
        - software
        - hardware
        - global
        version_ranges:
        - - v7.0.0
          - ''
        description: Use software (CPU) or hardware (CPX) to perform calculations for this Diffie-Hellman group.
      keypair_cache:
        type: enum
        raw_type: string
        choices:
        - global
        - custom
        version_ranges:
        - - v7.0.0
          - ''
        description: Configure custom key pair cache size for this Diffie-Hellman group.
      keypair_count:
        type: integer
        raw_type: integer
        version_ranges:
        - - v7.0.0
          - ''
        description: Number of key pairs to pre-generate for this Diffie-Hellman group (per-worker).
  dh_group_15:
    type: object
    raw_type: dict
    version_ranges:
    - - v7.0.0
      - ''
    description: Diffie-Hellman group 15 (MODP-3072).
    children:
      mode:
        type: enum
        raw_type: string
        choices:
        - software
        - hardware
        - global
        version_ranges:
        - - v7.0.0
          - ''
        description: Use software (CPU) or hardware (CPX) to perform calculations for this Diffie-Hellman group.
      keypair_cache:
        type: enum
        raw_type: string
        choices:
        - global
        - custom
        version_ranges:
        - - v7.0.0
          - ''
        description: Configure custom key pair cache size for this Diffie-Hellman group.
      keypair_count:
        type: integer
        raw_type: integer
        version_ranges:
        - - v7.0.0
          - ''
        description: Number of key pairs to pre-generate for this Diffie-Hellman group (per-worker).
  dh_group_16:
    type: object
    raw_type: dict
    version_ranges:
    - - v7.0.0
      - ''
    description: Diffie-Hellman group 16 (MODP-4096).
    children:
      mode:
        type: enum
        raw_type: string
        choices:
        - software
        - hardware
        - global
        version_ranges:
        - - v7.0.0
          - ''
        description: Use software (CPU) or hardware (CPX) to perform calculations for this Diffie-Hellman group.
      keypair_cache:
        type: enum
        raw_type: string
        choices:
        - global
        - custom
        version_ranges:
        - - v7.0.0
          - ''
        description: Configure custom key pair cache size for this Diffie-Hellman group.
      keypair_count:
        type: integer
        raw_type: integer
        version_ranges:
        - - v7.0.0
          - ''
        description: Number of key pairs to pre-generate for this Diffie-Hellman group (per-worker).
  dh_group_17:
    type: object
    raw_type: dict
    version_ranges:
    - - v7.0.0
      - ''
    description: Diffie-Hellman group 17 (MODP-6144).
    children:
      mode:
        type: enum
        raw_type: string
        choices:
        - software
        - hardware
        - global
        version_ranges:
        - - v7.0.0
          - ''
        description: Use software (CPU) or hardware (CPX) to perform calculations for this Diffie-Hellman group.
      keypair_cache:
        type: enum
        raw_type: string
        choices:
        - global
        - custom
        version_ranges:
        - - v7.0.0
          - ''
        description: Configure custom key pair cache size for this Diffie-Hellman group.
      keypair_count:
        type: integer
        raw_type: integer
        version_ranges:
        - - v7.0.0
          - ''
        description: Number of key pairs to pre-generate for this Diffie-Hellman group (per-worker).
  dh_group_18:
    type: object
    raw_type: dict
    version_ranges:
    - - v7.0.0
      - ''
    description: Diffie-Hellman group 18 (MODP-8192).
    children:
      mode:
        type: enum
        raw_type: string
        choices:
        - software
        - hardware
        - global
        version_ranges:
        - - v7.0.0
          - ''
        description: Use software (CPU) or hardware (CPX) to perform calculations for this Diffie-Hellman group.
      keypair_cache:
        type: enum
        raw_type: string
        choices:
        - global
        - custom
        version_ranges:
        - - v7.0.0
          - ''
        description: Configure custom key pair cache size for this Diffie-Hellman group.
      keypair_count:
        type: integer
        raw_type: integer
        version_ranges:
        - - v7.0.0
          - ''
        description: Number of key pairs to pre-generate for this Diffie-Hellman group (per-worker).
  dh_group_19:
    type: object
    raw_type: dict
    version_ranges:
    - - v7.0.0
      - ''
    description: Diffie-Hellman group 19 (EC-P256).
    children:
      mode:
        type: enum
        raw_type: string
        choices:
        - software
        - hardware
        - global
        version_ranges:
        - - v7.0.0
          - ''
        description: Use software (CPU) or hardware (CPX) to perform calculations for this Diffie-Hellman group.
      keypair_cache:
        type: enum
        raw_type: string
        choices:
        - global
        - custom
        version_ranges:
        - - v7.0.0
          - ''
        description: Configure custom key pair cache size for this Diffie-Hellman group.
      keypair_count:
        type: integer
        raw_type: integer
        version_ranges:
        - - v7.0.0
          - ''
        description: Number of key pairs to pre-generate for this Diffie-Hellman group (per-worker).
  dh_group_20:
    type: object
    raw_type: dict
    version_ranges:
    - - v7.0.0
      - ''
    description: Diffie-Hellman group 20 (EC-P384).
    children:
      mode:
        type: enum
        raw_type: string
        choices:
        - software
        - hardware
        - global
        version_ranges:
        - - v7.0.0
          - ''
        description: Use software (CPU) or hardware (CPX) to perform calculations for this Diffie-Hellman group.
      keypair_cache:
        type: enum
        raw_type: string
        choices:
        - global
        - custom
        version_ranges:
        - - v7.0.0
          - ''
        description: Configure custom key pair cache size for this Diffie-Hellman group.
      keypair_count:
        type: integer
        raw_type: integer
        version_ranges:
        - - v7.0.0
          - ''
        description: Number of key pairs to pre-generate for this Diffie-Hellman group (per-worker).
  dh_group_21:
    type: object
    raw_type: dict
    version_ranges:
    - - v7.0.0
      - ''
    description: Diffie-Hellman group 21 (EC-P521).
    children:
      mode:
        type: enum
        raw_type: string
        choices:
        - software
        - hardware
        - global
        version_ranges:
        - - v7.0.0
          - ''
        description: Use software (CPU) or hardware (CPX) to perform calculations for this Diffie-Hellman group.
      keypair_cache:
        type: enum
        raw_type: string
        choices:
        - global
        - custom
        version_ranges:
        - - v7.0.0
          - ''
        description: Configure custom key pair cache size for this Diffie-Hellman group.
      keypair_count:
        type: integer
        raw_type: integer
        version_ranges:
        - - v7.0.0
          - ''
        description: Number of key pairs to pre-generate for this Diffie-Hellman group (per-worker).
  dh_group_27:
    type: object
    raw_type: dict
    version_ranges:
    - - v7.0.0
      - ''
    description: Diffie-Hellman group 27 (EC-P224BP).
    children:
      mode:
        type: enum
        raw_type: string
        choices:
        - software
        - hardware
        - global
        version_ranges:
        - - v7.0.0
          - ''
        description: Use software (CPU) or hardware (CPX) to perform calculations for this Diffie-Hellman group.
      keypair_cache:
        type: enum
        raw_type: string
        choices:
        - global
        - custom
        version_ranges:
        - - v7.0.0
          - ''
        description: Configure custom key pair cache size for this Diffie-Hellman group.
      keypair_count:
        type: integer
        raw_type: integer
        version_ranges:
        - - v7.0.0
          - ''
        description: Number of key pairs to pre-generate for this Diffie-Hellman group (per-worker).
  dh_group_28:
    type: object
    raw_type: dict
    version_ranges:
    - - v7.0.0
      - ''
    description: Diffie-Hellman group 28 (EC-P256BP).
    children:
      mode:
        type: enum
        raw_type: string
        choices:
        - software
        - hardware
        - global
        version_ranges:
        - - v7.0.0
          - ''
        description: Use software (CPU) or hardware (CPX) to perform calculations for this Diffie-Hellman group.
      keypair_cache:
        type: enum
        raw_type: string
        choices:
        - global
        - custom
        version_ranges:
        - - v7.0.0
          - ''
        description: Configure custom key pair cache size for this Diffie-Hellman group.
      keypair_count:
        type: integer
        raw_type: integer
        version_ranges:
        - - v7.0.0
          - ''
        description: Number of key pairs to pre-generate for this Diffie-Hellman group (per-worker).
  dh_group_29:
    type: object
    raw_type: dict
    version_ranges:
    - - v7.0.0
      - ''
    description: Diffie-Hellman group 29 (EC-P384BP).
    children:
      mode:
        type: enum
        raw_type: string
        choices:
        - software
        - hardware
        - global
        version_ranges:
        - - v7.0.0
          - ''
        description: Use software (CPU) or hardware (CPX) to perform calculations for this Diffie-Hellman group.
      keypair_cache:
        type: enum
        raw_type: string
        choices:
        - global
        - custom
        version_ranges:
        - - v7.0.0
          - ''
        description: Configure custom key pair cache size for this Diffie-Hellman group.
      keypair_count:
        type: integer
        raw_type: integer
        version_ranges:
        - - v7.0.0
          - ''
        description: Number of key pairs to pre-generate for this Diffie-Hellman group (per-worker).
  dh_group_30:
    type: object
    raw_type: dict
    version_ranges:
    - - v7.0.0
      - ''
    description: Diffie-Hellman group 30 (EC-P512BP).
    children:
      mode:
        type: enum
        raw_type: string
        choices:
        - software
        - hardware
        - global
        version_ranges:
        - - v7.0.0
          - ''
        description: Use software (CPU) or hardware (CPX) to perform calculations for this Diffie-Hellman group.
      keypair_cache:
        type: enum
        raw_type: string
        choices:
        - global
        - custom
        version_ranges:
        - - v7.0.0
          - ''
        description: Configure custom key pair cache size for this Diffie-Hellman group.
      keypair_count:
        type: integer
        raw_type: integer
        version_ranges:
        - - v7.0.0
          - ''
        description: Number of key pairs to pre-generate for this Diffie-Hellman group (per-worker).
  dh_group_31:
    type: object
    raw_type: dict
    version_ranges:
    - - v7.0.0
      - ''
    description: Diffie-Hellman group 31 (EC-X25519).
    children:
      mode:
        type: enum
        raw_type: string
        choices:
        - software
        - hardware
        - global
        version_ranges:
        - - v7.0.0
          - ''
        description: Use software (CPU) or hardware (CPX) to perform calculations for this Diffie-Hellman group.
      keypair_cache:
        type: enum
        raw_type: string
        choices:
        - global
        - custom
        version_ranges:
        - - v7.0.0
          - ''
        description: Configure custom key pair cache size for this Diffie-Hellman group.
      keypair_count:
        type: integer
        raw_type: integer
        version_ranges:
        - - v7.0.0
          - ''
        description: Number of key pairs to pre-generate for this Diffie-Hellman group (per-worker).
  dh_group_32:
    type: object
    raw_type: dict
    version_ranges:
    - - v7.0.0
      - ''
    description: Diffie-Hellman group 32 (EC-X448).
    children:
      mode:
        type: enum
        raw_type: string
        choices:
        - software
        - hardware
        - global
        version_ranges:
        - - v7.0.0
          - ''
        description: Use software (CPU) or hardware (CPX) to perform calculations for this Diffie-Hellman group.
      keypair_cache:
        type: enum
        raw_type: string
        choices:
        - global
        - custom
        version_ranges:
        - - v7.0.0
          - ''
        description: Configure custom key pair cache size for this Diffie-Hellman group.
      keypair_count:
        type: integer
        raw_type: integer
        version_ranges:
        - - v7.0.0
          - ''
        description: Number of key pairs to pre-generate for this Diffie-Hellman group (per-worker).
