id: system.gi-gk
version: 7.6.7
source_object: fortios_system_gi_gk
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_system_gi_gk.py
root_type: object
attributes:
  context:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - v7.0.8
    - - v7.2.0
      - v7.2.4
    - - v7.4.3
      - v7.6.7
    description: Context ID
  port:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - v7.0.8
    - - v7.2.0
      - v7.2.4
    - - v7.4.3
      - v7.6.7
    description: UDP port to listen, range 0-65535.
