id: system.fortisandbox
version: 7.6.7
source_object: fortios_system_fortisandbox
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_system_fortisandbox.py
root_type: list
attributes:
  status:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable FortiSandbox.
  inline_scan:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.2.0
      - ''
    description: Enable/disable FortiSandbox inline scan.
  server:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Server IP address or FQDN of the remote FortiSandbox.
  source_ip:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Source IP address for communications to FortiSandbox.
  interface_select_method:
    type: enum
    raw_type: string
    choices:
    - auto
    - sdwan
    - specify
    version_ranges:
    - - v6.4.0
      - v6.4.0
    - - v6.4.4
      - ''
    description: Specify how to select outgoing interface to reach server.
  interface:
    type: string
    raw_type: string
    version_ranges:
    - - v6.4.0
      - v6.4.0
    - - v6.4.4
      - ''
    description: Specify outgoing interface to reach server. Source system.interface.name.
    references:
    - system.interface.name
  vrf_select:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.6.1
      - ''
    description: VRF ID used for connection to server.
  enc_algorithm:
    type: enum
    raw_type: string
    choices:
    - default
    - high
    - low
    version_ranges:
    - - v6.0.0
      - ''
    description: Configure the level of SSL protection for secure communication with FortiSandbox.
  ssl_min_proto_version:
    type: enum
    raw_type: string
    choices:
    - default
    - SSLv3
    - TLSv1
    - TLSv1-1
    - TLSv1-2
    - TLSv1-3
    version_ranges:
    - - v6.0.0
      - ''
    description: Minimum supported protocol version for SSL/TLS connections .
  email:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Notifier email address.
  certificate_verification:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.6.3
      - ''
    description: Enable/disable identity verification of FortiSandbox by use of certificate.
  ca:
    type: string
    raw_type: string
    version_ranges:
    - - v7.6.1
      - ''
    description: The CA that signs remote FortiSandbox certificate, empty for no check. Source certificate.ca.name.
    references:
    - certificate.ca.name
  forticloud:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.0.0
      - v7.6.7
    description: Enable/disable FortiSandbox Cloud.
  cn:
    type: string
    raw_type: string
    version_ranges:
    - - v7.6.1
      - v7.6.7
    description: The CN of remote server certificate, case sensitive, empty for no check.
