id: system.gre-tunnel
version: 7.6.7
source_object: fortios_system_gre_tunnel
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_system_gre_tunnel.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v6.0.0
      - ''
    description: Tunnel name.
  interface:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Interface name. Source system.interface.name.
    references:
    - system.interface.name
  ip_version:
    type: enum
    raw_type: string
    choices:
    - '4'
    - '6'
    version_ranges:
    - - v6.0.0
      - ''
    description: IP version to use for VPN interface.
  remote_gw6:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: IPv6 address of the remote gateway.
  local_gw6:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: IPv6 address of the local gateway.
  remote_gw:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: IP address of the remote gateway.
  local_gw:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: IP address of the local gateway.
  use_sdwan:
    type: enum
    raw_type: string
    choices:
    - disable
    - enable
    version_ranges:
    - - v7.0.0
      - ''
    description: Enable/disable use of SD-WAN to reach remote gateway.
  sequence_number_transmission:
    type: enum
    raw_type: string
    choices:
    - disable
    - enable
    version_ranges:
    - - v6.4.0
      - v6.4.0
    - - v7.2.0
      - v7.2.0
    - - v7.4.0
      - ''
    description: Enable/disable including of sequence numbers in transmitted GRE packets.
  sequence_number_reception:
    type: enum
    raw_type: string
    choices:
    - disable
    - enable
    version_ranges:
    - - v6.4.0
      - v6.4.0
    - - v7.2.0
      - v7.2.0
    - - v7.4.0
      - ''
    description: Enable/disable validating sequence numbers in received GRE packets.
  checksum_transmission:
    type: enum
    raw_type: string
    choices:
    - disable
    - enable
    version_ranges:
    - - v6.4.0
      - v6.4.0
    - - v7.2.0
      - v7.2.0
    - - v7.4.0
      - ''
    description: Enable/disable including checksums in transmitted GRE packets.
  checksum_reception:
    type: enum
    raw_type: string
    choices:
    - disable
    - enable
    version_ranges:
    - - v6.4.0
      - v6.4.0
    - - v7.2.0
      - v7.2.0
    - - v7.4.0
      - ''
    description: Enable/disable validating checksums in received GRE packets.
  key_outbound:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.4.0
      - v6.4.0
    - - v7.2.0
      - v7.2.0
    - - v7.4.0
      - ''
    description: Include this key in transmitted GRE packets (0 - 4294967295).
  key_inbound:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.4.0
      - v6.4.0
    - - v7.2.0
      - v7.2.0
    - - v7.4.0
      - ''
    description: Require received GRE packets contain this key (0 - 4294967295).
  dscp_copying:
    type: enum
    raw_type: string
    choices:
    - disable
    - enable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable DSCP copying.
  diffservcode:
    type: string
    raw_type: string
    version_ranges:
    - - v6.2.0
      - ''
    description: DiffServ setting to be applied to GRE tunnel outer IP header.
  keepalive_interval:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Keepalive message interval (0 - 32767, 0 = disabled).
  keepalive_failtimes:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Number of consecutive unreturned keepalive messages before a GRE connection is considered down (1 - 255).
