id: system.dscp-based-priority
version: 7.6.7
source_object: fortios_system_dscp_based_priority
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_system_dscp_based_priority.py
root_type: list
attributes:
  id:
    type: integer
    raw_type: integer
    required: true
    version_ranges:
    - - v6.0.0
      - ''
    description: Item ID. see <a href='#notes'>Notes</a>.
  ds:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: DSCP(DiffServ) DS value (0 - 63).
  priority:
    type: enum
    raw_type: string
    choices:
    - low
    - medium
    - high
    version_ranges:
    - - v6.0.0
      - ''
    description: DSCP based priority level.
