id: system.network-visibility
version: 7.6.7
source_object: fortios_system_network_visibility
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_system_network_visibility.py
root_type: object
attributes:
  destination_visibility:
    type: enum
    raw_type: string
    choices:
    - disable
    - enable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable logging of destination visibility.
  source_location:
    type: enum
    raw_type: string
    choices:
    - disable
    - enable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable logging of source geographical location visibility.
  destination_hostname_visibility:
    type: enum
    raw_type: string
    choices:
    - disable
    - enable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable logging of destination hostname visibility.
  destination_location:
    type: enum
    raw_type: string
    choices:
    - disable
    - enable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable logging of destination geographical location visibility.
