id: system.np6
version: 7.6.7
source_object: fortios_system_np6
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_system_np6.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v6.0.0
      - v7.4.1
    - - v7.4.3
      - v7.6.7
    description: Device Name.
  fastpath:
    type: enum
    raw_type: string
    choices:
    - disable
    - enable
    version_ranges:
    - - v6.0.0
      - v7.4.1
    - - v7.4.3
      - v7.6.7
    description: Enable/disable NP6 offloading (also called fast path).
  low_latency_mode:
    type: enum
    raw_type: string
    choices:
    - disable
    - enable
    version_ranges:
    - - v6.0.0
      - v7.4.1
    - - v7.4.3
      - v7.6.7
    description: Enable/disable low latency mode.
  per_session_accounting:
    type: enum
    raw_type: string
    choices:
    - disable
    - traffic-log-only
    - enable
    version_ranges:
    - - v6.0.0
      - v7.4.1
    - - v7.4.3
      - v7.6.7
    description: Enable/disable per-session accounting.
  garbage_session_collector:
    type: enum
    raw_type: string
    choices:
    - disable
    - enable
    version_ranges:
    - - v6.0.0
      - v7.4.1
    - - v7.4.3
      - v7.6.7
    description: Enable/disable garbage session collector.
  session_collector_interval:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - v7.4.1
    - - v7.4.3
      - v7.6.7
    description: Set garbage session collection cleanup interval (1 - 100 sec).
  session_timeout_interval:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - v7.4.1
    - - v7.4.3
      - v7.6.7
    description: Set the fixed timeout for refreshing NP6 sessions (0 - 1000 sec).
  session_timeout_random_range:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - v7.4.1
    - - v7.4.3
      - v7.6.7
    description: Set the random timeout range for refreshing NP6 sessions (0 - 1000 sec).
  session_timeout_fixed:
    type: enum
    raw_type: string
    choices:
    - disable
    - enable
    version_ranges:
    - - v6.0.0
      - v7.4.1
    - - v7.4.3
      - v7.6.7
    description: '{disable | enable} Toggle between using fixed or random timeouts for refreshing NP6 sessions.'
  hpe:
    type: object
    raw_type: dict
    version_ranges:
    - - v6.0.0
      - v7.4.1
    - - v7.4.3
      - v7.6.7
    description: HPE configuration.
    children:
      tcpsyn_max:
        type: integer
        raw_type: integer
        version_ranges:
        - - v6.0.0
          - v7.4.1
        - - v7.4.3
          - v7.6.7
        description: Maximum TCP SYN packet rate (1K - 1G pps).
      tcpsyn_ack_max:
        type: integer
        raw_type: integer
        version_ranges:
        - - v7.0.0
          - v7.4.1
        - - v7.4.3
          - v7.6.7
        description: Maximum TCP carries SYN and ACK flags packet rate (1K - 1G pps).
      tcpfin_rst_max:
        type: integer
        raw_type: integer
        version_ranges:
        - - v7.0.0
          - v7.4.1
        - - v7.4.3
          - v7.6.7
        description: Maximum TCP carries FIN or RST flags packet rate (1K - 1G pps).
      tcp_max:
        type: integer
        raw_type: integer
        version_ranges:
        - - v6.0.0
          - v7.4.1
        - - v7.4.3
          - v7.6.7
        description: Maximum TCP packet rate (1K - 1G pps).
      udp_max:
        type: integer
        raw_type: integer
        version_ranges:
        - - v6.0.0
          - v7.4.1
        - - v7.4.3
          - v7.6.7
        description: Maximum UDP packet rate (1K - 1G pps).
      icmp_max:
        type: integer
        raw_type: integer
        version_ranges:
        - - v6.0.0
          - v7.4.1
        - - v7.4.3
          - v7.6.7
        description: Maximum ICMP packet rate (1K - 1G pps).
      sctp_max:
        type: integer
        raw_type: integer
        version_ranges:
        - - v6.0.0
          - v7.4.1
        - - v7.4.3
          - v7.6.7
        description: Maximum SCTP packet rate (1K - 1G pps).
      esp_max:
        type: integer
        raw_type: integer
        version_ranges:
        - - v6.0.0
          - v7.4.1
        - - v7.4.3
          - v7.6.7
        description: Maximum ESP packet rate (1K - 1G pps).
      ip_frag_max:
        type: integer
        raw_type: integer
        version_ranges:
        - - v6.0.0
          - v7.4.1
        - - v7.4.3
          - v7.6.7
        description: Maximum fragmented IP packet rate (1K - 1G pps).
      ip_others_max:
        type: integer
        raw_type: integer
        version_ranges:
        - - v6.0.0
          - v7.4.1
        - - v7.4.3
          - v7.6.7
        description: Maximum IP packet rate for other packets (packet types that cannot be set with other options) (1K - 1G
          pps).
      arp_max:
        type: integer
        raw_type: integer
        version_ranges:
        - - v6.0.0
          - v7.4.1
        - - v7.4.3
          - v7.6.7
        description: Maximum ARP packet rate (1K - 1G pps).
      l2_others_max:
        type: integer
        raw_type: integer
        version_ranges:
        - - v6.0.0
          - v7.4.1
        - - v7.4.3
          - v7.6.7
        description: Maximum L2 packet rate for L2 packets that are not ARP packets (1K - 1G pps).
      pri_type_max:
        type: integer
        raw_type: integer
        version_ranges:
        - - v6.0.0
          - v6.0.0
        - - v6.0.11
          - v7.4.1
        - - v7.4.3
          - v7.6.7
        description: 'Maximum overflow rate of priority type traffic (1K - 1G pps). Includes L2: HA, 802.3ad LACP, heartbeats.
          L3: OSPF. L4_TCP: BGP. L4_UDP: IKE, SLBC, BFD.'
      enable_shaper:
        type: enum
        raw_type: string
        choices:
        - disable
        - enable
        version_ranges:
        - - v6.0.0
          - v7.4.1
        - - v7.4.3
          - v7.6.7
        description: Enable/Disable NPU Host Protection Engine(HPE) for packet type shaper.
  fp_anomaly:
    type: object
    raw_type: dict
    version_ranges:
    - - v6.0.0
      - v7.4.1
    - - v7.4.3
      - v7.6.7
    description: NP6 IPv4 anomaly protection. trap-to-host forwards anomaly sessions to the CPU.
    children:
      tcp_syn_fin:
        type: enum
        raw_type: string
        choices:
        - allow
        - drop
        - trap-to-host
        version_ranges:
        - - v6.0.0
          - v7.4.1
        - - v7.4.3
          - v7.6.7
        description: TCP SYN flood SYN/FIN flag set anomalies.
      tcp_fin_noack:
        type: enum
        raw_type: string
        choices:
        - allow
        - drop
        - trap-to-host
        version_ranges:
        - - v6.0.0
          - v7.4.1
        - - v7.4.3
          - v7.6.7
        description: TCP SYN flood with FIN flag set without ACK setting anomalies.
      tcp_fin_only:
        type: enum
        raw_type: string
        choices:
        - allow
        - drop
        - trap-to-host
        version_ranges:
        - - v6.0.0
          - v7.4.1
        - - v7.4.3
          - v7.6.7
        description: TCP SYN flood with only FIN flag set anomalies.
      tcp_no_flag:
        type: enum
        raw_type: string
        choices:
        - allow
        - drop
        - trap-to-host
        version_ranges:
        - - v6.0.0
          - v7.4.1
        - - v7.4.3
          - v7.6.7
        description: TCP SYN flood with no flag set anomalies.
      tcp_syn_data:
        type: enum
        raw_type: string
        choices:
        - allow
        - drop
        - trap-to-host
        version_ranges:
        - - v6.0.0
          - v7.4.1
        - - v7.4.3
          - v7.6.7
        description: TCP SYN flood packets with data anomalies.
      tcp_winnuke:
        type: enum
        raw_type: string
        choices:
        - allow
        - drop
        - trap-to-host
        version_ranges:
        - - v6.0.0
          - v7.4.1
        - - v7.4.3
          - v7.6.7
        description: TCP WinNuke anomalies.
      tcp_land:
        type: enum
        raw_type: string
        choices:
        - allow
        - drop
        - trap-to-host
        version_ranges:
        - - v6.0.0
          - v7.4.1
        - - v7.4.3
          - v7.6.7
        description: TCP land anomalies.
      udp_land:
        type: enum
        raw_type: string
        choices:
        - allow
        - drop
        - trap-to-host
        version_ranges:
        - - v6.0.0
          - v7.4.1
        - - v7.4.3
          - v7.6.7
        description: UDP land anomalies.
      icmp_land:
        type: enum
        raw_type: string
        choices:
        - allow
        - drop
        - trap-to-host
        version_ranges:
        - - v6.0.0
          - v7.4.1
        - - v7.4.3
          - v7.6.7
        description: ICMP land anomalies.
      icmp_frag:
        type: enum
        raw_type: string
        choices:
        - allow
        - drop
        - trap-to-host
        version_ranges:
        - - v6.0.0
          - v7.4.1
        - - v7.4.3
          - v7.6.7
        description: Layer 3 fragmented packets that could be part of layer 4 ICMP anomalies.
      ipv4_land:
        type: enum
        raw_type: string
        choices:
        - allow
        - drop
        - trap-to-host
        version_ranges:
        - - v6.0.0
          - v7.4.1
        - - v7.4.3
          - v7.6.7
        description: Land anomalies.
      ipv4_proto_err:
        type: enum
        raw_type: string
        choices:
        - allow
        - drop
        - trap-to-host
        version_ranges:
        - - v6.0.0
          - v7.4.1
        - - v7.4.3
          - v7.6.7
        description: Invalid layer 4 protocol anomalies.
      ipv4_unknopt:
        type: enum
        raw_type: string
        choices:
        - allow
        - drop
        - trap-to-host
        version_ranges:
        - - v6.0.0
          - v7.4.1
        - - v7.4.3
          - v7.6.7
        description: Unknown option anomalies.
      ipv4_optrr:
        type: enum
        raw_type: string
        choices:
        - allow
        - drop
        - trap-to-host
        version_ranges:
        - - v6.0.0
          - v7.4.1
        - - v7.4.3
          - v7.6.7
        description: Record route option anomalies.
      ipv4_optssrr:
        type: enum
        raw_type: string
        choices:
        - allow
        - drop
        - trap-to-host
        version_ranges:
        - - v6.0.0
          - v7.4.1
        - - v7.4.3
          - v7.6.7
        description: Strict source record route option anomalies.
      ipv4_optlsrr:
        type: enum
        raw_type: string
        choices:
        - allow
        - drop
        - trap-to-host
        version_ranges:
        - - v6.0.0
          - v7.4.1
        - - v7.4.3
          - v7.6.7
        description: Loose source record route option anomalies.
      ipv4_optstream:
        type: enum
        raw_type: string
        choices:
        - allow
        - drop
        - trap-to-host
        version_ranges:
        - - v6.0.0
          - v7.4.1
        - - v7.4.3
          - v7.6.7
        description: Stream option anomalies.
      ipv4_optsecurity:
        type: enum
        raw_type: string
        choices:
        - allow
        - drop
        - trap-to-host
        version_ranges:
        - - v6.0.0
          - v7.4.1
        - - v7.4.3
          - v7.6.7
        description: Security option anomalies.
      ipv4_opttimestamp:
        type: enum
        raw_type: string
        choices:
        - allow
        - drop
        - trap-to-host
        version_ranges:
        - - v6.0.0
          - v7.4.1
        - - v7.4.3
          - v7.6.7
        description: Timestamp option anomalies.
      ipv4_csum_err:
        type: enum
        raw_type: string
        choices:
        - drop
        - trap-to-host
        version_ranges:
        - - v6.0.0
          - v7.4.1
        - - v7.4.3
          - v7.6.7
        description: Invalid IPv4 IP checksum anomalies.
      tcp_csum_err:
        type: enum
        raw_type: string
        choices:
        - drop
        - trap-to-host
        version_ranges:
        - - v6.0.0
          - v7.4.1
        - - v7.4.3
          - v7.6.7
        description: Invalid IPv4 TCP checksum anomalies.
      udp_csum_err:
        type: enum
        raw_type: string
        choices:
        - drop
        - trap-to-host
        version_ranges:
        - - v6.0.0
          - v7.4.1
        - - v7.4.3
          - v7.6.7
        description: Invalid IPv4 UDP checksum anomalies.
      icmp_csum_err:
        type: enum
        raw_type: string
        choices:
        - drop
        - trap-to-host
        version_ranges:
        - - v6.0.0
          - v7.4.1
        - - v7.4.3
          - v7.6.7
        description: Invalid IPv4 ICMP checksum anomalies.
      ipv6_land:
        type: enum
        raw_type: string
        choices:
        - allow
        - drop
        - trap-to-host
        version_ranges:
        - - v6.0.0
          - v7.4.1
        - - v7.4.3
          - v7.6.7
        description: Land anomalies.
      ipv6_proto_err:
        type: enum
        raw_type: string
        choices:
        - allow
        - drop
        - trap-to-host
        version_ranges:
        - - v6.0.0
          - v7.4.1
        - - v7.4.3
          - v7.6.7
        description: Layer 4 invalid protocol anomalies.
      ipv6_unknopt:
        type: enum
        raw_type: string
        choices:
        - allow
        - drop
        - trap-to-host
        version_ranges:
        - - v6.0.0
          - v7.4.1
        - - v7.4.3
          - v7.6.7
        description: Unknown option anomalies.
      ipv6_saddr_err:
        type: enum
        raw_type: string
        choices:
        - allow
        - drop
        - trap-to-host
        version_ranges:
        - - v6.0.0
          - v7.4.1
        - - v7.4.3
          - v7.6.7
        description: Source address as multicast anomalies.
      ipv6_daddr_err:
        type: enum
        raw_type: string
        choices:
        - allow
        - drop
        - trap-to-host
        version_ranges:
        - - v6.0.0
          - v7.4.1
        - - v7.4.3
          - v7.6.7
        description: Destination address as unspecified or loopback address anomalies.
      ipv6_optralert:
        type: enum
        raw_type: string
        choices:
        - allow
        - drop
        - trap-to-host
        version_ranges:
        - - v6.0.0
          - v7.4.1
        - - v7.4.3
          - v7.6.7
        description: Router alert option anomalies.
      ipv6_optjumbo:
        type: enum
        raw_type: string
        choices:
        - allow
        - drop
        - trap-to-host
        version_ranges:
        - - v6.0.0
          - v7.4.1
        - - v7.4.3
          - v7.6.7
        description: Jumbo options anomalies.
      ipv6_opttunnel:
        type: enum
        raw_type: string
        choices:
        - allow
        - drop
        - trap-to-host
        version_ranges:
        - - v6.0.0
          - v7.4.1
        - - v7.4.3
          - v7.6.7
        description: Tunnel encapsulation limit option anomalies.
      ipv6_opthomeaddr:
        type: enum
        raw_type: string
        choices:
        - allow
        - drop
        - trap-to-host
        version_ranges:
        - - v6.0.0
          - v7.4.1
        - - v7.4.3
          - v7.6.7
        description: Home address option anomalies.
      ipv6_optnsap:
        type: enum
        raw_type: string
        choices:
        - allow
        - drop
        - trap-to-host
        version_ranges:
        - - v6.0.0
          - v7.4.1
        - - v7.4.3
          - v7.6.7
        description: Network service access point address option anomalies.
      ipv6_optendpid:
        type: enum
        raw_type: string
        choices:
        - allow
        - drop
        - trap-to-host
        version_ranges:
        - - v6.0.0
          - v7.4.1
        - - v7.4.3
          - v7.6.7
        description: End point identification anomalies.
      ipv6_optinvld:
        type: enum
        raw_type: string
        choices:
        - allow
        - drop
        - trap-to-host
        version_ranges:
        - - v6.0.0
          - v7.4.1
        - - v7.4.3
          - v7.6.7
        description: Invalid option anomalies.Invalid option anomalies.
