id: system.nd-proxy
version: 7.6.7
source_object: fortios_system_nd_proxy
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_system_nd_proxy.py
root_type: object
attributes:
  status:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable neighbor discovery proxy.
  member:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: Interfaces using the neighbor discovery proxy.
    children:
      interface_name:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: Interface name. Source system.interface.name.
        references:
        - system.interface.name
