id: system.ipv6-neighbor-cache
version: 7.6.7
source_object: fortios_system_ipv6_neighbor_cache
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_system_ipv6_neighbor_cache.py
root_type: list
attributes:
  id:
    type: integer
    raw_type: integer
    required: true
    version_ranges:
    - - v6.0.0
      - ''
    description: Unique integer ID of the entry. see <a href='#notes'>Notes</a>.
  interface:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Select the associated interface name from available options. Source system.interface.name.
    references:
    - system.interface.name
  ipv6:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: 'IPv6 address (format: xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx).'
  mac:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: 'MAC address (format: xx:xx:xx:xx:xx:xx).'
