id: system.vdom-link
version: 7.6.7
source_object: fortios_system_vdom_link
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_system_vdom_link.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v6.0.0
      - ''
    description: VDOM link name (maximum = 11 characters).
  vcluster:
    type: enum
    raw_type: string
    choices:
    - vcluster1
    - vcluster2
    version_ranges:
    - - v6.0.0
      - ''
    description: Virtual cluster.
  type:
    type: enum
    raw_type: string
    choices:
    - ppp
    - ethernet
    version_ranges:
    - - v6.0.0
      - ''
    description: 'VDOM link type: PPP or Ethernet.'
