id: system.sov-sase
version: 7.6.7
source_object: fortios_system_sov_sase
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_system_sov_sase.py
root_type: object
attributes:
  status:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.6.5
      - ''
    description: Enable/disable Sovereign SASE.
