id: system.session-helper
version: 7.6.7
source_object: fortios_system_session_helper
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_system_session_helper.py
root_type: list
attributes:
  id:
    type: integer
    raw_type: integer
    required: true
    version_ranges:
    - - v6.0.0
      - ''
    description: Session helper ID. see <a href='#notes'>Notes</a>.
  name:
    type: enum
    raw_type: string
    choices:
    - ftp
    - tftp
    - ras
    - h323
    - tns
    - mms
    - sip
    - pptp
    - rtsp
    - dns-udp
    - dns-tcp
    - pmap
    - rsh
    - dcerpc
    - mgcp
    - gtp-c
    - gtp-u
    - gtp-b
    - pfcp
    version_ranges:
    - - v6.0.0
      - ''
    description: Helper name.
  protocol:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Protocol number.
  port:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Protocol port.
