id: system.snmp.rmon-stat
version: 7.6.7
source_object: fortios_system_snmp_rmon_stat
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_system_snmp_rmon_stat.py
root_type: list
attributes:
  id:
    type: integer
    raw_type: integer
    required: true
    version_ranges:
    - - v7.6.0
      - ''
    description: RMON Ethernet statistics entry ID. see <a href='#notes'>Notes</a>.
  source:
    type: string
    raw_type: string
    version_ranges:
    - - v7.6.0
      - ''
    description: Data source of the Ethernet statistics entry. Source system.interface.name.
    references:
    - system.interface.name
  owner:
    type: string
    raw_type: string
    version_ranges:
    - - v7.6.0
      - ''
    description: Owner of the Ethernet statistics entry.
