id: system.password-policy-guest-admin
version: 7.6.7
source_object: fortios_system_password_policy_guest_admin
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_system_password_policy_guest_admin.py
root_type: object
attributes:
  status:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable setting a password policy for locally defined administrator passwords and IPsec VPN pre-shared
      keys.
  apply_to:
    type: enum
    raw_type: list
    choices:
    - guest-admin-password
    multiple_values: true
    elements: str
    version_ranges:
    - - v6.0.0
      - ''
    description: Guest administrator to which this password policy applies.
  minimum_length:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Minimum password length (12 - 128).
  min_lower_case_letter:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Minimum number of lowercase characters in password (0 - 128).
  min_upper_case_letter:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Minimum number of uppercase characters in password (0 - 128).
  min_non_alphanumeric:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Minimum number of non-alphanumeric characters in password (0 - 128).
  min_number:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Minimum number of numeric characters in password (0 - 128).
  expire_status:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable password expiration.
  expire_day:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Number of days after which passwords expire (1 - 999 days).
  reuse_password:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable reuse of password.
  reuse_password_limit:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.6.0
      - ''
    description: Number of times passwords can be reused (0 - 20).
