id: system.ipsec-aggregate
version: 7.6.7
source_object: fortios_system_ipsec_aggregate
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_system_ipsec_aggregate.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v6.2.0
      - ''
    description: IPsec aggregate name.
  member:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.2.0
      - ''
    description: Member tunnels of the aggregate.
    children:
      tunnel_name:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v6.2.0
          - ''
        description: Tunnel name. Source vpn.ipsec.phase1-interface.name.
        references:
        - vpn.ipsec.phase1-interface.name
  algorithm:
    type: enum
    raw_type: string
    choices:
    - L3
    - L4
    - round-robin
    - redundant
    - weighted-round-robin
    version_ranges:
    - - v6.2.0
      - ''
    description: Frame distribution algorithm.
