id: system.pcp-server
version: 7.6.7
source_object: fortios_system_pcp_server
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_system_pcp_server.py
root_type: object
attributes:
  status:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.4.0
      - ''
    description: Enable/disable PCP server.
  pools:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v7.4.0
      - ''
    description: Configure PCP pools.
    children:
      name:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v7.4.0
          - ''
        description: PCP pool name.
      description:
        type: string
        raw_type: string
        version_ranges:
        - - v7.4.0
          - ''
        description: Description.
      id:
        type: integer
        raw_type: integer
        version_ranges:
        - - v7.4.0
          - ''
        description: ID.
      client_subnet:
        type: list
        raw_type: list
        elements: dict
        version_ranges:
        - - v7.4.0
          - ''
        description: Subnets from which PCP requests are accepted.
        children:
          subnet:
            type: string
            raw_type: string
            required: true
            version_ranges:
            - - v7.4.0
              - ''
            description: Client subnets.
      ext_intf:
        type: string
        raw_type: string
        version_ranges:
        - - v7.4.0
          - ''
        description: External interface name. Source system.interface.name.
        references:
        - system.interface.name
      arp_reply:
        type: enum
        raw_type: string
        choices:
        - disable
        - enable
        version_ranges:
        - - v7.4.0
          - ''
        description: Enable to respond to ARP requests for external IP .
      extip:
        type: string
        raw_type: string
        version_ranges:
        - - v7.4.0
          - ''
        description: IP address or address range on the external interface that you want to map to an address on the internal
          network.
      extport:
        type: string
        raw_type: string
        version_ranges:
        - - v7.4.0
          - ''
        description: Incoming port number range that you want to map to a port number on the internal network.
      minimal_lifetime:
        type: integer
        raw_type: integer
        version_ranges:
        - - v7.4.0
          - ''
        description: Minimal lifetime of a PCP mapping in seconds (60 - 300).
      maximal_lifetime:
        type: integer
        raw_type: integer
        version_ranges:
        - - v7.4.0
          - ''
        description: Maximal lifetime of a PCP mapping in seconds (3600 - 604800).
      client_mapping_limit:
        type: integer
        raw_type: integer
        version_ranges:
        - - v7.4.0
          - ''
        description: Mapping limit per client (0 - 65535).
      mapping_filter_limit:
        type: integer
        raw_type: integer
        version_ranges:
        - - v7.4.0
          - ''
        description: Filter limit per mapping (0 - 5).
      allow_opcode:
        type: enum
        raw_type: list
        choices:
        - map
        - peer
        - announce
        multiple_values: true
        elements: str
        version_ranges:
        - - v7.4.0
          - ''
        description: Allowed PCP opcode.
      third_party:
        type: enum
        raw_type: string
        choices:
        - allow
        - disallow
        version_ranges:
        - - v7.4.0
          - ''
        description: Allow/disallow third party option.
      third_party_subnet:
        type: list
        raw_type: list
        elements: dict
        version_ranges:
        - - v7.4.0
          - ''
        description: Subnets from which third party requests are accepted.
        children:
          subnet:
            type: string
            raw_type: string
            required: true
            version_ranges:
            - - v7.4.0
              - ''
            description: Third party subnets.
      multicast_announcement:
        type: enum
        raw_type: string
        choices:
        - enable
        - disable
        version_ranges:
        - - v7.4.0
          - ''
        description: Enable/disable multicast announcements.
      announcement_count:
        type: integer
        raw_type: integer
        version_ranges:
        - - v7.4.0
          - ''
        description: Number of multicast announcements.
      intl_intf:
        type: list
        raw_type: list
        elements: dict
        version_ranges:
        - - v7.4.0
          - ''
        description: Internal interface name.
        children:
          interface_name:
            type: string
            raw_type: string
            required: true
            version_ranges:
            - - v7.4.0
              - ''
            description: Interface name. Source system.interface.name.
            references:
            - system.interface.name
      recycle_delay:
        type: integer
        raw_type: integer
        version_ranges:
        - - v7.4.0
          - ''
        description: Minimum delay (in seconds) the PCP Server will wait before recycling mappings that have expired (0 -
          3600).
