id: system.vdom-radius-server
version: 7.6.7
source_object: fortios_system_vdom_radius_server
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_system_vdom_radius_server.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v6.0.0
      - ''
    description: Name of the VDOM that you are adding the RADIUS server to. Source system.vdom.name.
    references:
    - system.vdom.name
  status:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable the RSSO RADIUS server for this VDOM.
  radius_server_vdom:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Use this option to select another VDOM containing a VDOM RSSO RADIUS server to use for the current VDOM.
      Source system.vdom.name.
    references:
    - system.vdom.name
