id: user.local
version: 7.6.7
source_object: fortios_user_local
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_user_local.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v6.0.0
      - ''
    description: Local user name.
  status:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable allowing the local user to authenticate with the FortiGate unit.
  type:
    type: enum
    raw_type: string
    choices:
    - password
    - radius
    - tacacs+
    - ldap
    - saml
    version_ranges:
    - - v6.0.0
      - ''
    description: Authentication method.
  passwd:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: User"s password.
  ldap_server:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Name of LDAP server with which the user must authenticate. Source user.ldap.name.
    references:
    - user.ldap.name
  radius_server:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Name of RADIUS server with which the user must authenticate. Source user.radius.name.
    references:
    - user.radius.name
  saml_server:
    type: string
    raw_type: string
    version_ranges:
    - - v7.6.3
      - ''
    description: Name of SAML server with which the user must authenticate. Source user.saml.name.
    references:
    - user.saml.name
  two_factor:
    type: enum
    raw_type: string
    choices:
    - disable
    - fortitoken
    - fortitoken-cloud
    - email
    - sms
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable two-factor authentication.
  two_factor_authentication:
    type: enum
    raw_type: string
    choices:
    - fortitoken
    - email
    - sms
    version_ranges:
    - - v6.2.0
      - v6.2.0
    - - v6.2.5
      - ''
    description: Authentication method by FortiToken Cloud.
  two_factor_notification:
    type: enum
    raw_type: string
    choices:
    - email
    - sms
    version_ranges:
    - - v6.2.0
      - v6.2.0
    - - v6.2.5
      - ''
    description: Notification method for user activation by FortiToken Cloud.
  fortitoken:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Two-factor recipient"s FortiToken serial number. Source user.fortitoken.serial-number.
    references:
    - user.fortitoken.serial-number
  email_to:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Two-factor recipient"s email address.
  sms_server:
    type: enum
    raw_type: string
    choices:
    - fortiguard
    - custom
    version_ranges:
    - - v6.0.0
      - ''
    description: Send SMS through FortiGuard or other external server.
  sms_custom_server:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Two-factor recipient"s SMS server. Source system.sms-server.name.
    references:
    - system.sms-server.name
  sms_phone:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Two-factor recipient"s mobile phone number.
  passwd_policy:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Password policy to apply to this user, as defined in config user password-policy. Source user.password-policy.name.
    references:
    - user.password-policy.name
  passwd_time:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Time of the last password update.
  authtimeout:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Time in minutes before the authentication timeout for a user is reached.
  workstation:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Name of the remote user workstation, if you want to limit the user to authenticate only from a particular
      workstation.
  auth_concurrent_override:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable overriding the policy-auth-concurrent under config system global.
  auth_concurrent_value:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Maximum number of concurrent logins permitted from the same user.
  ppk_secret:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: IKEv2 Postquantum Preshared Key (ASCII string or hexadecimal encoded with a leading 0x).
  ppk_identity:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: IKEv2 Postquantum Preshared Key Identity.
  qkd_profile:
    type: string
    raw_type: string
    version_ranges:
    - - v7.4.2
      - ''
    description: Quantum Key Distribution (QKD) profile. Source vpn.qkd.name.
    references:
    - vpn.qkd.name
  username_sensitivity:
    type: enum
    raw_type: string
    choices:
    - disable
    - enable
    version_ranges:
    - - v7.0.1
      - ''
    description: Enable/disable case and accent sensitivity when performing username matching (accents are stripped and case
      is ignored when disabled).
  tacacs_plus_server:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Name of TACACS+ server with which the user must authenticate. Source user.tacacs+.name.
