id: user.peergrp
version: 7.6.7
source_object: fortios_user_peergrp
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_user_peergrp.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v6.0.0
      - ''
    description: Peer group name.
  member:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: Peer group members.
    children:
      name:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: Peer group member name. Source user.peer.name.
        references:
        - user.peer.name
