id: user.password-policy
version: 7.6.7
source_object: fortios_user_password_policy
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_user_password_policy.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v6.0.0
      - ''
    description: Password policy name.
  expire_status:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.4.1
      - ''
    description: Enable/disable password expiration.
  expire_days:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Time in days before the user"s password expires.
  warn_days:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Time in days before a password expiration warning message is displayed to the user upon login.
  expired_password_renewal:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.2.0
      - ''
    description: Enable/disable renewal of a password that already is expired.
  minimum_length:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.4.1
      - ''
    description: Minimum password length (8 - 128).
  min_lower_case_letter:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.4.1
      - ''
    description: Minimum number of lowercase characters in password (0 - 128).
  min_upper_case_letter:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.4.1
      - ''
    description: Minimum number of uppercase characters in password (0 - 128).
  min_non_alphanumeric:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.4.1
      - ''
    description: Minimum number of non-alphanumeric characters in password (0 - 128).
  min_number:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.4.1
      - ''
    description: Minimum number of numeric characters in password (0 - 128).
  min_change_characters:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.4.1
      - ''
    description: Minimum number of unique characters in new password which do not exist in old password (0 - 128).
  reuse_password:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.4.1
      - ''
    description: Enable/disable reuse of password. If both reuse-password and min-change-characters are enabled, min-change-characters
      overrides.
  reuse_password_limit:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.6.0
      - ''
    description: Number of times passwords can be reused (0 - 20).
