id: user.domain-controller
version: 7.6.7
source_object: fortios_user_domain_controller
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_user_domain_controller.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v6.0.0
      - ''
    description: Domain controller entry name.
  ad_mode:
    type: enum
    raw_type: string
    choices:
    - none
    - ds
    - lds
    version_ranges:
    - - v7.0.0
      - ''
    description: Set Active Directory mode.
  hostname:
    type: string
    raw_type: string
    version_ranges:
    - - v7.0.0
      - ''
    description: Hostname of the server to connect to.
  username:
    type: string
    raw_type: string
    version_ranges:
    - - v7.0.0
      - ''
    description: User name to sign in with. Must have proper permissions for service.
  password:
    type: string
    raw_type: string
    version_ranges:
    - - v7.0.0
      - ''
    description: Password for specified username.
  ip_address:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Domain controller IPv4 address.
  ip6:
    type: string
    raw_type: string
    version_ranges:
    - - v7.0.0
      - ''
    description: Domain controller IPv6 address.
  port:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Port to be used for communication with the domain controller .
  source_ip_address:
    type: string
    raw_type: string
    version_ranges:
    - - v7.0.0
      - ''
    description: FortiGate IPv4 address to be used for communication with the domain controller.
  source_ip6:
    type: string
    raw_type: string
    version_ranges:
    - - v7.0.0
      - ''
    description: FortiGate IPv6 address to be used for communication with the domain controller.
  source_port:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.0.0
      - ''
    description: Source port to be used for communication with the domain controller.
  interface_select_method:
    type: enum
    raw_type: string
    choices:
    - auto
    - sdwan
    - specify
    version_ranges:
    - - v7.0.0
      - ''
    description: Specify how to select outgoing interface to reach server.
  interface:
    type: string
    raw_type: string
    version_ranges:
    - - v7.0.0
      - ''
    description: Specify outgoing interface to reach server. Source system.interface.name.
    references:
    - system.interface.name
  extra_server:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.2.0
      - ''
    description: Extra servers.
    children:
      id:
        type: integer
        raw_type: integer
        required: true
        version_ranges:
        - - v6.2.0
          - ''
        description: Server ID. see <a href='#notes'>Notes</a>.
      ip_address:
        type: string
        raw_type: string
        version_ranges:
        - - v6.2.0
          - ''
        description: Domain controller IP address.
      port:
        type: integer
        raw_type: integer
        version_ranges:
        - - v6.2.0
          - ''
        description: Port to be used for communication with the domain controller .
      source_ip_address:
        type: string
        raw_type: string
        version_ranges:
        - - v7.0.0
          - ''
        description: FortiGate IPv4 address to be used for communication with the domain controller.
      source_port:
        type: integer
        raw_type: integer
        version_ranges:
        - - v7.0.0
          - ''
        description: Source port to be used for communication with the domain controller.
  domain_name:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Domain DNS name.
  replication_port:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.0.0
      - ''
    description: Port to be used for communication with the domain controller for replication service. Port number 0 indicates
      automatic discovery.
  ldap_server:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: LDAP server name(s). Source user.ldap.name.
    references:
    - user.ldap.name
    children:
      name:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v6.4.4
          - ''
        description: LDAP server name. Source user.ldap.name.
        references:
        - user.ldap.name
  change_detection:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.4.0
      - ''
    description: Enable/disable detection of a configuration change in the Active Directory server.
  change_detection_period:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.4.0
      - ''
    description: Minutes to detect a configuration change in the Active Directory server (5 - 10080 minutes (7 days)).
  dns_srv_lookup:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.0.0
      - ''
    description: Enable/disable DNS service lookup.
  adlds_dn:
    type: string
    raw_type: string
    version_ranges:
    - - v7.0.0
      - ''
    description: AD LDS distinguished name.
  adlds_ip_address:
    type: string
    raw_type: string
    version_ranges:
    - - v7.0.0
      - ''
    description: AD LDS IPv4 address.
  adlds_ip6:
    type: string
    raw_type: string
    version_ranges:
    - - v7.0.0
      - ''
    description: AD LDS IPv6 address.
  adlds_port:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.0.0
      - ''
    description: Port number of AD LDS service .
