id: videofilter.profile
version: 7.6.7
source_object: fortios_videofilter_profile
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_videofilter_profile.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v7.0.0
      - ''
    description: Name.
  comment:
    type: string
    raw_type: string
    version_ranges:
    - - v7.0.0
      - ''
    description: Comment.
  filters:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v7.4.2
      - ''
    description: YouTube filter entries.
    children:
      id:
        type: integer
        raw_type: integer
        required: true
        version_ranges:
        - - v7.4.2
          - ''
        description: ID. see <a href='#notes'>Notes</a>.
      comment:
        type: string
        raw_type: string
        version_ranges:
        - - v7.4.2
          - ''
        description: Comment.
      type:
        type: enum
        raw_type: string
        choices:
        - category
        - channel
        - title
        - description
        version_ranges:
        - - v7.4.2
          - ''
        description: Filter type.
      keyword:
        type: integer
        raw_type: integer
        version_ranges:
        - - v7.4.2
          - ''
        description: Video filter keyword ID. Source videofilter.keyword.id.
        references:
        - videofilter.keyword.id
      category:
        type: string
        raw_type: string
        version_ranges:
        - - v7.4.2
          - ''
        description: FortiGuard category ID.
      channel:
        type: string
        raw_type: string
        version_ranges:
        - - v7.4.2
          - ''
        description: Channel ID.
      action:
        type: enum
        raw_type: string
        choices:
        - allow
        - monitor
        - block
        version_ranges:
        - - v7.4.2
          - ''
        description: Video filter action.
      log:
        type: enum
        raw_type: string
        choices:
        - enable
        - disable
        version_ranges:
        - - v7.4.2
          - ''
        description: Enable/disable logging.
  replacemsg_group:
    type: string
    raw_type: string
    version_ranges:
    - - v7.0.1
      - ''
    description: Replacement message group. Source system.replacemsg-group.name.
    references:
    - system.replacemsg-group.name
  youtube:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.0.0
      - v7.6.7
    description: Enable/disable YouTube video source.
  vimeo:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.0.0
      - v7.6.7
    description: Enable/disable Vimeo video source.
  dailymotion:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.0.0
      - v7.6.7
    description: Enable/disable Dailymotion video source.
