id: vpn.l2tp
version: 7.6.7
source_object: fortios_vpn_l2tp
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_vpn_l2tp.py
root_type: object
attributes:
  status:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable FortiGate as a L2TP gateway.
  eip:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: End IP.
  sip:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Start IP.
  usrgrp:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: User group. Source user.group.name.
    references:
    - user.group.name
  enforce_ipsec:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable IPsec enforcement.
  lcp_echo_interval:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.4.0
      - v6.4.0
    - - v6.4.4
      - ''
    description: Time in seconds between PPPoE Link Control Protocol (LCP) echo requests.
  lcp_max_echo_fails:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.4.0
      - v6.4.0
    - - v6.4.4
      - ''
    description: Maximum number of missed LCP echo messages before disconnect.
  hello_interval:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.0.1
      - ''
    description: L2TP hello message interval in seconds (0 - 3600 sec).
  compress:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.2.0
      - v6.2.0
    - - v6.2.5
      - ''
    description: Enable/disable data compression.
