id: vpn.certificate.ocsp-server
version: 7.6.7
source_object: fortios_vpn_certificate_ocsp_server
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_vpn_certificate_ocsp_server.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v6.0.0
      - ''
    description: OCSP server entry name.
  url:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: OCSP server URL.
  cert:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: OCSP server certificate. Source vpn.certificate.remote.name vpn.certificate.ca.name.
    references:
    - vpn.certificate.ca.name
    - vpn.certificate.remote.name
  secondary_url:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Secondary OCSP server URL.
  secondary_cert:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Secondary OCSP server certificate. Source vpn.certificate.remote.name vpn.certificate.ca.name.
    references:
    - vpn.certificate.ca.name
    - vpn.certificate.remote.name
  unavail_action:
    type: enum
    raw_type: string
    choices:
    - revoke
    - ignore
    version_ranges:
    - - v6.0.0
      - ''
    description: Action when server is unavailable (revoke the certificate or ignore the result of the check).
  source_ip:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Source IP address for dynamic AIA and OCSP queries.
