id: vpn.ssl.settings
version: 7.6.7
source_object: fortios_vpn_ssl_settings
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_vpn_ssl_settings.py
root_type: object
attributes:
  status:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.0.1
      - ''
    description: Enable/disable Agentless VPN.
  reqclientcert:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable to require client certificates for all Agentless VPN users.
  user_peer:
    type: string
    raw_type: string
    version_ranges:
    - - v6.2.0
      - ''
    description: Name of user peer. Source user.peer.name.
    references:
    - user.peer.name
  ssl_max_proto_ver:
    type: enum
    raw_type: string
    choices:
    - tls1-0
    - tls1-1
    - tls1-2
    - tls1-3
    version_ranges:
    - - v6.2.0
      - ''
    description: SSL maximum protocol version.
  ssl_min_proto_ver:
    type: enum
    raw_type: string
    choices:
    - tls1-0
    - tls1-1
    - tls1-2
    - tls1-3
    version_ranges:
    - - v6.2.0
      - ''
    description: SSL minimum protocol version.
  banned_cipher:
    type: enum
    raw_type: list
    choices:
    - RSA
    - DHE
    - ECDHE
    - DSS
    - ECDSA
    - AES
    - AESGCM
    - CAMELLIA
    - 3DES
    - SHA1
    - SHA256
    - SHA384
    - STATIC
    - CHACHA20
    - ARIA
    - AESCCM
    multiple_values: true
    elements: str
    version_ranges:
    - - v6.0.0
      - ''
    description: Select one or more cipher technologies that cannot be used in Agentless VPN negotiations. Only applies to
      TLS 1.2 and below.
  ciphersuite:
    type: enum
    raw_type: list
    choices:
    - TLS-AES-128-GCM-SHA256
    - TLS-AES-256-GCM-SHA384
    - TLS-CHACHA20-POLY1305-SHA256
    - TLS-AES-128-CCM-SHA256
    - TLS-AES-128-CCM-8-SHA256
    multiple_values: true
    elements: str
    version_ranges:
    - - v7.0.0
      - ''
    description: Select one or more TLS 1.3 ciphersuites to enable. Does not affect ciphers in TLS 1.2 and below. At least
      one must be enabled. To disable all, set ssl-max-proto-ver to tls1-2 or below.
  ssl_insert_empty_fragment:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable insertion of empty fragment.
  https_redirect:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable redirect of port 80 to Agentless VPN port.
  x_content_type_options:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Add HTTP X-Content-Type-Options header.
  ssl_client_renegotiation:
    type: enum
    raw_type: string
    choices:
    - disable
    - enable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable to allow client renegotiation by the server if the tunnel goes down.
  force_two_factor_auth:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable only PKI users with two-factor authentication for Agentless VPNs.
  unsafe_legacy_renegotiation:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable unsafe legacy re-negotiation.
  servercert:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Name of the server certificate to be used for Agentless VPNs. Source vpn.certificate.local.name.
    references:
    - vpn.certificate.local.name
  algorithm:
    type: enum
    raw_type: string
    choices:
    - high
    - medium
    - default
    - low
    version_ranges:
    - - v6.0.0
      - ''
    description: Force the Agentless VPN security level. High allows only high. Medium allows medium and high. Low allows
      any.
  tls_groups:
    type: enum
    raw_type: list
    choices:
    - P-521
    - P-384
    - P-256
    - ML-KEM512
    - ML-KEM768
    - ML-KEM1024
    - P-384-MLKEM1024
    - P-256-MLKEM768
    - X25519-MLKEM768
    - X448
    - X25519
    - FFDHE2048
    - FFDHE3072
    - FFDHE4096
    - FFDHE6144
    - FFDHE8192
    multiple_values: true
    elements: str
    version_ranges:
    - - v7.6.5
      - ''
    description: Configure the supported groups for TLS negotiation.
  idle_timeout:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Agentless VPN disconnects if idle for specified time in seconds.
  auth_timeout:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Agentless VPN authentication timeout (1 - 259200 sec (3 days), 0 for no timeout).
  login_attempt_limit:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Agentless VPN maximum login attempt times before block (0 - 10).
  login_block_time:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Time for which a user is blocked from logging in after too many failed login attempts (0 - 86400 sec).
  login_timeout:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Agentless VPN maximum login timeout (10 - 180 sec).
  dtls_hello_timeout:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: SSLVPN maximum DTLS hello timeout (10 - 60 sec).
  dtls_heartbeat_idle_timeout:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.4.0
      - ''
    description: Idle timeout before DTLS heartbeat is sent.
  dtls_heartbeat_interval:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.4.0
      - ''
    description: Interval between DTLS heartbeat.
  dtls_heartbeat_fail_count:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.4.0
      - ''
    description: Number of missing heartbeats before the connection is considered dropped.
  dns_suffix:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: DNS suffix used for Agentless VPN clients.
  url_obscuration:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable to obscure the host name of the URL of the web browser display.
  http_compression:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable to allow HTTP compression over Agentless VPN connections.
  http_only_cookie:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable Agentless VPN support for HttpOnly cookies.
  deflate_compression_level:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Compression level (0~9).
  deflate_min_data_size:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Minimum amount of data that triggers compression (200 - 65535 bytes).
  port:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Agentless VPN access port (1 - 65535).
  port_precedence:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable, Enable means that if Agentless VPN connections are allowed on an interface admin GUI connections
      are blocked on that interface.
  header_x_forwarded_for:
    type: enum
    raw_type: string
    choices:
    - pass
    - add
    - remove
    version_ranges:
    - - v6.0.0
      - ''
    description: Forward the same, add, or remove HTTP header.
  source_interface:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: Agentless VPN source interface of incoming traffic.
    children:
      name:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: Interface name. Source system.interface.name system.zone.name.
        references:
        - system.interface.name
        - system.zone.name
  source_address:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: Source address of incoming traffic.
    children:
      name:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: Address name. Source firewall.address.name firewall.addrgrp.name system.external-resource.name.
        references:
        - firewall.address.name
        - firewall.addrgrp.name
        - system.external-resource.name
  source_address_negate:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable negated source address match.
  source_address6:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: IPv6 source address of incoming traffic.
    children:
      name:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: IPv6 address name. Source firewall.address6.name firewall.addrgrp6.name system.external-resource.name.
        references:
        - firewall.address6.name
        - firewall.addrgrp6.name
        - system.external-resource.name
  source_address6_negate:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable negated source IPv6 address match.
  default_portal:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Default Agentless VPN portal. Source vpn.ssl.web.portal.name.
    references:
    - vpn.ssl.web.portal.name
  authentication_rule:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: Authentication rule for Agentless VPN.
    children:
      id:
        type: integer
        raw_type: integer
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: ID (0 - 4294967295). see <a href='#notes'>Notes</a>.
      source_interface:
        type: list
        raw_type: list
        elements: dict
        version_ranges:
        - - v6.0.0
          - ''
        description: Agentless VPN source interface of incoming traffic.
        children:
          name:
            type: string
            raw_type: string
            required: true
            version_ranges:
            - - v6.0.0
              - ''
            description: Interface name. Source system.interface.name system.zone.name.
            references:
            - system.interface.name
            - system.zone.name
      source_address:
        type: list
        raw_type: list
        elements: dict
        version_ranges:
        - - v6.0.0
          - ''
        description: Source address of incoming traffic.
        children:
          name:
            type: string
            raw_type: string
            required: true
            version_ranges:
            - - v6.0.0
              - ''
            description: Address name. Source firewall.address.name firewall.addrgrp.name system.external-resource.name.
            references:
            - firewall.address.name
            - firewall.addrgrp.name
            - system.external-resource.name
      source_address_negate:
        type: enum
        raw_type: string
        choices:
        - enable
        - disable
        version_ranges:
        - - v6.0.0
          - ''
        description: Enable/disable negated source address match.
      source_address6:
        type: list
        raw_type: list
        elements: dict
        version_ranges:
        - - v6.0.0
          - ''
        description: IPv6 source address of incoming traffic.
        children:
          name:
            type: string
            raw_type: string
            required: true
            version_ranges:
            - - v6.0.0
              - ''
            description: IPv6 address name. Source firewall.address6.name firewall.addrgrp6.name system.external-resource.name.
            references:
            - firewall.address6.name
            - firewall.addrgrp6.name
            - system.external-resource.name
      source_address6_negate:
        type: enum
        raw_type: string
        choices:
        - enable
        - disable
        version_ranges:
        - - v6.0.0
          - ''
        description: Enable/disable negated source IPv6 address match.
      users:
        type: list
        raw_type: list
        elements: dict
        version_ranges:
        - - v6.0.0
          - ''
        description: User name.
        children:
          name:
            type: string
            raw_type: string
            required: true
            version_ranges:
            - - v6.0.0
              - ''
            description: User name. Source user.local.name.
            references:
            - user.local.name
      groups:
        type: list
        raw_type: list
        elements: dict
        version_ranges:
        - - v6.0.0
          - ''
        description: User groups.
        children:
          name:
            type: string
            raw_type: string
            required: true
            version_ranges:
            - - v6.0.0
              - ''
            description: Group name. Source user.group.name.
            references:
            - user.group.name
      portal:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Agentless VPN portal. Source vpn.ssl.web.portal.name.
        references:
        - vpn.ssl.web.portal.name
      realm:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Agentless VPN realm. Source vpn.ssl.web.realm.url-path.
        references:
        - vpn.ssl.web.realm.url-path
      client_cert:
        type: enum
        raw_type: string
        choices:
        - enable
        - disable
        version_ranges:
        - - v6.0.0
          - ''
        description: Enable/disable Agentless VPN client certificate restrictive.
      user_peer:
        type: string
        raw_type: string
        version_ranges:
        - - v6.2.0
          - ''
        description: Name of user peer. Source user.peer.name.
        references:
        - user.peer.name
      cipher:
        type: enum
        raw_type: string
        choices:
        - any
        - high
        - medium
        version_ranges:
        - - v6.0.0
          - ''
        description: Agentless VPN cipher strength.
      auth:
        type: enum
        raw_type: string
        choices:
        - any
        - local
        - radius
        - tacacs+
        - ldap
        - peer
        version_ranges:
        - - v6.0.0
          - ''
        description: Agentless VPN authentication method restriction.
  browser_language_detection:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.2.0
      - ''
    description: Enable/disable overriding the configured system language based on the preferred language of the browser.
  check_referer:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable verification of referer field in HTTP request header.
  http_request_header_timeout:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Agentless VPN session is disconnected if an HTTP request header is not received within this time (1 - 60
      sec).
  http_request_body_timeout:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Agentless VPN session is disconnected if an HTTP request body is not received within this time (1 - 60 sec).
  auth_session_check_source_ip:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.2.0
      - ''
    description: Enable/disable checking of source IP for authentication session.
  hsts_include_subdomains:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.2.0
      - ''
    description: Add HSTS includeSubDomains response header.
  transform_backward_slashes:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.4.0
      - ''
    description: Transform backward slashes to forward slashes in URLs.
  encode_2f_sequence:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.2.0
      - v6.2.0
    - - v6.2.5
      - ''
    description: Encode 2F sequence to forward slash in URLs.
  encrypt_and_store_password:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.4.0
      - ''
    description: Encrypt and store user passwords for Agentless VPN web sessions.
  client_sigalgs:
    type: enum
    raw_type: string
    choices:
    - no-rsa-pss
    - all
    version_ranges:
    - - v6.4.4
      - ''
    description: Set signature algorithms related to client authentication. Affects TLS version <= 1.2 only.
  dual_stack_mode:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.0.0
      - ''
    description: 'Agentless web mode: support IPv4 and IPv6 bookmarks in the portal.'
  server_hostname:
    type: string
    raw_type: string
    version_ranges:
    - - v7.4.0
      - ''
    description: Server hostname for HTTPS. When set, will be used for Agentless VPN web proxy host header for any redirection.
  remote_https_cert_check:
    type: enum
    raw_type: string
    choices:
    - no-check
    - warn-on-error
    - reject-on-error
    version_ranges:
    - - v7.6.5
      - ''
    description: Configure how the FortiGate unit checks and responds to the remote HTTPS server"s certificate .
