id: vpn.ipsec.phase2-interface
version: 7.6.7
source_object: fortios_vpn_ipsec_phase2_interface
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_vpn_ipsec_phase2_interface.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v6.0.0
      - ''
    description: IPsec tunnel name.
  phase1name:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Phase 1 determines the options required for phase 2. Source vpn.ipsec.phase1-interface.name.
    references:
    - vpn.ipsec.phase1-interface.name
  dhcp_ipsec:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable DHCP-IPsec.
  proposal:
    type: enum
    raw_type: list
    choices:
    - null-md5
    - null-sha1
    - null-sha256
    - null-sha384
    - null-sha512
    - des-null
    - des-md5
    - des-sha1
    - des-sha256
    - des-sha384
    - des-sha512
    - 3des-null
    - 3des-md5
    - 3des-sha1
    - 3des-sha256
    - 3des-sha384
    - 3des-sha512
    - aes128-null
    - aes128-md5
    - aes128-sha1
    - aes128-sha256
    - aes128-sha384
    - aes128-sha512
    - aes128gcm
    - aes192-null
    - aes192-md5
    - aes192-sha1
    - aes192-sha256
    - aes192-sha384
    - aes192-sha512
    - aes256-null
    - aes256-md5
    - aes256-sha1
    - aes256-sha256
    - aes256-sha384
    - aes256-sha512
    - aes256gcm
    - chacha20poly1305
    - aria128-null
    - aria128-md5
    - aria128-sha1
    - aria128-sha256
    - aria128-sha384
    - aria128-sha512
    - aria192-null
    - aria192-md5
    - aria192-sha1
    - aria192-sha256
    - aria192-sha384
    - aria192-sha512
    - aria256-null
    - aria256-md5
    - aria256-sha1
    - aria256-sha256
    - aria256-sha384
    - aria256-sha512
    - seed-null
    - seed-md5
    - seed-sha1
    - seed-sha256
    - seed-sha384
    - seed-sha512
    multiple_values: true
    elements: str
    version_ranges:
    - - v6.0.0
      - ''
    description: Phase2 proposal.
  pfs:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable PFS feature.
  dhgrp:
    type: enum
    raw_type: list
    choices:
    - '1'
    - '2'
    - '5'
    - '14'
    - '15'
    - '16'
    - '17'
    - '18'
    - '19'
    - '20'
    - '21'
    - '27'
    - '28'
    - '29'
    - '30'
    - '31'
    - '32'
    multiple_values: true
    elements: str
    version_ranges:
    - - v6.0.0
      - ''
    description: Phase2 DH group.
  addke1:
    type: enum
    raw_type: list
    choices:
    - none
    - ml-kem-512
    - ml-kem-768
    - ml-kem-1024
    - kyber512
    - kyber768
    - kyber1024
    - frodo-l1
    - frodo-l3
    - frodo-l5
    - bike-l1
    - bike-l3
    - bike-l5
    - hqc128
    - hqc192
    - hqc256
    multiple_values: true
    elements: str
    version_ranges:
    - - v7.6.0
      - ''
    description: phase2 ADDKE1 group.
  addke2:
    type: enum
    raw_type: list
    choices:
    - none
    - ml-kem-512
    - ml-kem-768
    - ml-kem-1024
    - kyber512
    - kyber768
    - kyber1024
    - frodo-l1
    - frodo-l3
    - frodo-l5
    - bike-l1
    - bike-l3
    - bike-l5
    - hqc128
    - hqc192
    - hqc256
    multiple_values: true
    elements: str
    version_ranges:
    - - v7.6.0
      - ''
    description: phase2 ADDKE2 group.
  addke3:
    type: enum
    raw_type: list
    choices:
    - none
    - ml-kem-512
    - ml-kem-768
    - ml-kem-1024
    - kyber512
    - kyber768
    - kyber1024
    - frodo-l1
    - frodo-l3
    - frodo-l5
    - bike-l1
    - bike-l3
    - bike-l5
    - hqc128
    - hqc192
    - hqc256
    multiple_values: true
    elements: str
    version_ranges:
    - - v7.6.0
      - ''
    description: phase2 ADDKE3 group.
  addke4:
    type: enum
    raw_type: list
    choices:
    - none
    - ml-kem-512
    - ml-kem-768
    - ml-kem-1024
    - kyber512
    - kyber768
    - kyber1024
    - frodo-l1
    - frodo-l3
    - frodo-l5
    - bike-l1
    - bike-l3
    - bike-l5
    - hqc128
    - hqc192
    - hqc256
    multiple_values: true
    elements: str
    version_ranges:
    - - v7.6.0
      - ''
    description: phase2 ADDKE4 group.
  addke5:
    type: enum
    raw_type: list
    choices:
    - none
    - ml-kem-512
    - ml-kem-768
    - ml-kem-1024
    - kyber512
    - kyber768
    - kyber1024
    - frodo-l1
    - frodo-l3
    - frodo-l5
    - bike-l1
    - bike-l3
    - bike-l5
    - hqc128
    - hqc192
    - hqc256
    multiple_values: true
    elements: str
    version_ranges:
    - - v7.6.0
      - ''
    description: phase2 ADDKE5 group.
  addke6:
    type: enum
    raw_type: list
    choices:
    - none
    - ml-kem-512
    - ml-kem-768
    - ml-kem-1024
    - kyber512
    - kyber768
    - kyber1024
    - frodo-l1
    - frodo-l3
    - frodo-l5
    - bike-l1
    - bike-l3
    - bike-l5
    - hqc128
    - hqc192
    - hqc256
    multiple_values: true
    elements: str
    version_ranges:
    - - v7.6.0
      - ''
    description: phase2 ADDKE6 group.
  addke7:
    type: enum
    raw_type: list
    choices:
    - none
    - ml-kem-512
    - ml-kem-768
    - ml-kem-1024
    - kyber512
    - kyber768
    - kyber1024
    - frodo-l1
    - frodo-l3
    - frodo-l5
    - bike-l1
    - bike-l3
    - bike-l5
    - hqc128
    - hqc192
    - hqc256
    multiple_values: true
    elements: str
    version_ranges:
    - - v7.6.0
      - ''
    description: phase2 ADDKE7 group.
  replay:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable replay detection.
  keepalive:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable keep alive.
  auto_negotiate:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable IPsec SA auto-negotiation.
  add_route:
    type: enum
    raw_type: string
    choices:
    - phase1
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable automatic route addition.
  inbound_dscp_copy:
    type: enum
    raw_type: string
    choices:
    - phase1
    - enable
    - disable
    version_ranges:
    - - v7.0.6
      - v7.0.12
    - - v7.2.1
      - ''
    description: Enable/disable copying of the DSCP in the ESP header to the inner IP header.
  auto_discovery_sender:
    type: enum
    raw_type: string
    choices:
    - phase1
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable sending short-cut messages.
  auto_discovery_forwarder:
    type: enum
    raw_type: string
    choices:
    - phase1
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable forwarding short-cut messages.
  keylifeseconds:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Phase2 key life in time in seconds (120 - 172800).
  keylifekbs:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Phase2 key life in number of kilobytes of traffic (5120 - 4294967295).
  keylife_type:
    type: enum
    raw_type: string
    choices:
    - seconds
    - kbs
    - both
    version_ranges:
    - - v6.0.0
      - ''
    description: Keylife type.
  single_source:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable single source IP restriction.
  route_overlap:
    type: enum
    raw_type: string
    choices:
    - use-old
    - use-new
    - allow
    version_ranges:
    - - v6.0.0
      - ''
    description: Action for overlapping routes.
  encapsulation:
    type: enum
    raw_type: string
    choices:
    - tunnel-mode
    - transport-mode
    version_ranges:
    - - v6.0.0
      - ''
    description: ESP encapsulation mode.
  l2tp:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable L2TP over IPsec.
  comments:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Comment.
  initiator_ts_narrow:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.4.4
      - ''
    description: Enable/disable traffic selector narrowing for IKEv2 initiator.
  diffserv:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.4.4
      - ''
    description: Enable/disable applying DSCP value to the IPsec tunnel outer IP header.
  diffservcode:
    type: string
    raw_type: string
    version_ranges:
    - - v6.4.4
      - ''
    description: DSCP value to be applied to the IPsec tunnel outer IP header.
  protocol:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Quick mode protocol selector (1 - 255 or 0 for all).
  src_name:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Local proxy ID name. Source firewall.address.name firewall.addrgrp.name.
    references:
    - firewall.address.name
    - firewall.addrgrp.name
  src_name6:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Local proxy ID name. Source firewall.address6.name firewall.addrgrp6.name.
    references:
    - firewall.address6.name
    - firewall.addrgrp6.name
  src_addr_type:
    type: enum
    raw_type: string
    choices:
    - subnet
    - range
    - ip
    - name
    - subnet6
    - range6
    - ip6
    - name6
    version_ranges:
    - - v6.0.0
      - ''
    description: Local proxy ID type.
  src_start_ip:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Local proxy ID start.
  src_start_ip6:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Local proxy ID IPv6 start.
  src_end_ip:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Local proxy ID end.
  src_end_ip6:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Local proxy ID IPv6 end.
  src_subnet:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Local proxy ID subnet.
  src_subnet6:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Local proxy ID IPv6 subnet.
  src_port:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Quick mode source port (1 - 65535 or 0 for all).
  dst_name:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Remote proxy ID name. Source firewall.address.name firewall.addrgrp.name.
    references:
    - firewall.address.name
    - firewall.addrgrp.name
  dst_name6:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Remote proxy ID name. Source firewall.address6.name firewall.addrgrp6.name.
    references:
    - firewall.address6.name
    - firewall.addrgrp6.name
  dst_addr_type:
    type: enum
    raw_type: string
    choices:
    - subnet
    - range
    - ip
    - name
    - subnet6
    - range6
    - ip6
    - name6
    version_ranges:
    - - v6.0.0
      - ''
    description: Remote proxy ID type.
  dst_start_ip:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Remote proxy ID IPv4 start.
  dst_start_ip6:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Remote proxy ID IPv6 start.
  dst_end_ip:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Remote proxy ID IPv4 end.
  dst_end_ip6:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Remote proxy ID IPv6 end.
  dst_subnet:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Remote proxy ID IPv4 subnet.
  dst_subnet6:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Remote proxy ID IPv6 subnet.
  dst_port:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Quick mode destination port (1 - 65535 or 0 for all).
