id: waf.main-class
version: 7.6.7
source_object: fortios_waf_main_class
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_waf_main_class.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Main signature class name.
  id:
    type: integer
    raw_type: integer
    required: true
    version_ranges:
    - - v6.0.0
      - ''
    description: Main signature class ID. see <a href='#notes'>Notes</a>.
