id: wanopt.settings
version: 7.6.7
source_object: fortios_wanopt_settings
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_wanopt_settings.py
root_type: object
attributes:
  host_id:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Local host ID (must also be entered in the remote FortiGate"s peer list).
  tunnel_ssl_algorithm:
    type: enum
    raw_type: string
    choices:
    - high
    - medium
    - low
    version_ranges:
    - - v6.0.0
      - ''
    description: Relative strength of encryption algorithms accepted during tunnel negotiation.
  auto_detect_algorithm:
    type: enum
    raw_type: string
    choices:
    - simple
    - diff-req-resp
    version_ranges:
    - - v6.0.0
      - ''
    description: Auto detection algorithms used in tunnel negotiations.
  tunnel_optimization:
    type: enum
    raw_type: string
    choices:
    - memory-usage
    - balanced
    - throughput
    version_ranges:
    - - v7.0.6
      - v7.0.12
    - - v7.2.1
      - ''
    description: WANOpt tunnel optimization option.
