id: web-proxy.fast-fallback
version: 7.6.7
source_object: fortios_web_proxy_fast_fallback
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_web_proxy_fast_fallback.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v7.4.1
      - ''
    description: Configure a name for the fast-fallback entry.
  status:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.4.1
      - ''
    description: Enable/disable the fast-fallback entry.
  connection_mode:
    type: enum
    raw_type: string
    choices:
    - sequentially
    - simultaneously
    version_ranges:
    - - v7.4.1
      - ''
    description: Connection mode for multiple destinations.
  protocol:
    type: enum
    raw_type: string
    choices:
    - IPv4-first
    - IPv6-first
    - IPv4-only
    - IPv6-only
    version_ranges:
    - - v7.4.1
      - ''
    description: Connection protocols for multiple destinations.
  connection_timeout:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.4.1
      - ''
    description: Number of milliseconds to wait before starting another connection (200 - 1800000). For sequential connection-mode
      only.
