id: web-proxy.explicit
version: 7.6.7
source_object: fortios_web_proxy_explicit
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_web_proxy_explicit.py
root_type: object
attributes:
  status:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable the explicit Web proxy for HTTP and HTTPS session.
  secure_web_proxy:
    type: enum
    raw_type: string
    choices:
    - disable
    - enable
    - secure
    version_ranges:
    - - v7.4.0
      - ''
    description: Enable/disable/require the secure web proxy for HTTP and HTTPS session.
  ftp_over_http:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable to proxy FTP-over-HTTP sessions sent from a web browser.
  socks:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable the SOCKS proxy.
  http_incoming_port:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Accept incoming HTTP requests on one or more ports (0 - 65535).
  http_connection_mode:
    type: enum
    raw_type: string
    choices:
    - static
    - multiplex
    - serverpool
    version_ranges:
    - - v7.2.4
      - ''
    description: HTTP connection mode .
  https_incoming_port:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Accept incoming HTTPS requests on one or more ports (0 - 65535).
  secure_web_proxy_cert:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v7.4.0
      - ''
    description: Name of certificates for secure web proxy.
    children:
      name:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v7.4.0
          - ''
        description: Certificate list. Source vpn.certificate.local.name.
        references:
        - vpn.certificate.local.name
  client_cert:
    type: enum
    raw_type: string
    choices:
    - disable
    - enable
    version_ranges:
    - - v7.4.4
      - ''
    description: Enable/disable to request client certificate.
  user_agent_detect:
    type: enum
    raw_type: string
    choices:
    - disable
    - enable
    version_ranges:
    - - v7.4.4
      - ''
    description: Enable/disable to detect device type by HTTP user-agent if no client certificate provided.
  empty_cert_action:
    type: enum
    raw_type: string
    choices:
    - accept
    - block
    - accept-unmanageable
    version_ranges:
    - - v7.4.4
      - ''
    description: Action of an empty client certificate.
  ssl_dh_bits:
    type: enum
    raw_type: string
    choices:
    - '768'
    - '1024'
    - '1536'
    - '2048'
    version_ranges:
    - - v7.4.0
      - ''
    description: Bit-size of Diffie-Hellman (DH) prime used in DHE-RSA negotiation .
  ftp_incoming_port:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Accept incoming FTP-over-HTTP requests on one or more ports (0 - 65535).
  socks_incoming_port:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Accept incoming SOCKS proxy requests on one or more ports (0 - 65535).
  incoming_ip:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Restrict the explicit HTTP proxy to only accept sessions from this IP address. An interface must have this
      IP address.
  outgoing_ip:
    type: list
    raw_type: list
    multiple_values: true
    elements: str
    version_ranges:
    - - v6.0.0
      - ''
    description: Outgoing HTTP requests will have this IP address as their source address. An interface must have this IP
      address.
  interface_select_method:
    type: enum
    raw_type: string
    choices:
    - sdwan
    - specify
    version_ranges:
    - - v7.6.1
      - ''
    description: Specify how to select outgoing interface to reach server.
  interface:
    type: string
    raw_type: string
    version_ranges:
    - - v7.6.1
      - ''
    description: Specify outgoing interface to reach server. Source system.interface.name.
    references:
    - system.interface.name
  vrf_select:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.6.1
      - ''
    description: VRF ID used for connection to server.
  ipv6_status:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable allowing an IPv6 web proxy destination in policies and all IPv6 related entries in this command.
  incoming_ip6:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Restrict the explicit web proxy to only accept sessions from this IPv6 address. An interface must have this
      IPv6 address.
  outgoing_ip6:
    type: list
    raw_type: list
    multiple_values: true
    elements: str
    version_ranges:
    - - v6.0.0
      - ''
    description: Outgoing HTTP requests will leave this IPv6. Multiple interfaces can be specified. Interfaces must have these
      IPv6 addresses.
  strict_guest:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable strict guest user checking by the explicit web proxy.
  pref_dns_result:
    type: enum
    raw_type: string
    choices:
    - ipv4
    - ipv6
    - ipv4-strict
    - ipv6-strict
    version_ranges:
    - - v6.0.0
      - ''
    description: Prefer resolving addresses using the configured IPv4 or IPv6 DNS server .
  unknown_http_version:
    type: enum
    raw_type: string
    choices:
    - reject
    - best-effort
    version_ranges:
    - - v6.0.0
      - ''
    description: How to handle HTTP sessions that do not comply with HTTP 0.9, 1.0, or 1.1.
  realm:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Authentication realm used to identify the explicit web proxy (maximum of 63 characters).
  sec_default_action:
    type: enum
    raw_type: string
    choices:
    - accept
    - deny
    version_ranges:
    - - v6.0.0
      - ''
    description: Accept or deny explicit web proxy sessions when no web proxy firewall policy exists.
  https_replacement_message:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable sending the client a replacement message for HTTPS requests.
  message_upon_server_error:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable displaying a replacement message when a server error is detected.
  pac_file_server_status:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable Proxy Auto-Configuration (PAC) for users of this explicit proxy profile.
  pac_file_server_port:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Port number that PAC traffic from client web browsers uses to connect to the explicit web proxy (0 - 65535).
  pac_file_through_https:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.2.1
      - ''
    description: Enable/disable to get Proxy Auto-Configuration (PAC) through HTTPS.
  pac_file_name:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Pac file name.
  pac_file_data:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: PAC file contents enclosed in quotes (maximum of 256K bytes).
  pac_policy:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: PAC policies.
    children:
      policyid:
        type: integer
        raw_type: integer
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: Policy ID. see <a href='#notes'>Notes</a>.
      status:
        type: enum
        raw_type: string
        choices:
        - enable
        - disable
        version_ranges:
        - - v6.0.0
          - ''
        description: Enable/disable policy.
      srcaddr:
        type: list
        raw_type: list
        elements: dict
        version_ranges:
        - - v6.0.0
          - ''
        description: Source address objects.
        children:
          name:
            type: string
            raw_type: string
            required: true
            version_ranges:
            - - v6.0.0
              - ''
            description: Address name. Source firewall.address.name firewall.addrgrp.name firewall.proxy-address.name firewall.proxy-addrgrp.name.
            references:
            - firewall.address.name
            - firewall.addrgrp.name
            - firewall.proxy-address.name
            - firewall.proxy-addrgrp.name
      srcaddr6:
        type: list
        raw_type: list
        elements: dict
        version_ranges:
        - - v6.0.0
          - ''
        description: Source address6 objects.
        children:
          name:
            type: string
            raw_type: string
            required: true
            version_ranges:
            - - v6.0.0
              - ''
            description: Address name. Source firewall.address6.name firewall.addrgrp6.name.
            references:
            - firewall.address6.name
            - firewall.addrgrp6.name
      dstaddr:
        type: list
        raw_type: list
        elements: dict
        version_ranges:
        - - v6.0.0
          - ''
        description: Destination address objects.
        children:
          name:
            type: string
            raw_type: string
            required: true
            version_ranges:
            - - v6.0.0
              - ''
            description: Address name. Source firewall.address.name firewall.addrgrp.name.
            references:
            - firewall.address.name
            - firewall.addrgrp.name
      pac_file_name:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Pac file name.
      pac_file_data:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: PAC file contents enclosed in quotes (maximum of 256K bytes).
      comments:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Optional comments.
  ssl_algorithm:
    type: enum
    raw_type: string
    choices:
    - high
    - medium
    - low
    version_ranges:
    - - v6.0.0
      - ''
    description: 'Relative strength of encryption algorithms accepted in HTTPS deep scan: high, medium, or low.'
  trace_auth_no_rsp:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable logging timed-out authentication requests.
