id: web-proxy.isolator-server
version: 7.6.7
source_object: fortios_web_proxy_isolator_server
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_web_proxy_isolator_server.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v7.6.1
      - ''
    description: Server name.
  addr_type:
    type: enum
    raw_type: string
    choices:
    - ip
    - ipv6
    - fqdn
    version_ranges:
    - - v7.6.1
      - ''
    description: 'Address type of the forwarding proxy server: IP or FQDN.'
  ip:
    type: string
    raw_type: string
    version_ranges:
    - - v7.6.1
      - ''
    description: Forward proxy server IP address.
  ipv6:
    type: string
    raw_type: string
    version_ranges:
    - - v7.6.1
      - ''
    description: Forward proxy server IPv6 address.
  fqdn:
    type: string
    raw_type: string
    version_ranges:
    - - v7.6.1
      - ''
    description: Forward server Fully Qualified Domain Name (FQDN).
  port:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.6.1
      - ''
    description: Port number that the forwarding server expects to receive HTTP sessions on (1 - 65535).
  interface_select_method:
    type: enum
    raw_type: string
    choices:
    - sdwan
    - specify
    version_ranges:
    - - v7.6.1
      - ''
    description: Specify how to select outgoing interface to reach server.
  interface:
    type: string
    raw_type: string
    version_ranges:
    - - v7.6.1
      - ''
    description: Specify outgoing interface to reach server. Source system.interface.name.
    references:
    - system.interface.name
  vrf_select:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.6.1
      - ''
    description: VRF ID used for connection to server.
  comment:
    type: string
    raw_type: string
    version_ranges:
    - - v7.6.1
      - ''
    description: Comment.
  masquerade:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.6.3
      - ''
    description: Enable/disable use of the IP address of the outgoing interface as the client IP address
