id: webfilter.ftgd-local-risk
version: 7.6.7
source_object: fortios_webfilter_ftgd_local_risk
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_webfilter_ftgd_local_risk.py
root_type: list
attributes:
  url:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v7.6.1
      - ''
    description: URL to rate locally.
  status:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.6.1
      - ''
    description: Enable/disable local risk score.
  comment:
    type: string
    raw_type: string
    version_ranges:
    - - v7.6.1
      - ''
    description: Comment.
  risk_score:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.6.1
      - ''
    description: Local risk score.
