id: webfilter.ftgd-local-cat
version: 7.6.7
source_object: fortios_webfilter_ftgd_local_cat
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_webfilter_ftgd_local_cat.py
root_type: list
attributes:
  status:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable the local category.
  id:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Local category ID.
  desc:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v6.0.0
      - ''
    description: Local category description.
