id: webfilter.override
version: 7.6.7
source_object: fortios_webfilter_override
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_webfilter_override.py
root_type: list
attributes:
  id:
    type: integer
    raw_type: integer
    required: true
    version_ranges:
    - - v6.0.0
      - ''
    description: Override rule ID. see <a href='#notes'>Notes</a>.
  status:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable override rule.
  scope:
    type: enum
    raw_type: string
    choices:
    - user
    - user-group
    - ip
    - ip6
    version_ranges:
    - - v6.0.0
      - ''
    description: Override either the specific user, user group, IPv4 address, or IPv6 address.
  ip:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: IPv4 address which the override applies.
  user:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Name of the user which the override applies.
  user_group:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Specify the user group for which the override applies. Source user.group.name.
    references:
    - user.group.name
  old_profile:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Name of the web filter profile which the override applies. Source webfilter.profile.name.
    references:
    - webfilter.profile.name
  new_profile:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Name of the new web filter profile used by the override. Source webfilter.profile.name.
    references:
    - webfilter.profile.name
  ip6:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: IPv6 address which the override applies.
  expires:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: 'Override expiration date and time, from 5 minutes to 365 from now (format: yyyy/mm/dd hh:mm:ss).'
  initiator:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Initiating user of override (read-only setting).
