id: webfilter.ips-urlfilter-cache-setting
version: 7.6.7
source_object: fortios_webfilter_ips_urlfilter_cache_setting
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_webfilter_ips_urlfilter_cache_setting.py
root_type: object
attributes:
  dns_retry_interval:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Retry interval. Refresh DNS faster than TTL to capture multiple IPs for hosts. 0 means use DNS server"s TTL
      only.
  extended_ttl:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Extend time to live beyond reported by DNS. Use of 0 means use DNS server"s TTL.
