id: wireless-controller.snmp
version: 7.6.7
source_object: fortios_wireless_controller_snmp
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_wireless_controller_snmp.py
root_type: object
attributes:
  engine_id:
    type: string
    raw_type: string
    version_ranges:
    - - v6.2.0
      - ''
    description: AC SNMP engineID string (maximum 24 characters).
  contact_info:
    type: string
    raw_type: string
    version_ranges:
    - - v6.2.0
      - ''
    description: Contact Information.
  trap_high_cpu_threshold:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.2.0
      - ''
    description: CPU usage when trap is sent.
  trap_high_mem_threshold:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.2.0
      - ''
    description: Memory usage when trap is sent.
  community:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.2.0
      - ''
    description: SNMP Community Configuration.
    children:
      id:
        type: integer
        raw_type: integer
        required: true
        version_ranges:
        - - v6.2.0
          - ''
        description: Community ID. see <a href='#notes'>Notes</a>.
      name:
        type: string
        raw_type: string
        version_ranges:
        - - v6.2.0
          - ''
        description: Community name.
      status:
        type: enum
        raw_type: string
        choices:
        - enable
        - disable
        version_ranges:
        - - v6.2.0
          - ''
        description: Enable/disable this SNMP community.
      query_v1_status:
        type: enum
        raw_type: string
        choices:
        - enable
        - disable
        version_ranges:
        - - v6.2.0
          - ''
        description: Enable/disable SNMP v1 queries.
      query_v2c_status:
        type: enum
        raw_type: string
        choices:
        - enable
        - disable
        version_ranges:
        - - v6.2.0
          - ''
        description: Enable/disable SNMP v2c queries.
      trap_v1_status:
        type: enum
        raw_type: string
        choices:
        - enable
        - disable
        version_ranges:
        - - v6.2.0
          - ''
        description: Enable/disable SNMP v1 traps.
      trap_v2c_status:
        type: enum
        raw_type: string
        choices:
        - enable
        - disable
        version_ranges:
        - - v6.2.0
          - ''
        description: Enable/disable SNMP v2c traps.
      hosts:
        type: list
        raw_type: list
        elements: dict
        version_ranges:
        - - v6.2.0
          - ''
        description: Configure IPv4 SNMP managers (hosts).
        children:
          id:
            type: integer
            raw_type: integer
            required: true
            version_ranges:
            - - v6.2.0
              - ''
            description: Host entry ID. see <a href='#notes'>Notes</a>.
          ip:
            type: string
            raw_type: string
            version_ranges:
            - - v6.2.0
              - ''
            description: IPv4 address of the SNMP manager (host).
      hosts6:
        type: list
        raw_type: list
        elements: dict
        version_ranges:
        - - v7.6.5
          - ''
        description: Configure IPv6 SNMP managers (hosts).
        children:
          id:
            type: integer
            raw_type: integer
            required: true
            version_ranges:
            - - v7.6.5
              - ''
            description: Host6 entry ID. see <a href='#notes'>Notes</a>.
          ipv6:
            type: string
            raw_type: string
            version_ranges:
            - - v7.6.5
              - ''
            description: IPv6 address of the SNMP manager (host).
  user:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.2.0
      - ''
    description: SNMP User Configuration.
    children:
      name:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v6.2.0
          - ''
        description: SNMP user name.
      status:
        type: enum
        raw_type: string
        choices:
        - enable
        - disable
        version_ranges:
        - - v6.2.0
          - ''
        description: SNMP user enable.
      queries:
        type: enum
        raw_type: string
        choices:
        - enable
        - disable
        version_ranges:
        - - v6.2.0
          - ''
        description: Enable/disable SNMP queries for this user.
      trap_status:
        type: enum
        raw_type: string
        choices:
        - enable
        - disable
        version_ranges:
        - - v6.2.0
          - ''
        description: Enable/disable traps for this SNMP user.
      security_level:
        type: enum
        raw_type: string
        choices:
        - no-auth-no-priv
        - auth-no-priv
        - auth-priv
        version_ranges:
        - - v6.2.0
          - ''
        description: Security level for message authentication and encryption.
      auth_proto:
        type: enum
        raw_type: string
        choices:
        - md5
        - sha
        - sha224
        - sha256
        - sha384
        - sha512
        version_ranges:
        - - v6.2.0
          - ''
        description: Authentication protocol.
      auth_pwd:
        type: string
        raw_type: string
        version_ranges:
        - - v6.2.0
          - ''
        description: Password for authentication protocol.
      priv_proto:
        type: enum
        raw_type: string
        choices:
        - aes
        - des
        - aes256
        - aes256cisco
        version_ranges:
        - - v6.2.0
          - ''
        description: Privacy (encryption) protocol.
      priv_pwd:
        type: string
        raw_type: string
        version_ranges:
        - - v6.2.0
          - ''
        description: Password for privacy (encryption) protocol.
      notify_hosts:
        type: list
        raw_type: list
        multiple_values: true
        elements: str
        version_ranges:
        - - v6.2.0
          - ''
        description: Configure SNMP User Notify Hosts.
      notify_hosts6:
        type: list
        raw_type: list
        multiple_values: true
        elements: str
        version_ranges:
        - - v7.6.5
          - ''
        description: Configure IPv6 SNMP User Notify Hosts.
