id: wireless-controller.arrp-profile
version: 7.6.7
source_object: fortios_wireless_controller_arrp_profile
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_wireless_controller_arrp_profile.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v6.4.0
      - v6.4.0
    - - v6.4.4
      - ''
    description: WiFi ARRP profile name.
  comment:
    type: string
    raw_type: string
    version_ranges:
    - - v6.4.0
      - v6.4.0
    - - v6.4.4
      - ''
    description: Comment.
  selection_period:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.4.0
      - v6.4.0
    - - v6.4.4
      - ''
    description: Period in seconds to measure average channel load, noise floor, spectral RSSI .
  monitor_period:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.4.0
      - v6.4.0
    - - v6.4.4
      - ''
    description: Period in seconds to measure average transmit retries and receive errors .
  weight_managed_ap:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.4.0
      - v6.4.0
    - - v6.4.4
      - ''
    description: Weight in DARRP channel score calculation for managed APs (0 - 200).
  weight_rogue_ap:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.4.0
      - v6.4.0
    - - v6.4.4
      - ''
    description: Weight in DARRP channel score calculation for rogue APs (0 - 200).
  weight_noise_floor:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.4.0
      - v6.4.0
    - - v6.4.4
      - ''
    description: Weight in DARRP channel score calculation for noise floor (0 - 200).
  weight_channel_load:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.4.0
      - v6.4.0
    - - v6.4.4
      - ''
    description: Weight in DARRP channel score calculation for channel load (0 - 200).
  weight_spectral_rssi:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.4.0
      - v6.4.0
    - - v6.4.4
      - ''
    description: Weight in DARRP channel score calculation for spectral RSSI (0 - 200).
  weight_weather_channel:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.4.0
      - v6.4.0
    - - v6.4.4
      - ''
    description: Weight in DARRP channel score calculation for weather channel (0 - 200).
  weight_dfs_channel:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.4.0
      - v6.4.0
    - - v6.4.4
      - ''
    description: Weight in DARRP channel score calculation for DFS channel (0 - 200).
  threshold_ap:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.4.0
      - v6.4.0
    - - v6.4.4
      - ''
    description: Threshold to reject channel in DARRP channel selection phase 1 due to surrounding APs (0 - 500).
  threshold_noise_floor:
    type: string
    raw_type: string
    version_ranges:
    - - v6.4.0
      - v6.4.0
    - - v6.4.4
      - ''
    description: Threshold in dBm to reject channel in DARRP channel selection phase 1 due to noise floor (-95 to -20).
  threshold_channel_load:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.4.0
      - v6.4.0
    - - v6.4.4
      - ''
    description: Threshold in percentage to reject channel in DARRP channel selection phase 1 due to channel load (0 - 100).
  threshold_spectral_rssi:
    type: string
    raw_type: string
    version_ranges:
    - - v6.4.0
      - v6.4.0
    - - v6.4.4
      - ''
    description: Threshold in dBm to reject channel in DARRP channel selection phase 1 due to spectral RSSI (-95 to -20).
  threshold_tx_retries:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.4.0
      - v6.4.0
    - - v6.4.4
      - ''
    description: Threshold in percentage for transmit retries to trigger channel reselection in DARRP monitor stage (0 - 1000).
  threshold_rx_errors:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.4.0
      - v6.4.0
    - - v6.4.4
      - ''
    description: Threshold in percentage for receive errors to trigger channel reselection in DARRP monitor stage (0 - 100).
  include_weather_channel:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.4.0
      - v6.4.0
    - - v6.4.4
      - ''
    description: Enable/disable use of weather channel in DARRP channel selection phase 1 .
  include_dfs_channel:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.4.0
      - v6.4.0
    - - v6.4.4
      - ''
    description: Enable/disable use of DFS channel in DARRP channel selection phase 1 .
  override_darrp_optimize:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v7.0.4
      - ''
    description: Enable to override setting darrp-optimize and darrp-optimize-schedules .
  darrp_optimize:
    type: integer
    raw_type: integer
    version_ranges:
    - - v7.0.4
      - ''
    description: Time for running Distributed Automatic Radio Resource Provisioning (DARRP) optimizations (0 - 86400 sec).
  darrp_optimize_schedules:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v7.0.4
      - ''
    description: Firewall schedules for DARRP running time. DARRP will run periodically based on darrp-optimize within the
      schedules. Separate multiple schedule names with a space.
    children:
      name:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v7.0.4
          - ''
        description: Schedule name. Source firewall.schedule.group.name firewall.schedule.recurring.name firewall.schedule.onetime.name.
        references:
        - firewall.schedule.group.name
        - firewall.schedule.onetime.name
        - firewall.schedule.recurring.name
