id: wireless-controller.qos-profile
version: 7.6.7
source_object: fortios_wireless_controller_qos_profile
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_wireless_controller_qos_profile.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v6.0.0
      - ''
    description: WiFi QoS profile name.
  comment:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Comment.
  uplink:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Maximum uplink bandwidth for Virtual Access Points (VAPs) (0 - 2097152 Kbps).
  downlink:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Maximum downlink bandwidth for Virtual Access Points (VAPs) (0 - 2097152 Kbps).
  uplink_sta:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Maximum uplink bandwidth for clients (0 - 2097152 Kbps).
  downlink_sta:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Maximum downlink bandwidth for clients (0 - 2097152 Kbps).
  burst:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable client rate burst.
  wmm:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable WiFi multi-media (WMM) control.
  wmm_uapsd:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable WMM Unscheduled Automatic Power Save Delivery (U-APSD) power save mode.
  call_admission_control:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable WMM call admission control.
  call_capacity:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Maximum number of Voice over WLAN (VoWLAN) phones allowed (0 - 60).
  bandwidth_admission_control:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable WMM bandwidth admission control.
  bandwidth_capacity:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.0.0
      - ''
    description: Maximum bandwidth capacity allowed (1 - 600000 Kbps).
  dscp_wmm_mapping:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable Differentiated Services Code Point (DSCP) mapping.
  dscp_wmm_vo:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: DSCP mapping for voice access .
    children:
      id:
        type: integer
        raw_type: integer
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: DSCP WMM mapping numbers (0 - 63). see <a href='#notes'>Notes</a>.
  dscp_wmm_vi:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: DSCP mapping for video access .
    children:
      id:
        type: integer
        raw_type: integer
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: DSCP WMM mapping numbers (0 - 63). see <a href='#notes'>Notes</a>.
  dscp_wmm_be:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: DSCP mapping for best effort access .
    children:
      id:
        type: integer
        raw_type: integer
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: DSCP WMM mapping numbers (0 - 63). see <a href='#notes'>Notes</a>.
  dscp_wmm_bk:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: DSCP mapping for background access .
    children:
      id:
        type: integer
        raw_type: integer
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: DSCP WMM mapping numbers (0 - 63). see <a href='#notes'>Notes</a>.
  wmm_dscp_marking:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.2.0
      - ''
    description: Enable/disable WMM Differentiated Services Code Point (DSCP) marking.
  wmm_vo_dscp:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.2.0
      - ''
    description: DSCP marking for voice access .
  wmm_vi_dscp:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.2.0
      - ''
    description: DSCP marking for video access .
  wmm_be_dscp:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.2.0
      - ''
    description: DSCP marking for best effort access .
  wmm_bk_dscp:
    type: integer
    raw_type: integer
    version_ranges:
    - - v6.2.0
      - ''
    description: DSCP marking for background access .
