id: wireless-controller.ap-status
version: 7.6.7
source_object: fortios_wireless_controller_ap_status
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_wireless_controller_ap_status.py
root_type: list
attributes:
  id:
    type: integer
    raw_type: integer
    required: true
    version_ranges:
    - - v6.0.0
      - ''
    description: AP ID. see <a href='#notes'>Notes</a>.
  bssid:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Access Point"s (AP"s) BSSID.
  ssid:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Access Point"s (AP"s) SSID.
  status:
    type: enum
    raw_type: string
    choices:
    - rogue
    - accepted
    - suppressed
    version_ranges:
    - - v6.0.0
      - ''
    description: 'Access Point"s (AP"s) status: rogue, accepted, or suppressed.'
