id: wireless-controller.hotspot20.h2qp-osu-provider-nai
version: 7.6.7
source_object: fortios_wireless_controller_hotspot20_h2qp_osu_provider_nai
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_wireless_controller_hotspot20_h2qp_osu_provider_nai.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v7.0.2
      - ''
    description: OSU provider NAI ID.
  nai_list:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v7.0.2
      - ''
    description: OSU NAI list.
    children:
      name:
        type: string
        raw_type: string
        required: true
        version_ranges:
        - - v7.0.2
          - ''
        description: OSU NAI ID.
      osu_nai:
        type: string
        raw_type: string
        version_ranges:
        - - v7.0.2
          - ''
        description: OSU NAI.
