id: wireless-controller.hotspot20.h2qp-osu-provider
version: 7.6.7
source_object: fortios_wireless_controller_hotspot20_h2qp_osu_provider
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_wireless_controller_hotspot20_h2qp_osu_provider.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v6.0.0
      - ''
    description: OSU provider ID.
  friendly_name:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: OSU provider friendly name.
    children:
      index:
        type: integer
        raw_type: integer
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: OSU provider friendly name index. see <a href='#notes'>Notes</a>.
      lang:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Language code.
      friendly_name:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: OSU provider friendly name.
  server_uri:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Server URI.
  osu_method:
    type: enum
    raw_type: list
    choices:
    - oma-dm
    - soap-xml-spp
    - reserved
    multiple_values: true
    elements: str
    version_ranges:
    - - v6.0.0
      - ''
    description: OSU method list.
  osu_nai:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: OSU NAI.
  service_description:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: OSU service name.
    children:
      service_id:
        type: integer
        raw_type: integer
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: OSU service ID. see <a href='#notes'>Notes</a>.
      lang:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Language code.
      service_description:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Service description.
  icon:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: OSU provider icon. Source wireless-controller.hotspot20.icon.name.
    references:
    - wireless-controller.hotspot20.icon.name
