id: wireless-controller.access-control-list
version: 7.6.7
source_object: fortios_wireless_controller_access_control_list
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_wireless_controller_access_control_list.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v6.4.0
      - ''
    description: AP access control list name.
  comment:
    type: string
    raw_type: string
    version_ranges:
    - - v6.4.0
      - ''
    description: Description.
  layer3_ipv4_rules:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.4.0
      - ''
    description: AP ACL layer3 ipv4 rule list.
    children:
      rule_id:
        type: integer
        raw_type: integer
        required: true
        version_ranges:
        - - v6.4.0
          - ''
        description: Rule ID (1 - 65535). see <a href='#notes'>Notes</a>.
      comment:
        type: string
        raw_type: string
        version_ranges:
        - - v6.4.0
          - ''
        description: Description.
      srcaddr:
        type: string
        raw_type: string
        version_ranges:
        - - v6.4.0
          - ''
        description: Source IP address (any | local-LAN | IPv4 address[/<network mask | mask length>] | fqdn).
      srcport:
        type: integer
        raw_type: integer
        version_ranges:
        - - v6.4.0
          - ''
        description: Source port (0 - 65535).
      dstaddr:
        type: string
        raw_type: string
        version_ranges:
        - - v6.4.0
          - ''
        description: Destination IP address (any | local-LAN | IPv4 address[/<network mask | mask length>]).
      dstport:
        type: integer
        raw_type: integer
        version_ranges:
        - - v6.4.0
          - ''
        description: Destination port (0 - 65535).
      protocol:
        type: integer
        raw_type: integer
        version_ranges:
        - - v6.4.0
          - ''
        description: Protocol type as defined by IANA (0 - 255).
      action:
        type: enum
        raw_type: string
        choices:
        - allow
        - deny
        version_ranges:
        - - v6.4.0
          - ''
        description: Policy action (allow | deny).
  layer3_ipv6_rules:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.4.0
      - ''
    description: AP ACL layer3 ipv6 rule list.
    children:
      rule_id:
        type: integer
        raw_type: integer
        required: true
        version_ranges:
        - - v6.4.0
          - ''
        description: Rule ID (1 - 65535). see <a href='#notes'>Notes</a>.
      comment:
        type: string
        raw_type: string
        version_ranges:
        - - v6.4.0
          - ''
        description: Description.
      srcaddr:
        type: string
        raw_type: string
        version_ranges:
        - - v6.4.0
          - ''
        description: Source IPv6 address (any | local-LAN | IPv6 address[/prefix length] | fqdn), default = any.
      srcport:
        type: integer
        raw_type: integer
        version_ranges:
        - - v6.4.0
          - ''
        description: Source port (0 - 65535).
      dstaddr:
        type: string
        raw_type: string
        version_ranges:
        - - v6.4.0
          - ''
        description: Destination IPv6 address (any | local-LAN | IPv6 address[/prefix length]), default = any.
      dstport:
        type: integer
        raw_type: integer
        version_ranges:
        - - v6.4.0
          - ''
        description: Destination port (0 - 65535).
      protocol:
        type: integer
        raw_type: integer
        version_ranges:
        - - v6.4.0
          - ''
        description: Protocol type as defined by IANA (0 - 255).
      action:
        type: enum
        raw_type: string
        choices:
        - allow
        - deny
        version_ranges:
        - - v6.4.0
          - ''
        description: Policy action (allow | deny).
