id: wireless-controller.utm-profile
version: 7.6.7
source_object: fortios_wireless_controller_utm_profile
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_wireless_controller_utm_profile.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v6.0.0
      - ''
    description: UTM profile name.
  comment:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Comment.
  utm_log:
    type: enum
    raw_type: string
    choices:
    - enable
    - disable
    version_ranges:
    - - v6.0.0
      - ''
    description: Enable/disable UTM logging.
  ips_sensor:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: IPS sensor name. Source ips.sensor.name.
    references:
    - ips.sensor.name
  application_list:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: Application control list name. Source application.list.name.
    references:
    - application.list.name
  antivirus_profile:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: AntiVirus profile name. Source antivirus.profile.name.
    references:
    - antivirus.profile.name
  webfilter_profile:
    type: string
    raw_type: string
    version_ranges:
    - - v6.0.0
      - ''
    description: WebFilter profile name. Source webfilter.profile.name.
    references:
    - webfilter.profile.name
  scan_botnet_connections:
    type: enum
    raw_type: string
    choices:
    - disable
    - monitor
    - block
    version_ranges:
    - - v6.0.0
      - ''
    description: Block or monitor connections to Botnet servers or disable Botnet scanning.
