id: wireless-controller.nac-profile
version: 7.6.7
source_object: fortios_wireless_controller_nac_profile
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_wireless_controller_nac_profile.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v7.0.0
      - ''
    description: Name.
  comment:
    type: string
    raw_type: string
    version_ranges:
    - - v7.0.0
      - ''
    description: Comment.
  onboarding_vlan:
    type: string
    raw_type: string
    version_ranges:
    - - v7.0.0
      - ''
    description: VLAN interface name. Source system.interface.name.
    references:
    - system.interface.name
