id: wireless-controller.hotspot20.anqp-venue-name
version: 7.6.7
source_object: fortios_wireless_controller_hotspot20_anqp_venue_name
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_wireless_controller_hotspot20_anqp_venue_name.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v6.0.0
      - ''
    description: Name of venue name duple.
  value_list:
    type: list
    raw_type: list
    elements: dict
    version_ranges:
    - - v6.0.0
      - ''
    description: Name list.
    children:
      index:
        type: integer
        raw_type: integer
        required: true
        version_ranges:
        - - v6.0.0
          - ''
        description: Value index. see <a href='#notes'>Notes</a>.
      lang:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Language code.
      value:
        type: string
        raw_type: string
        version_ranges:
        - - v6.0.0
          - ''
        description: Venue name value.
