id: ztna.traffic-forward-proxy
version: 7.6.7
source_object: fortios_ztna_traffic_forward_proxy
source:
  kind: ansible
  file: .work\ansible\plugins\modules\fortios_ztna_traffic_forward_proxy.py
root_type: list
attributes:
  name:
    type: string
    raw_type: string
    required: true
    version_ranges:
    - - v7.6.0
      - ''
    description: ZTNA traffic forward proxy name.
  vip:
    type: string
    raw_type: string
    version_ranges:
    - - v7.6.1
      - ''
    description: Virtual IP name. Source firewall.vip.name.
    references:
    - firewall.vip.name
  host:
    type: string
    raw_type: string
    version_ranges:
    - - v7.6.1
      - ''
    description: Virtual or real host name. Source firewall.access-proxy-virtual-host.name.
    references:
    - firewall.access-proxy-virtual-host.name
  decrypted_traffic_mirror:
    type: string
    raw_type: string
    version_ranges:
    - - v7.6.1
      - ''
    description: Decrypted traffic mirror. Source firewall.decrypted-traffic-mirror.name.
    references:
    - firewall.decrypted-traffic-mirror.name
  vip6:
    type: string
    raw_type: string
    version_ranges:
    - - v7.6.1
      - ''
    description: Virtual IPv6 name. Source firewall.vip6.name.
    references:
    - firewall.vip6.name
  log_blocked_traffic:
    type: enum
    raw_type: string
    choices:
    - disable
    - enable
    version_ranges:
    - - v7.6.0
      - v7.6.7
    description: Enable/disable logging of blocked traffic.
  auth_portal:
    type: enum
    raw_type: string
    choices:
    - disable
    - enable
    version_ranges:
    - - v7.6.0
      - v7.6.7
    description: Enable/disable authentication portal.
  auth_virtual_host:
    type: string
    raw_type: string
    version_ranges:
    - - v7.6.1
      - v7.6.7
    description: Virtual host for authentication portal. Source firewall.access-proxy-virtual-host.name.
    references:
    - firewall.access-proxy-virtual-host.name
