id: application.list
version: 7.6.7
source_object: resource_application_list
source:
  kind: terraform
  file: .work\terraform\fortios\resource_application_list.go
attributes:
  vdomparam:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
    force_new: true
  update_if_exist:
    type: boolean
    raw_type: TypeBool
    optional: true
    computed: true
  name:
    type: string
    raw_type: TypeString
    required: true
    force_new: true
    min_length: 0
    max_length: 47
  uuid:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  fabric_object:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  fabric_force_sync:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  fabric_object_source:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  comment:
    type: string
    raw_type: TypeString
    optional: true
    min_length: 0
    max_length: 255
  replacemsg_group:
    type: string
    raw_type: TypeString
    optional: true
    min_length: 0
    max_length: 35
  extended_log:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  other_application_action:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  app_replacemsg:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  other_application_log:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  enforce_default_app_port:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  force_inclusion_ssl_di_sigs:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  unknown_application_action:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  unknown_application_log:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  p2p_block_list:
    type: string
    raw_type: TypeString
    optional: true
  p2p_black_list:
    type: string
    raw_type: TypeString
    optional: true
  deep_app_inspection:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  options:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  entries:
    type: list
    raw_type: TypeList
    optional: true
    children:
      id:
        type: integer
        raw_type: TypeInt
        optional: true
        computed: true
      risk:
        type: list
        raw_type: TypeSet
        optional: true
        children:
          level:
            type: integer
            raw_type: TypeInt
            optional: true
      category:
        type: list
        raw_type: TypeSet
        optional: true
        children:
          id:
            type: integer
            raw_type: TypeInt
            optional: true
      sub_category:
        type: list
        raw_type: TypeSet
        optional: true
        children:
          id:
            type: integer
            raw_type: TypeInt
            optional: true
      application:
        type: list
        raw_type: TypeSet
        optional: true
        children:
          id:
            type: integer
            raw_type: TypeInt
            optional: true
      protocols:
        type: string
        raw_type: TypeString
        optional: true
        computed: true
      vendor:
        type: string
        raw_type: TypeString
        optional: true
        computed: true
      technology:
        type: string
        raw_type: TypeString
        optional: true
        computed: true
      behavior:
        type: string
        raw_type: TypeString
        optional: true
        computed: true
      popularity:
        type: string
        raw_type: TypeString
        optional: true
        computed: true
      classification:
        type: string
        raw_type: TypeString
        optional: true
        computed: true
      exclusion:
        type: list
        raw_type: TypeSet
        optional: true
        children:
          id:
            type: integer
            raw_type: TypeInt
            optional: true
      parameters:
        type: list
        raw_type: TypeList
        optional: true
        children:
          id:
            type: integer
            raw_type: TypeInt
            optional: true
            computed: true
          members:
            type: list
            raw_type: TypeList
            optional: true
            children:
              id:
                type: integer
                raw_type: TypeInt
                optional: true
                computed: true
              name:
                type: string
                raw_type: TypeString
                optional: true
                min_length: 0
                max_length: 31
              value:
                type: string
                raw_type: TypeString
                optional: true
                min_length: 0
                max_length: 199
          value:
            type: string
            raw_type: TypeString
            optional: true
            min_length: 0
            max_length: 63
      action:
        type: string
        raw_type: TypeString
        optional: true
        computed: true
      log:
        type: string
        raw_type: TypeString
        optional: true
        computed: true
      log_packet:
        type: string
        raw_type: TypeString
        optional: true
        computed: true
      rate_count:
        type: integer
        raw_type: TypeInt
        optional: true
        min: 0
        max: 65535
      rate_duration:
        type: integer
        raw_type: TypeInt
        optional: true
        computed: true
        min: 1
        max: 65535
      rate_mode:
        type: string
        raw_type: TypeString
        optional: true
        computed: true
      rate_track:
        type: string
        raw_type: TypeString
        optional: true
        computed: true
      session_ttl:
        type: integer
        raw_type: TypeInt
        optional: true
      shaper:
        type: string
        raw_type: TypeString
        optional: true
        min_length: 0
        max_length: 35
      shaper_reverse:
        type: string
        raw_type: TypeString
        optional: true
        min_length: 0
        max_length: 35
      per_ip_shaper:
        type: string
        raw_type: TypeString
        optional: true
        min_length: 0
        max_length: 35
      quarantine:
        type: string
        raw_type: TypeString
        optional: true
        computed: true
      quarantine_expiry:
        type: string
        raw_type: TypeString
        optional: true
        computed: true
      quarantine_log:
        type: string
        raw_type: TypeString
        optional: true
        computed: true
  control_default_network_services:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  default_network_services:
    type: list
    raw_type: TypeList
    optional: true
    children:
      id:
        type: integer
        raw_type: TypeInt
        optional: true
      port:
        type: integer
        raw_type: TypeInt
        optional: true
        min: 0
        max: 65535
      services:
        type: string
        raw_type: TypeString
        optional: true
      violation_action:
        type: string
        raw_type: TypeString
        optional: true
        computed: true
  dynamic_sort_subtable:
    type: string
    raw_type: TypeString
    optional: true
  get_all_tables:
    type: string
    raw_type: TypeString
    optional: true
