id: switchcontroller.stpsettings
version: 7.6.7
source_object: resource_switchcontroller_stpsettings
source:
  kind: terraform
  file: .work\terraform\fortios\resource_switchcontroller_stpsettings.go
attributes:
  vdomparam:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
    force_new: true
  name:
    type: string
    raw_type: TypeString
    optional: true
    min_length: 0
    max_length: 31
  status:
    type: string
    raw_type: TypeString
    optional: true
  revision:
    type: integer
    raw_type: TypeInt
    optional: true
    min: 0
    max: 65535
  hello_time:
    type: integer
    raw_type: TypeInt
    optional: true
    computed: true
    min: 1
    max: 10
  forward_time:
    type: integer
    raw_type: TypeInt
    optional: true
    computed: true
    min: 4
    max: 30
  max_age:
    type: integer
    raw_type: TypeInt
    optional: true
    computed: true
    min: 6
    max: 40
  max_hops:
    type: integer
    raw_type: TypeInt
    optional: true
    computed: true
    min: 1
    max: 40
  pending_timer:
    type: integer
    raw_type: TypeInt
    optional: true
    computed: true
    min: 1
    max: 15
