id: application.unsanctionedapps
version: 7.6.7
source_object: resource_application_unsanctionedapps
source:
  kind: terraform
  file: .work\terraform\fortios\resource_application_unsanctionedapps.go
attributes:
  vdomparam:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
    force_new: true
  update_if_exist:
    type: boolean
    raw_type: TypeBool
    optional: true
    computed: true
  fosid:
    type: integer
    raw_type: TypeInt
    optional: true
    computed: true
    force_new: true
  type:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  app:
    type: integer
    raw_type: TypeInt
    optional: true
  category:
    type: string
    raw_type: TypeString
    optional: true
  status:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
declared_version_support: '>= 8.0.0'
