id: switchcontrollerinitialconfig.vlans
version: 7.6.7
source_object: resource_switchcontrollerinitialconfig_vlans
source:
  kind: terraform
  file: .work\terraform\fortios\resource_switchcontrollerinitialconfig_vlans.go
attributes:
  vdomparam:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
    force_new: true
  optional_vlans:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  default_vlan:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
    min_length: 0
    max_length: 63
  quarantine:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
    min_length: 0
    max_length: 63
  rspan:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
    min_length: 0
    max_length: 63
  voice:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
    min_length: 0
    max_length: 63
  video:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
    min_length: 0
    max_length: 63
  nac:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
    min_length: 0
    max_length: 63
  nac_segment:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
    min_length: 0
    max_length: 63
declared_version_support: '>= 6.4.0'
