id: system.settings
version: 7.6.7
source_object: resource_system_settings
source:
  kind: terraform
  file: .work\terraform\fortios\resource_system_settings.go
attributes:
  vdomparam:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
    force_new: true
  comments:
    type: string
    raw_type: TypeString
    optional: true
    min_length: 0
    max_length: 255
  vdom_type:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  lan_extension_controller_addr:
    type: string
    raw_type: TypeString
    optional: true
    min_length: 0
    max_length: 255
  lan_extension_controller_port:
    type: integer
    raw_type: TypeInt
    optional: true
    computed: true
    min: 1024
    max: 65535
  opmode:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  policy_offload_level:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  inspection_mode:
    type: string
    raw_type: TypeString
    optional: true
  ngfw_mode:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  implicit_allow_dns:
    type: string
    raw_type: TypeString
    optional: true
  ssl_ssh_profile:
    type: string
    raw_type: TypeString
    optional: true
    min_length: 0
    max_length: 35
  consolidated_firewall_mode:
    type: string
    raw_type: TypeString
    optional: true
  http_external_dest:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  firewall_session_dirty:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  manageip:
    type: string
    raw_type: TypeString
    optional: true
  gateway:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  ip:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  manageip6:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  gateway6:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  ip6:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  device:
    type: string
    raw_type: TypeString
    optional: true
    min_length: 0
    max_length: 35
  bfd:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  bfd_desired_min_tx:
    type: integer
    raw_type: TypeInt
    optional: true
    computed: true
    min: 1
    max: 100000
  bfd_required_min_rx:
    type: integer
    raw_type: TypeInt
    optional: true
    computed: true
    min: 1
    max: 100000
  bfd_detect_mult:
    type: integer
    raw_type: TypeInt
    optional: true
    computed: true
    min: 1
    max: 50
  bfd_dont_enforce_src_port:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  utf8_spam_tagging:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  wccp_cache_engine:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  vpn_stats_log:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  vpn_stats_period:
    type: integer
    raw_type: TypeInt
    optional: true
    computed: true
  v4_ecmp_mode:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  mac_ttl:
    type: integer
    raw_type: TypeInt
    optional: true
    computed: true
    min: 300
    max: 8640000
  fw_session_hairpin:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  prp_trailer_action:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  snat_hairpin_traffic:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  dhcp_proxy:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  dhcp_proxy_interface_select_method:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  dhcp_proxy_interface:
    type: string
    raw_type: TypeString
    optional: true
    min_length: 0
    max_length: 15
  dhcp_proxy_vrf_select:
    type: integer
    raw_type: TypeInt
    optional: true
    min: 0
    max: 511
  dhcp_server_ip:
    type: string
    raw_type: TypeString
    optional: true
  dhcp6_server_ip:
    type: string
    raw_type: TypeString
    optional: true
  central_nat:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  gui_default_policy_columns:
    type: list
    raw_type: TypeSet
    optional: true
    children:
      name:
        type: string
        raw_type: TypeString
        optional: true
        min_length: 0
        max_length: 79
  lldp_reception:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  lldp_transmission:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  link_down_access:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  nat46_generate_ipv6_fragment_header:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  nat46_force_ipv4_packet_forwarding:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  nat64_force_ipv6_packet_forwarding:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  detect_unknown_esp:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  intree_ses_best_route:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  auxiliary_session:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  vrf_local_ip_isolation:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  asymroute:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  asymroute_icmp:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  tcp_session_without_syn:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  ses_denied_traffic:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  ses_denied_multicast_traffic:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  strict_src_check:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  src_check_reply:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  allow_linkdown_path:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  asymroute6:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  asymroute6_icmp:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  sctp_session_without_init:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  sip_expectation:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  sip_helper:
    type: string
    raw_type: TypeString
    optional: true
  sip_nat_trace:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  h323_direct_model:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  status:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  sip_tcp_port:
    type: integer
    raw_type: TypeInt
    optional: true
    computed: true
    min: 1
    max: 65535
  sip_udp_port:
    type: integer
    raw_type: TypeInt
    optional: true
    computed: true
    min: 1
    max: 65535
  sip_ssl_port:
    type: integer
    raw_type: TypeInt
    optional: true
    computed: true
    min: 0
    max: 65535
  sccp_port:
    type: integer
    raw_type: TypeInt
    optional: true
    computed: true
    min: 0
    max: 65535
  multicast_forward:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  multicast_ttl_notchange:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  multicast_skip_policy:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  allow_subnet_overlap:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  deny_tcp_with_icmp:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  ecmp_max_paths:
    type: integer
    raw_type: TypeInt
    optional: true
    computed: true
    min: 1
    max: 255
  discovered_device_timeout:
    type: integer
    raw_type: TypeInt
    optional: true
    computed: true
    min: 1
    max: 365
  email_portal_check_dns:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  default_voip_alg_mode:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  gui_icap:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  gui_nat46_64:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  gui_implicit_policy:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  gui_dns_database:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  gui_load_balance:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  gui_multicast_policy:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  gui_dos_policy:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  gui_object_colors:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  gui_route_tag_address_creation:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  gui_replacement_message_groups:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  gui_voip_profile:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  gui_ap_profile:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  gui_security_profile_group:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  gui_dynamic_profile_display:
    type: string
    raw_type: TypeString
    optional: true
  gui_local_in_policy:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  gui_local_reports:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  gui_wanopt_cache:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  gui_explicit_proxy:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  gui_dynamic_routing:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  gui_dlp:
    type: string
    raw_type: TypeString
    optional: true
  gui_sslvpn_personal_bookmarks:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  gui_sslvpn_realms:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  gui_policy_based_ipsec:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  gui_threat_weight:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  gui_multiple_utm_profiles:
    type: string
    raw_type: TypeString
    optional: true
  gui_spamfilter:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  gui_file_filter:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  gui_application_control:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  gui_ips:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  gui_endpoint_control:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  gui_endpoint_control_advanced:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  gui_dhcp_advanced:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  gui_vpn:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  gui_sslvpn:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  gui_wireless_controller:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  gui_advanced_wireless_features:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  gui_switch_controller:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  gui_advanced_switch_features:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  gui_fortiap_split_tunneling:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  gui_webfilter_advanced:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  gui_traffic_shaping:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  gui_wan_load_balancing:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  gui_antivirus:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  gui_webfilter:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  gui_fortitelemetry:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  gui_videofilter:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  gui_dnsfilter:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  gui_waf_profile:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  gui_dlp_profile:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  gui_dlp_advanced:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  gui_virtual_patch_profile:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  gui_casb:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  gui_fortiextender_controller:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  gui_proxy_inspection:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  gui_advanced_policy:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  gui_policy_custom_tags:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  gui_allow_unnamed_policy:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  gui_email_collection:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  gui_domain_ip_reputation:
    type: string
    raw_type: TypeString
    optional: true
  gui_multiple_interface_policy:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  gui_policy_disclaimer:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  gui_ztna:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  gui_reverse_connector:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  gui_ot:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  gui_dynamic_device_os_id:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  gui_gtp:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  location_id:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  gui_per_policy_disclaimer:
    type: string
    raw_type: TypeString
    optional: true
  gui_policy_learning:
    type: string
    raw_type: TypeString
    optional: true
  compliance_check:
    type: string
    raw_type: TypeString
    optional: true
  ike_session_resume:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  ike_quick_crash_detect:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  ike_dn_format:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  ike_policy_route:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  ike_detailed_event_logs:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  ike_proposal_visibility:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  ike_port:
    type: integer
    raw_type: TypeInt
    optional: true
    computed: true
    min: 1024
    max: 65535
  ike_extra_ports:
    type: integer
    raw_type: TypeInt
    optional: true
    min: 1024
    max: 65535
  ike_tcp_service:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  ike_tcp_port:
    type: integer
    raw_type: TypeInt
    optional: true
    computed: true
    min: 1
    max: 65535
  ike_tls_service:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  ike_natt_port:
    type: integer
    raw_type: TypeInt
    optional: true
    min: 1024
    max: 65535
  block_land_attack:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  default_app_port_as_service:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  application_bandwidth_tracking:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  fqdn_session_check:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  ext_resource_session_check:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  dyn_addr_session_check:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  default_policy_expiry_days:
    type: integer
    raw_type: TypeInt
    optional: true
    computed: true
    min: 0
    max: 365
  gui_enforce_change_summary:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  internet_service_database_cache:
    type: string
    raw_type: TypeString
    optional: true
    computed: true
  internet_service_app_ctrl_size:
    type: integer
    raw_type: TypeInt
    optional: true
    computed: true
  dynamic_sort_subtable:
    type: string
    raw_type: TypeString
    optional: true
    default: 'false'
  get_all_tables:
    type: string
    raw_type: TypeString
    optional: true
    default: 'false'
