id: application.group
version: 7.6.7
source:
  kind: fortinet_cli_reference
  url: https://docs.fortinet.com/document/fortigate/7.6.7/cli-reference/293598044/config-application-group
attributes:
  application:
    type: integer
    raw_type: integer
    description: Application ID list. Application IDs.
    min: 0
    max: 4294967295
  behavior:
    type: string
    raw_type: user
    description: Application behavior filter.
    default: all
  category:
    type: integer
    raw_type: integer
    description: Application category ID list. Category IDs.
    min: 0
    max: 4294967295
  comment:
    type: string
    raw_type: var-string
    description: Comments.
    max_length: 255
  name:
    type: string
    raw_type: string
    description: Application group name.
    max_length: 63
  popularity:
    type: enum
    raw_type: option
    description: Application popularity filter (1 - 5, from least to most popular).
    default: 1 2 3 4 5
  protocols:
    type: string
    raw_type: user
    description: Application protocol filter.
    default: all
  risk:
    type: integer
    raw_type: integer
    description: Risk, or impact, of allowing traffic from this application to occur (1 - 5; Low, Elevated, Medium, High,
      and Critical). Risk, or impact, of allowing traffic from this application to occur (1 - 5; Low, Elevated, Medium, High,
      and Critical).
    min: 0
    max: 4294967295
  technology:
    type: string
    raw_type: user
    description: Application technology filter.
    default: all
  type:
    type: enum
    raw_type: option
    description: Application group type.
    default: application
  vendor:
    type: string
    raw_type: user
    description: Application vendor filter.
    default: all
children: {}
