id: azure.vwan-ingress-public-ips
version: 7.6.7
source:
  kind: fortinet_cli_reference
  url: https://docs.fortinet.com/document/fortigate/7.6.7/cli-reference/234828748/config-azure-vwan-ingress-public-ips
attributes:
  ip:
    type: string
    raw_type: string
    description: Public IP address.
    max_length: 15
  name:
    type: string
    raw_type: string
    description: Name of public IP.
    max_length: 127
children: {}
