id: ips.settings
version: 7.6.7
source:
  kind: fortinet_cli_reference
  url: https://docs.fortinet.com/document/fortigate/7.6.7/cli-reference/221048928/config-ips-settings
attributes:
  ha-session-pickup:
    type: enum
    raw_type: option
    description: IPS HA failover session pickup preference.
    default: connectivity
  ips-packet-quota:
    type: integer
    raw_type: integer
    description: Maximum amount of disk space in MB for logged packets when logging to disk. Range depends on disk size.
    default: '0'
    min: 0
    max: 4294967295
  packet-log-history:
    type: integer
    raw_type: integer
    description: Number of packets to capture before and including the one in which the IPS signature is detected (1 - 255).
    default: '1'
    min: 1
    max: 255
  packet-log-memory:
    type: integer
    raw_type: integer
    description: Maximum memory can be used by packet log (64 - 8192 kB).
    default: '256'
    min: 64
    max: 8192
  packet-log-post-attack:
    type: integer
    raw_type: integer
    description: Number of packets to log after the IPS signature is detected (0 - 255).
    default: '0'
    min: 0
    max: 255
  proxy-inline-ips:
    type: enum
    raw_type: option
    description: Enable/disable proxy-mode policy inline IPS support.
    default: enable **
children: {}
