id: switch-controller.network-monitor-settings
version: 7.6.7
source:
  kind: fortinet_cli_reference
  url: https://docs.fortinet.com/document/fortigate/7.6.7/cli-reference/245771094/config-switch-controller-network-monitor-settings
attributes:
  network-monitoring:
    type: enum
    raw_type: option
    description: Enable/disable passive gathering of information by FortiSwitch units concerning other network devices.
    default: disable
children: {}
