id: switch-controller.initial-config.template
version: 7.6.7
source:
  kind: fortinet_cli_reference
  url: https://docs.fortinet.com/document/fortigate/7.6.7/cli-reference/568450468/config-switch-controller-initial-config-template
attributes:
  allowaccess:
    type: enum
    raw_type: option
    description: Permitted types of management access to this interface.
  auto-ip:
    type: enum
    raw_type: option
    description: Automatically allocate interface address and subnet block.
    default: enable
  dhcp-server:
    type: enum
    raw_type: option
    description: Enable/disable a DHCP server on this interface.
    default: disable
  ip:
    type: ipv4-classnet-host
    raw_type: ipv4-classnet-host
    description: Interface IPv4 address and subnet mask.
    default: 0.0.0.0 0.0.0.0
  name:
    type: string
    raw_type: string
    description: Initial config template name.
    max_length: 63
  vlanid:
    type: integer
    raw_type: integer
    description: Unique VLAN ID.
    default: '0'
    min: 1
    max: 4094
children: {}
