id: switch-controller.acl.ingress
version: 7.6.7
source:
  kind: fortinet_cli_reference
  url: https://docs.fortinet.com/document/fortigate/7.6.7/cli-reference/137022238/config-switch-controller-acl-ingress
attributes:
  description:
    type: string
    raw_type: string
    description: Description for the ACL policy.
    max_length: 63
  id:
    type: integer
    raw_type: integer
    description: ACL ID.
    default: '0'
    min: 0
    max: 4294967295
children:
  action:
    attributes:
      count:
        type: enum
        raw_type: option
        description: Enable/disable count.
        default: disable
      drop:
        type: enum
        raw_type: option
        description: Enable/disable drop.
        default: disable
  classifier:
    attributes:
      dst-ip-prefix:
        type: ipv4-classnet
        raw_type: ipv4-classnet
        description: Destination IP address to be matched.
        default: 0.0.0.0 0.0.0.0
      dst-mac:
        type: mac-address
        raw_type: mac-address
        description: Destination MAC address to be matched.
        default: 00:00:00:00:00:00
      src-ip-prefix:
        type: ipv4-classnet
        raw_type: ipv4-classnet
        description: Source IP address to be matched.
        default: 0.0.0.0 0.0.0.0
      src-mac:
        type: mac-address
        raw_type: mac-address
        description: Source MAC address to be matched.
        default: 00:00:00:00:00:00
      vlan:
        type: integer
        raw_type: integer
        description: VLAN ID to be matched.
        default: '0'
        min: 1
        max: 4094
