target:
  vendor: Fortinet
  product: FortiOS
  version: "7.6.7"

sources:
  ansible:
    repository: "https://github.com/fortinet-ansible-dev/ansible-galaxy-fortios-collection.git"
    tag: "2.6.0"
    expected_commit: "5174d341626cb099a079b18276906f3f91f4a110"
    modules_dir: "plugins/modules"
  terraform:
    repository: "https://github.com/fortinetdev/terraform-provider-fortios.git"
    tag: "1.26.0"
    resources_dir: "fortios"
    docs_dir: "website/docs/r"
  fortinet_docs:
    base_host: "docs.fortinet.com"
    cli_reference: "https://docs.fortinet.com/document/fortigate/7.6.7/cli-reference/84566/fortios-cli-reference"
    administration_guide: "https://docs.fortinet.com/document/fortigate/7.6.7/administration-guide/search"
    release_notes: "https://docs.fortinet.com/document/fortigate/7.6.7/fortios-release-notes/743723"
    new_features: "https://docs.fortinet.com/document/fortigate/7.6.0/new-features/51273/7-6-7"
