id: application.custom
version: 7.6.7
source_presence:
  ansible: true
  terraform: true
  cli_reference: true
attributes_flat:
  behavior:
    canonical:
      type: string
      version_ranges: &id001
      - - v6.0.0
        - ''
      description: Custom application signature behavior.
      source_attribute: behavior
    canonical_source: merged
    field_sources:
      type: cli_reference
      version_ranges: ansible
      description: cli_reference
      source_attribute: cli_reference
    evidence:
      ansible:
        type: string
        raw_type: string
        version_ranges: *id001
        description: Custom application signature behavior.
        source_attribute: behavior
      terraform:
        type: string
        raw_type: TypeString
        optional: true
        source_attribute: behavior
      cli_reference:
        type: string
        raw_type: user
        description: Custom application signature behavior.
        source_attribute: behavior
    sources:
    - ansible
    - cli_reference
    - terraform
  category:
    canonical:
      type: integer
      required: true
      version_ranges: &id002
      - - v6.0.0
        - ''
      default: '0'
      min: 0
      max: 4294967295
      description: Custom application category ID (use ? to view available options).
      source_attribute: category
    canonical_source: merged
    field_sources:
      type: cli_reference
      required: terraform
      version_ranges: ansible
      default: cli_reference
      min: cli_reference
      max: cli_reference
      description: cli_reference
      source_attribute: cli_reference
    evidence:
      ansible:
        type: integer
        raw_type: integer
        version_ranges: *id002
        description: Custom application category ID (use ? to view available options).
        source_attribute: category
      terraform:
        type: integer
        raw_type: TypeInt
        required: true
        source_attribute: category
      cli_reference:
        type: integer
        raw_type: integer
        description: Custom application category ID (use ? to view available options).
        default: '0'
        min: 0
        max: 4294967295
        source_attribute: category
    sources:
    - ansible
    - cli_reference
    - terraform
  comment:
    canonical:
      type: string
      version_ranges: &id003
      - - v6.0.0
        - ''
      min_length: 0
      max_length: 63
      description: Comment.
      source_attribute: comment
    canonical_source: merged
    field_sources:
      type: cli_reference
      version_ranges: ansible
      min_length: terraform
      max_length: cli_reference
      description: cli_reference
      source_attribute: cli_reference
    evidence:
      ansible:
        type: string
        raw_type: string
        version_ranges: *id003
        description: Comment.
        source_attribute: comment
      terraform:
        type: string
        raw_type: TypeString
        optional: true
        min_length: 0
        max_length: 63
        source_attribute: comment
      cli_reference:
        type: string
        raw_type: string
        description: Comment.
        max_length: 63
        source_attribute: comment
    sources:
    - ansible
    - cli_reference
    - terraform
  fosid:
    canonical:
      type: integer
      source_attribute: fosid
    canonical_source: merged
    field_sources:
      type: terraform
      source_attribute: terraform
    evidence:
      terraform:
        type: integer
        raw_type: TypeInt
        optional: true
        computed: true
        source_attribute: fosid
    sources:
    - terraform
  id:
    canonical:
      type: integer
      default: '0'
      min: 0
      max: 4294967295
      description: Custom application category ID (use ? to view available options). Read-only.
      source_attribute: id
    canonical_source: merged
    field_sources:
      type: cli_reference
      default: cli_reference
      min: cli_reference
      max: cli_reference
      description: cli_reference
      source_attribute: cli_reference
    evidence:
      cli_reference:
        type: integer
        raw_type: integer
        description: Custom application category ID (use ? to view available options). Read-only.
        default: '0'
        min: 0
        max: 4294967295
        source_attribute: id
    sources:
    - cli_reference
  name:
    canonical:
      type: string
      min_length: 0
      max_length: 63
      source_attribute: name
    canonical_source: merged
    field_sources:
      type: terraform
      min_length: terraform
      max_length: terraform
      source_attribute: terraform
    evidence:
      terraform:
        type: string
        raw_type: TypeString
        optional: true
        computed: true
        min_length: 0
        max_length: 63
        source_attribute: name
    sources:
    - terraform
  protocol:
    canonical:
      type: string
      version_ranges: &id004
      - - v6.0.0
        - ''
      description: Custom application signature protocol.
      source_attribute: protocol
    canonical_source: merged
    field_sources:
      type: cli_reference
      version_ranges: ansible
      description: cli_reference
      source_attribute: cli_reference
    evidence:
      ansible:
        type: string
        raw_type: string
        version_ranges: *id004
        description: Custom application signature protocol.
        source_attribute: protocol
      terraform:
        type: string
        raw_type: TypeString
        optional: true
        source_attribute: protocol
      cli_reference:
        type: string
        raw_type: user
        description: Custom application signature protocol.
        source_attribute: protocol
    sources:
    - ansible
    - cli_reference
    - terraform
  signature:
    canonical:
      type: string
      version_ranges: &id005
      - - v6.0.0
        - ''
      min_length: 0
      max_length: 4095
      description: The text that makes up the actual custom application signature.
      source_attribute: signature
    canonical_source: merged
    field_sources:
      type: cli_reference
      version_ranges: ansible
      min_length: terraform
      max_length: cli_reference
      description: cli_reference
      source_attribute: cli_reference
    evidence:
      ansible:
        type: string
        raw_type: string
        version_ranges: *id005
        description: The text that makes up the actual custom application signature.
        source_attribute: signature
      terraform:
        type: string
        raw_type: TypeString
        optional: true
        min_length: 0
        max_length: 4095
        source_attribute: signature
      cli_reference:
        type: string
        raw_type: var-string
        description: The text that makes up the actual custom application signature.
        max_length: 4095
        source_attribute: signature
    sources:
    - ansible
    - cli_reference
    - terraform
  tag:
    canonical:
      type: string
      required: true
      version_ranges: &id006
      - - v6.0.0
        - ''
      min_length: 0
      max_length: 63
      description: Signature tag.
      source_attribute: tag
    canonical_source: merged
    field_sources:
      type: cli_reference
      required: ansible
      version_ranges: ansible
      min_length: terraform
      max_length: cli_reference
      description: cli_reference
      source_attribute: cli_reference
    evidence:
      ansible:
        type: string
        raw_type: string
        required: true
        version_ranges: *id006
        description: Signature tag.
        source_attribute: tag
      terraform:
        type: string
        raw_type: TypeString
        optional: true
        computed: true
        force_new: true
        min_length: 0
        max_length: 63
        source_attribute: tag
      cli_reference:
        type: string
        raw_type: string
        description: Signature tag.
        max_length: 63
        source_attribute: tag
    sources:
    - ansible
    - cli_reference
    - terraform
  technology:
    canonical:
      type: string
      version_ranges: &id007
      - - v6.0.0
        - ''
      description: Custom application signature technology.
      source_attribute: technology
    canonical_source: merged
    field_sources:
      type: cli_reference
      version_ranges: ansible
      description: cli_reference
      source_attribute: cli_reference
    evidence:
      ansible:
        type: string
        raw_type: string
        version_ranges: *id007
        description: Custom application signature technology.
        source_attribute: technology
      terraform:
        type: string
        raw_type: TypeString
        optional: true
        source_attribute: technology
      cli_reference:
        type: string
        raw_type: user
        description: Custom application signature technology.
        source_attribute: technology
    sources:
    - ansible
    - cli_reference
    - terraform
  update_if_exist:
    canonical:
      type: boolean
      source_attribute: update_if_exist
    canonical_source: merged
    field_sources:
      type: terraform
      source_attribute: terraform
    evidence:
      terraform:
        type: boolean
        raw_type: TypeBool
        optional: true
        computed: true
        source_attribute: update_if_exist
    sources:
    - terraform
  vdomparam:
    canonical:
      type: string
      source_attribute: vdomparam
    canonical_source: merged
    field_sources:
      type: terraform
      source_attribute: terraform
    evidence:
      terraform:
        type: string
        raw_type: TypeString
        optional: true
        computed: true
        force_new: true
        source_attribute: vdomparam
    sources:
    - terraform
  vendor:
    canonical:
      type: string
      version_ranges: &id008
      - - v6.0.0
        - ''
      description: Custom application signature vendor.
      source_attribute: vendor
    canonical_source: merged
    field_sources:
      type: cli_reference
      version_ranges: ansible
      description: cli_reference
      source_attribute: cli_reference
    evidence:
      ansible:
        type: string
        raw_type: string
        version_ranges: *id008
        description: Custom application signature vendor.
        source_attribute: vendor
      terraform:
        type: string
        raw_type: TypeString
        optional: true
        source_attribute: vendor
      cli_reference:
        type: string
        raw_type: user
        description: Custom application signature vendor.
        source_attribute: vendor
    sources:
    - ansible
    - cli_reference
    - terraform
conflicts: []
