id: switch-controller.initial-config.vlans
version: 7.6.7
source_presence:
  ansible: true
  terraform: true
  cli_reference: true
attributes_flat:
  default_vlan:
    canonical:
      type: string
      references: &id002
      - switch-controller.initial-config.template.name
      version_ranges: &id001
      - - v6.4.0
        - ''
      default: _default
      min_length: 0
      max_length: 63
      description: Default VLAN (native) assigned to all switch ports upon discovery.
      source_attribute: default-vlan
    canonical_source: merged
    field_sources:
      type: cli_reference
      references: ansible
      version_ranges: ansible
      default: cli_reference
      min_length: terraform
      max_length: cli_reference
      description: cli_reference
      source_attribute: cli_reference
    evidence:
      ansible:
        type: string
        raw_type: string
        version_ranges: *id001
        description: Default VLAN (native) assigned to all switch ports upon discovery. Source switch-controller.initial-config.template.name.
        references: *id002
        source_attribute: default_vlan
      terraform:
        type: string
        raw_type: TypeString
        optional: true
        computed: true
        min_length: 0
        max_length: 63
        source_attribute: default_vlan
      cli_reference:
        type: string
        raw_type: string
        description: Default VLAN (native) assigned to all switch ports upon discovery.
        default: _default
        max_length: 63
        source_attribute: default-vlan
    sources:
    - ansible
    - cli_reference
    - terraform
  nac:
    canonical:
      type: string
      references: &id004
      - switch-controller.initial-config.template.name
      version_ranges: &id003
      - - v6.4.0
        - ''
      default: onboarding
      min_length: 0
      max_length: 63
      description: VLAN for NAC onboarding devices.
      source_attribute: nac
    canonical_source: merged
    field_sources:
      type: cli_reference
      references: ansible
      version_ranges: ansible
      default: cli_reference
      min_length: terraform
      max_length: cli_reference
      description: cli_reference
      source_attribute: cli_reference
    evidence:
      ansible:
        type: string
        raw_type: string
        version_ranges: *id003
        description: VLAN for NAC onboarding devices. Source switch-controller.initial-config.template.name.
        references: *id004
        source_attribute: nac
      terraform:
        type: string
        raw_type: TypeString
        optional: true
        computed: true
        min_length: 0
        max_length: 63
        source_attribute: nac
      cli_reference:
        type: string
        raw_type: string
        description: VLAN for NAC onboarding devices.
        default: onboarding
        max_length: 63
        source_attribute: nac
    sources:
    - ansible
    - cli_reference
    - terraform
  nac_segment:
    canonical:
      type: string
      references: &id006
      - switch-controller.initial-config.template.name
      version_ranges: &id005
      - - v7.0.1
        - ''
      default: nac_segment
      min_length: 0
      max_length: 63
      description: VLAN for NAC segment primary interface.
      source_attribute: nac-segment
    canonical_source: merged
    field_sources:
      type: cli_reference
      references: ansible
      version_ranges: ansible
      default: cli_reference
      min_length: terraform
      max_length: cli_reference
      description: cli_reference
      source_attribute: cli_reference
    evidence:
      ansible:
        type: string
        raw_type: string
        version_ranges: *id005
        description: VLAN for NAC segment primary interface. Source switch-controller.initial-config.template.name.
        references: *id006
        source_attribute: nac_segment
      terraform:
        type: string
        raw_type: TypeString
        optional: true
        computed: true
        min_length: 0
        max_length: 63
        source_attribute: nac_segment
      cli_reference:
        type: string
        raw_type: string
        description: VLAN for NAC segment primary interface.
        default: nac_segment
        max_length: 63
        source_attribute: nac-segment
    sources:
    - ansible
    - cli_reference
    - terraform
  optional_vlans:
    canonical:
      type: enum
      version_ranges: &id008
      - - v7.6.3
        - ''
      choices: &id007
      - enable
      - disable
      default: enable
      description: Auto-generate pre-configured VLANs upon switch discovery.
      source_attribute: optional-vlans
    canonical_source: merged
    field_sources:
      type: cli_reference
      version_ranges: ansible
      choices: ansible
      default: cli_reference
      description: cli_reference
      source_attribute: cli_reference
    evidence:
      ansible:
        type: enum
        raw_type: string
        choices: *id007
        version_ranges: *id008
        description: Auto-generate pre-configured VLANs upon switch discovery.
        source_attribute: optional_vlans
      terraform:
        type: string
        raw_type: TypeString
        optional: true
        computed: true
        source_attribute: optional_vlans
      cli_reference:
        type: enum
        raw_type: option
        description: Auto-generate pre-configured VLANs upon switch discovery.
        default: enable
        source_attribute: optional-vlans
    sources:
    - ansible
    - cli_reference
    - terraform
  quarantine:
    canonical:
      type: string
      references: &id010
      - switch-controller.initial-config.template.name
      version_ranges: &id009
      - - v6.4.0
        - ''
      default: quarantine
      min_length: 0
      max_length: 63
      description: VLAN for quarantined traffic.
      source_attribute: quarantine
    canonical_source: merged
    field_sources:
      type: cli_reference
      references: ansible
      version_ranges: ansible
      default: cli_reference
      min_length: terraform
      max_length: cli_reference
      description: cli_reference
      source_attribute: cli_reference
    evidence:
      ansible:
        type: string
        raw_type: string
        version_ranges: *id009
        description: VLAN for quarantined traffic. Source switch-controller.initial-config.template.name.
        references: *id010
        source_attribute: quarantine
      terraform:
        type: string
        raw_type: TypeString
        optional: true
        computed: true
        min_length: 0
        max_length: 63
        source_attribute: quarantine
      cli_reference:
        type: string
        raw_type: string
        description: VLAN for quarantined traffic.
        default: quarantine
        max_length: 63
        source_attribute: quarantine
    sources:
    - ansible
    - cli_reference
    - terraform
  rspan:
    canonical:
      type: string
      references: &id012
      - switch-controller.initial-config.template.name
      version_ranges: &id011
      - - v6.4.0
        - ''
      default: rspan
      min_length: 0
      max_length: 63
      description: VLAN for RSPAN/ERSPAN mirrored traffic.
      source_attribute: rspan
    canonical_source: merged
    field_sources:
      type: cli_reference
      references: ansible
      version_ranges: ansible
      default: cli_reference
      min_length: terraform
      max_length: cli_reference
      description: cli_reference
      source_attribute: cli_reference
    evidence:
      ansible:
        type: string
        raw_type: string
        version_ranges: *id011
        description: VLAN for RSPAN/ERSPAN mirrored traffic. Source switch-controller.initial-config.template.name.
        references: *id012
        source_attribute: rspan
      terraform:
        type: string
        raw_type: TypeString
        optional: true
        computed: true
        min_length: 0
        max_length: 63
        source_attribute: rspan
      cli_reference:
        type: string
        raw_type: string
        description: VLAN for RSPAN/ERSPAN mirrored traffic.
        default: rspan
        max_length: 63
        source_attribute: rspan
    sources:
    - ansible
    - cli_reference
    - terraform
  vdomparam:
    canonical:
      type: string
      source_attribute: vdomparam
    canonical_source: merged
    field_sources:
      type: terraform
      source_attribute: terraform
    evidence:
      terraform:
        type: string
        raw_type: TypeString
        optional: true
        computed: true
        force_new: true
        source_attribute: vdomparam
    sources:
    - terraform
  video:
    canonical:
      type: string
      references: &id014
      - switch-controller.initial-config.template.name
      version_ranges: &id013
      - - v6.4.0
        - ''
      default: video
      min_length: 0
      max_length: 63
      description: VLAN dedicated for video devices.
      source_attribute: video
    canonical_source: merged
    field_sources:
      type: cli_reference
      references: ansible
      version_ranges: ansible
      default: cli_reference
      min_length: terraform
      max_length: cli_reference
      description: cli_reference
      source_attribute: cli_reference
    evidence:
      ansible:
        type: string
        raw_type: string
        version_ranges: *id013
        description: VLAN dedicated for video devices. Source switch-controller.initial-config.template.name.
        references: *id014
        source_attribute: video
      terraform:
        type: string
        raw_type: TypeString
        optional: true
        computed: true
        min_length: 0
        max_length: 63
        source_attribute: video
      cli_reference:
        type: string
        raw_type: string
        description: VLAN dedicated for video devices.
        default: video
        max_length: 63
        source_attribute: video
    sources:
    - ansible
    - cli_reference
    - terraform
  voice:
    canonical:
      type: string
      references: &id016
      - switch-controller.initial-config.template.name
      version_ranges: &id015
      - - v6.4.0
        - ''
      default: voice
      min_length: 0
      max_length: 63
      description: VLAN dedicated for voice devices.
      source_attribute: voice
    canonical_source: merged
    field_sources:
      type: cli_reference
      references: ansible
      version_ranges: ansible
      default: cli_reference
      min_length: terraform
      max_length: cli_reference
      description: cli_reference
      source_attribute: cli_reference
    evidence:
      ansible:
        type: string
        raw_type: string
        version_ranges: *id015
        description: VLAN dedicated for voice devices. Source switch-controller.initial-config.template.name.
        references: *id016
        source_attribute: voice
      terraform:
        type: string
        raw_type: TypeString
        optional: true
        computed: true
        min_length: 0
        max_length: 63
        source_attribute: voice
      cli_reference:
        type: string
        raw_type: string
        description: VLAN dedicated for voice devices.
        default: voice
        max_length: 63
        source_attribute: voice
    sources:
    - ansible
    - cli_reference
    - terraform
conflicts: []
