id: switch-controller.lldp-settings
version: 7.6.7
source_presence:
  ansible: true
  terraform: true
  cli_reference: true
attributes_flat:
  device_detection:
    canonical:
      type: enum
      version_ranges: &id002
      - - v6.4.0
        - ''
      choices: &id001
      - disable
      - enable
      default: enable
      description: Enable/disable dynamic detection of LLDP neighbor devices for VLAN assignment.
      source_attribute: device-detection
    canonical_source: merged
    field_sources:
      type: cli_reference
      version_ranges: ansible
      choices: ansible
      default: cli_reference
      description: cli_reference
      source_attribute: cli_reference
    evidence:
      ansible:
        type: enum
        raw_type: string
        choices: *id001
        version_ranges: *id002
        description: Enable/disable dynamic detection of LLDP neighbor devices for VLAN assignment.
        source_attribute: device_detection
      terraform:
        type: string
        raw_type: TypeString
        optional: true
        computed: true
        source_attribute: device_detection
      cli_reference:
        type: enum
        raw_type: option
        description: Enable/disable dynamic detection of LLDP neighbor devices for VLAN assignment.
        default: enable
        source_attribute: device-detection
    sources:
    - ansible
    - cli_reference
    - terraform
  fast_start_interval:
    canonical:
      type: integer
      version_ranges: &id003
      - - v6.0.0
        - ''
      default: '2'
      min: 0
      max: 255
      description: Frequency of LLDP PDU transmission from FortiSwitch for the first 4 packets when the link is up (2 - 5
        sec, default = 2, 0 = disable fast start).
      source_attribute: fast-start-interval
    canonical_source: merged
    field_sources:
      type: cli_reference
      version_ranges: ansible
      default: cli_reference
      min: cli_reference
      max: cli_reference
      description: cli_reference
      source_attribute: cli_reference
    evidence:
      ansible:
        type: integer
        raw_type: integer
        version_ranges: *id003
        description: Frequency of LLDP PDU transmission from FortiSwitch for the first 4 packets when the link is up (2 -
          5 sec).
        source_attribute: fast_start_interval
      terraform:
        type: integer
        raw_type: TypeInt
        optional: true
        computed: true
        min: 0
        max: 255
        source_attribute: fast_start_interval
      cli_reference:
        type: integer
        raw_type: integer
        description: Frequency of LLDP PDU transmission from FortiSwitch for the first 4 packets when the link is up (2 -
          5 sec, default = 2, 0 = disable fast start).
        default: '2'
        min: 0
        max: 255
        source_attribute: fast-start-interval
    sources:
    - ansible
    - cli_reference
    - terraform
  management_interface:
    canonical:
      type: enum
      version_ranges: &id005
      - - v6.0.0
        - ''
      choices: &id004
      - internal
      - mgmt
      default: internal
      description: Primary management interface to be advertised in LLDP and CDP PDUs.
      source_attribute: management-interface
    canonical_source: merged
    field_sources:
      type: cli_reference
      version_ranges: ansible
      choices: ansible
      default: cli_reference
      description: cli_reference
      source_attribute: cli_reference
    evidence:
      ansible:
        type: enum
        raw_type: string
        choices: *id004
        version_ranges: *id005
        description: Primary management interface to be advertised in LLDP and CDP PDUs.
        source_attribute: management_interface
      terraform:
        type: string
        raw_type: TypeString
        optional: true
        computed: true
        source_attribute: management_interface
      cli_reference:
        type: enum
        raw_type: option
        description: Primary management interface to be advertised in LLDP and CDP PDUs.
        default: internal
        source_attribute: management-interface
    sources:
    - ansible
    - cli_reference
    - terraform
  status:
    canonical:
      type: string
      source_attribute: status
    canonical_source: merged
    field_sources:
      type: terraform
      source_attribute: terraform
    evidence:
      terraform:
        type: string
        raw_type: TypeString
        optional: true
        source_attribute: status
    sources:
    - terraform
  tx_hold:
    canonical:
      type: integer
      version_ranges: &id006
      - - v6.0.0
        - ''
      default: '4'
      min: 1
      max: 16
      description: Number of tx-intervals before local LLDP data expires (1 - 16, default = 4). Packet TTL is tx-hold * tx-interval.
      source_attribute: tx-hold
    canonical_source: merged
    field_sources:
      type: cli_reference
      version_ranges: ansible
      default: cli_reference
      min: cli_reference
      max: cli_reference
      description: cli_reference
      source_attribute: cli_reference
    evidence:
      ansible:
        type: integer
        raw_type: integer
        version_ranges: *id006
        description: Number of tx-intervals before local LLDP data expires (1 - 16). Packet TTL is tx-hold * tx-interval.
        source_attribute: tx_hold
      terraform:
        type: integer
        raw_type: TypeInt
        optional: true
        computed: true
        min: 1
        max: 16
        source_attribute: tx_hold
      cli_reference:
        type: integer
        raw_type: integer
        description: Number of tx-intervals before local LLDP data expires (1 - 16, default = 4). Packet TTL is tx-hold *
          tx-interval.
        default: '4'
        min: 1
        max: 16
        source_attribute: tx-hold
    sources:
    - ansible
    - cli_reference
    - terraform
  tx_interval:
    canonical:
      type: integer
      version_ranges: &id007
      - - v6.0.0
        - ''
      default: '30'
      min: 5
      max: 4095
      description: Frequency of LLDP PDU transmission from FortiSwitch (5 - 4095 sec, default = 30). Packet TTL is tx-hold
        * tx-interval.
      source_attribute: tx-interval
    canonical_source: merged
    field_sources:
      type: cli_reference
      version_ranges: ansible
      default: cli_reference
      min: cli_reference
      max: cli_reference
      description: cli_reference
      source_attribute: cli_reference
    evidence:
      ansible:
        type: integer
        raw_type: integer
        version_ranges: *id007
        description: Frequency of LLDP PDU transmission from FortiSwitch (5 - 4095 sec). Packet TTL is tx-hold * tx-interval.
        source_attribute: tx_interval
      terraform:
        type: integer
        raw_type: TypeInt
        optional: true
        computed: true
        min: 5
        max: 4095
        source_attribute: tx_interval
      cli_reference:
        type: integer
        raw_type: integer
        description: Frequency of LLDP PDU transmission from FortiSwitch (5 - 4095 sec, default = 30). Packet TTL is tx-hold
          * tx-interval.
        default: '30'
        min: 5
        max: 4095
        source_attribute: tx-interval
    sources:
    - ansible
    - cli_reference
    - terraform
  vdomparam:
    canonical:
      type: string
      source_attribute: vdomparam
    canonical_source: merged
    field_sources:
      type: terraform
      source_attribute: terraform
    evidence:
      terraform:
        type: string
        raw_type: TypeString
        optional: true
        computed: true
        force_new: true
        source_attribute: vdomparam
    sources:
    - terraform
conflicts: []
